### ISSUE TITLE
'n' in verbs - treatment

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#100]
1.	Right now the machine derives zvaYja! AzIrliG in the following manner.

By lopo vyorvali (6.4.65) :
लोपो व्योर्वलि (६.४.६५) :
1 - स्वञ्ज्+सीस्त
By coH kuH (8.2.30) :
चोः कुः (८.२.३०) :
1 - स्वञ्ग्+सीस्त
By nimittApAye naimittikasyApyapAyaH (pa) :
निमित्तापाये नैमित्तिकस्याप्यपायः (प) :
1 - स्वङ्ग्+सीस्त
By AdezapratyayayoH (8.3.59) :
आदेशप्रत्यययोः (८.३.५९) :
1 - स्वङ्ग्+षीष्त
By STunA STuH (8.4.41) and na padAntATToraNam (8.4.42) and toH Si (8.4.43) :
ष्टुना ष्टुः (८.४.४१), न पदान्ताट्टोरणाम्‌ (८.४.४२) तथा तोः षि (८.४.४३) :
1 - स्वङ्ग्षीष्ट
By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - स्वङ्क्षीष्ट
By khari ca (8.4.55) :
N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :
खरि च (८.४.५५) :
खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।
1 - स्वङ्क्षीष्ट

Whereas sahajabodha part 2 page 138 says this:

![capture](https://cloud.githubusercontent.com/assets/5755132/5782008/9a40454c-9ddd-11e4-90b0-68b87e58739a.PNG)

Is this mandatory to convert it to ‘n’ or is it OK to continue with nimittApAye naimittikasyApyapAyam ?

**Comment by mrudani** [comment]
वस्तुतः तत्र न् एवासीत्. तदधुना परे विद्यमानवर्णं निमित्तीकृत्य तद्वर्गपञ्चमवर्ण इव परिवर्तितः. यदा सः निमित्तः वर्णान्तरः सम्पन्नः तदा निमित्तापायेव इत्यादि न्यायेन पुनः न् इति स्वस्वरूपमाप्नोति.  न तु साक्षात् वर्णान्तरत्वेन परिणमति.

**Comment by mrudani** [comment]
वस्तुतः तत्र न् एवासीत्. तदधुना परे विद्यमानवर्णं निमित्तीकृत्य तद्वर्गपञ्चमवर्ण इव परिवर्तितः. यदा सः निमित्तः वर्णान्तरः सम्पन्नः तदा निमित्तापायेव इत्यादि न्यायेन पुनः न् इति स्वस्वरूपमाप्नोति.  न तु साक्षात् वर्णान्तरत्वेन परिणमति.

**Comment by drdhaval2785** [comment]
Done. Closing the issue
