### ISSUE TITLE
जिँ॒ - जये, भ्वादि, कर्मणि, लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1000]
अन्तिमं रूपम्‌

1 - जियते
अकृत्सार्वधातुकयोः दीर्घः इति दीर्घः भवेत्, जीयते इति भवेत्।

**Comment by drdhaval2785** [comment]
Happy Deepavali @mrudani 
I will be handling these issues soon.
Good to see this great feedback.
