### ISSUE TITLE
सह्‌ - सेट्‌ / वेट्‌ ?

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#103]
Database of verbs says षहँ is सेट्‌.
sahajabodha 2, p. 149 says it is वेट्‌.
What is correct ?

![capture](https://cloud.githubusercontent.com/assets/5755132/5791804/7e3f2890-9f18-11e4-967f-00fd76198bef.PNG)

**Comment by Shalu411** [comment]
Which database is that? Mihail's ? Did you check with others? Lets try different sources and take majority? Or wait for authentic resources to speak. :)

**Comment by mrudani** [comment]
तीषसहलुभरुषरिषः इति सूत्रेण तकारादि-आर्धदातुकप्रत्ययेषु परेषु वा इडागमः विधीयते. अतः वेट् इति लिखितम्. तेन लुट् लकारे सहिता - सोढा इति भवति.

**Comment by drdhaval2785** [comment]
Great. Grammar resolved. Coding pending.

**Comment by drdhaval2785** [comment]
#121 says that there are no 'veT' entries in our database.
Tracking as separate generic issue rather than single occurrences.
Closing the issue
