### ISSUE TITLE
वसँ, कर्तरि, लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1030]
अन्तिमं रूपम्‌

1 - वसयति
वासयति इति भवेत्।

**Comment by drdhaval2785** [comment]
अदन्ते वसयति / सकारान्ते वासयति इति मे मतिः ।

**Comment by drdhaval2785** [comment]
@mrudani Any solution?

**Comment by drdhaval2785** [comment]
mAdhavIya

वस निवासे
 वसयति ) 396
