### ISSUE TITLE
व्येञ्, कर्मणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1036]
अन्तिमं रूपम्‌

1 - व्येयते
वचिस्वपियजादीनां किति इति सम्प्रसारणे कृते वीयते इति सिध्यति।

**Comment by drdhaval2785** [comment]
Sorry @mrudani 
I didn't upload the corrected code for samprasarana (corrected because of previous corrections).
I have uploaded the corrected code.
Mostly you should not see samprasarana errors now.
