### ISSUE TITLE
दुहँ, कर्मणि, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1038]
आदेशप्रत्यययोः (8.3.59) :

1 - अधुघ्+ष्+आताम्

खरि च (8.4.55) :

1 - अधुक्षाताम्
------------------------------
आदौ चर्त्वम् अनन्तरं मूर्धन्यादेशः इति क्रमः।

**Comment by mrudani** [comment]
आदेशप्रत्यययोः (8.3.59) :

1 - अधुघ्+ष+थास्

2 - अदुघ्+धास्

ससजुषो रुः (8.2.66) :

1 - अधुघ्+ष+थारुँ

2 - अदुघ्+धारुँ
------------------------------
अत्र चर्त्वादिकं कृत्वा रुत्वादीनि कार्याणि कर्तव्याणि।

**Comment by drdhaval2785** [comment]
The orders are not correctable as of now.

**Comment by drdhaval2785** [comment]
>आदौ चर्त्वम् अनन्तरं मूर्धन्यादेशः इति क्रमः।

पूर्वत्रासिद्धमिति न्यायेनानुपूर्व्येणैव सूत्रोपस्थापनमिति मे मतिः ।

**Comment by drdhaval2785** [comment]
>अत्र चर्त्वादिकं कृत्वा रुत्वादीनि कार्याणि कर्तव्याणि।

Not possible as of now.

**Comment by drdhaval2785** [comment]
Pending to be handled at https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0004 too.

**Comment by akprasad** [comment]
@drdhaval2785 this is [fixed](https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=02.0004) in the latest release.
