### ISSUE TITLE
अभ्यासाच्च॥ ७।३।५५ and लुङि च॥ २।४।४३

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#104]
sahajabodha part 2 page page 185 has the following derivation for 'han':
![capture](https://cloud.githubusercontent.com/assets/5755132/6020715/4837c012-abd5-11e4-9d0b-60c11e40b336.PNG)

Machine gives the following derivation -
```
1 - हनँ+णिच्+तिप्

By luGi ca (2.4.43) :

लुङि च (२.४.४३) :

1 - वधँ+णिच्+तिप्
```

What is correct ? Should it have vadh Adesha or not ?

**Comment by mrudani** [comment]
हन् धातोः वधादेशः मात्रं लुङि परे एव विदधात्येतत् सूत्रं - लुङि च इति. सहजबोधे यः क्रमः दर्शितः सः णिजन्तस्य लुङ्विधाने करणीयः, न तु सामान्य लुङि.

**Comment by drdhaval2785** [comment]
Closed
