### ISSUE TITLE
ज्या, यङ्लुकि, मध्य.द्वि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1042]
अन्तिमं रूपम्‌

1 - जाजिथः
------------------------
जाजीथः इति भवेत्।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/ab8f7a3bc787200b860fc1f2d583ee811e65f9c1 closed this.
