### ISSUE TITLE
दो, कर्मणि, लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1044]
अन्तिमं रूपम्‌

1 - दायते
अत्र घुमास्थागापाजहातिसां हलि इति ईत्त्वं स्यात्।

**Comment by drdhaval2785** [comment]
Yes. Some Swami ji discussed this on whatsapp with me.

Coder's note -

If possible try to do this without separately clubbing all sUtras of dhAtu
modifications for yak, san, yaNluk,... etc.

Keep it generic. All these issue arise when I forgot to add some such sUtra
in bunch for specific sanAdi, yak etc.

**Comment by drdhaval2785** [comment]
The issue was not what I thought.
It was just because the ghumAsthA.... was applied before Adeca upadeze...
Changing the location after Adeca helped.
