### ISSUE TITLE
चक्षिङ् लिटि रूपत्रयं भवति 

### ISSUE THREAD

**Issue by raghubhaijoshi** [drdhaval2785/SanskritVerb#1046]
अत्र 'वा लिटि' इत्यनेन ख्याञादेशे ञित्त्यात्पदद्वयमिति। परस्मपैदमात्मनेपदं चेत्यर्थः। चख्यौ इति। ख्शादेशस्य शस्य वत्वपक्षे "आत औ णलः" इति भावः

**Comment by drdhaval2785** [comment]
Agreed. mAdhavIya also says so.
