### ISSUE TITLE
Better code organization..

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#1048]
The scripts folder can be organized better. As it is, it is quite intimidating. For example you can create a separate module for the transcoding stuff (separately you can just delete it and start using the pip module I recently published).

I hope you're using a good IDE while developing (I use intellij idea), which will make all such code refactoring easy..

**Comment by drdhaval2785** [comment]
The code as it stands was written by quite immature me. Somehow works. Not possible to refactor without drastic results.
