### ISSUE TITLE
चकासृ दीप्तौ (अदादि) लङि, अचकात् भवेत् 

### ISSUE THREAD

**Issue by raghubhaijoshi** [drdhaval2785/SanskritVerb#1049]
अचकात् - अचकाद्     अचकास् + ति इति स्थिते "तिप्यनस्ते" इति सकारस्य दकारे , इलोपे, तलोपे, विकल्पेन चर्त्वे  अचकात् - अचकाद् इति भवेत् ।

**Comment by drdhaval2785** [comment]
Removed trailing '+' marks. Look for disasters if any.
