### ISSUE TITLE
डुपचष् लिट्लकार उत्तमपुरुष एकवचन, पपच पपाच

### ISSUE THREAD

**Issue by jbabuc** [drdhaval2785/SanskritVerb#1051]
डुपचष् लिट्लकार उत्तमपुरुष एकवचन, पपच पपाच. The forms are correct however it fails to display that vrriddhi vikalpa is happening due to sutra णलुत्तमो वा 7.1.91. 

Thanks.

**Comment by drdhaval2785** [comment]
Thanks for your report. Will post here once it is corrected.

**Comment by drdhaval2785** [comment]
It is corrected in my code. It will take some time before it is visible on website.
Will post when website is in sync with current code.
