### ISSUE TITLE
अभिनः

### ISSUE THREAD

**Issue by jbabuc** [drdhaval2785/SanskritVerb#1052]
भिदिर् रुधादिः लङ् सिपि परे दश्च८.२.७५ इति दकारस्य वा रेफादेशः विसर्गः अभिनः इति न दृश्यते। ॐ।

**Comment by drdhaval2785** [comment]
धन्यवादाः । सम्यक् कृत्वात्रैव ज्ञापयिष्यामि ।
अन्यान्यपि धातुरूपाणि परीक्ष्य दोषाः सूच्याः । कृतज्ञोऽस्मि ।

**Comment by drdhaval2785** [comment]
Corrected in local machine. Pending to upload to server.

**Comment by drdhaval2785** [comment]
Corrected on server.
![screenshot from 2017-12-15 14-57-07](https://user-images.githubusercontent.com/5755132/34035503-3f1a11c2-e1a8-11e7-915e-0f7a63a5cddf.png)
