### ISSUE TITLE
JSON version of tinanta forms list

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#1056]
I forget where I generated https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-vyAkaraNa/dhaval-tiNanta/dhaval-tiNanta.babylon from. I need a JSON version of that file: Just give me a JSON list like the example [here](http://www.jsoneditoronline.org/?id=1ad66e957255b457fcf4524389f66001) (<-- alas somehow this is corrupted as of Dec 15). This, if available, will be immediately useful for shrI sAi's sentence generator (we can switch from [uohyd API](https://api.vedavaapi.org/scala/swagger/index.html#/grammarv1analyser/Analyse1) then).

It would be specially good if you could use the same (hopefully standard and community maintained) JSON structure - defined in public [scala](https://github.com/sanskrit-coders/db-interface/blob/master/src/main/scala/dbSchema/grammar/Analysis.scala) and python packages - that way we wont have to translate one json to another. You can modify it to hold additional data.

**Comment by drdhaval2785** [comment]
JSON mode now available on CLI as well as frontend.
Out of the JSONs so generated, a new web service is being envisaged at https://github.com/drdhaval2785/prakriya

**Comment by vvasuki** [comment]
Good going!

कुत्र लभेय भोः json सञ्चिकाम्??

**Comment by drdhaval2785** [comment]
The size of data is prohibitive. So creating a web service. Flask test
version delivers as expected. Will learn deploying flask applications.
First time for me.

**Comment by vvasuki** [comment]
wait - actually a tsv file (with optional forms separated by a comma) would be even better since it can be imported to google sheets and smaller - can you produce that and send it to me or import into Google Sheets and share instead? Any human or program will be able to read it quite easily. 

See https://docs.google.com/spreadsheets/d/14UEZmuSvbbdxAnqpZdSvSH8hrp3flPhPoo01aSXhbDY/edit?usp=drive_web for an example.

**Comment by drdhaval2785** [comment]
I know we are on different lines.

There are two items, one in my mind, another in yours.

1. Your requirement - a babylon / json / tsv for verb forms of a given verb
e.g
BU,Bavati,BavataH,Bavanti.....

2. My requirement - a step by step derivation of a single verb form.
Genetation of Bavati from BU.

Both are near at hand.
Point 2 is done. 2.25 lac + forms with step by step derivation.
It would be great help to beginners of Paninian grammar.

**Comment by vvasuki** [comment]
I am interested in both as well! But was referring to 1 since this thread was about that. (we already have a babylon though)

The latter should be made available as a dict too.

**Comment by vvasuki** [comment]
Hey @drdhaval2785 , why's this closed? we don't have a tsv or json or google spreadhseet dump yet..

**Comment by vvasuki** [comment]
PS: I just recalled an old xml dump of the data at https://github.com/drdhaval2785/SanskritVerb/issues/937 , which may well suffice if it's up-to-date (and can be kept up-to-date by a readily available script). I can dig up or contribute anew a script to transform it to tsv or whatever else I need.

**Comment by drdhaval2785** [comment]
@vvasuki

Do you still need this file?

**Comment by vvasuki** [comment]
If you can keep dhaval-* in https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-vyAkaraNa up to date, that's more than enough - you'll be helping lots of people.
