### ISSUE TITLE
व्रज गतौ लुङि 

### ISSUE THREAD

**Issue by raghubhaijoshi** [drdhaval2785/SanskritVerb#1063]
व्रज गतौ लुङि  "वदव्रजहलन्तस्याच:" इति नित्यवृद्धि: भवति अत: अव्राजीत् इति रुपं भवेत् | पक्षे अव्रजीत् इति रुपं न भवति |

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0286 also does not handle this. This requires to be corrected.

**Comment by akprasad** [comment]
@drdhaval2785 This is [fixed](https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=01.0286) in the latest release.
