### ISSUE TITLE
The entire Dyutaadi-Gana should be aatmanepadi

### ISSUE THREAD

**Issue by neeleshb** [drdhaval2785/SanskritVerb#1064]
Verbs from द्युत् 1.842 upto कृप् 1.866 all belong to द्युतादि अन्तर्गण and all are आत्मनेपदी. only for लुङ्लकार, they become ubhaypadi due to द्युद्भ्यो लुङि. However, for some verbs in this set (e.g. शुभ् 1.851, लुठ् 1.853) the database the reverse. That is, all परस्मैपदी forms are shown with only लुङ् getting आत्मनेपदी forms. This needs to be fixed.

**Comment by neeleshb** [comment]
Specifically these four dhatus - 851, 852, 853, 864. Rest all seem correct.

**Comment by drdhaval2785** [comment]
Yes. Checking. There seem to be two entries each in bhvAdi for these items. Numbering seems to have gone haywire.

**Comment by drdhaval2785** [comment]
Require to be checked. Not checked yet.

**Comment by akprasad** [comment]
This seems implemented in Vidyut, see e.g. https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=01.0842 and verbs following it.
