### ISSUE TITLE
Adding svara-prakaraNa to panini.php

### ISSUE THREAD

**Issue by sathynius2** [drdhaval2785/SanskritVerb#1068]
Following my email regarding the SanskritAccent project, would it be a good idea to start by extending panini.php with 6.1.158 (anudAttaM padam-ekavarjam) etc, so that the tiGanta and subanta generators can produce forms with the accent indicated? Would that be directly usable with the Accents project where an input word needs to be analysed rather than a new word constructed from roots/stems?

**Comment by drdhaval2785** [comment]
Svaras will not be handled here. Will be handled in SanskritAccent whenever I can take it up.
