### ISSUE TITLE
ऋद्ध्यति

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#1074]
तव कोशे "ऋध्नोति" इत्येव रूपम् दृश्यते। किञ्च, कृदन्तरूपमालायाम् - "1 {@“ऋधु वृद्धौ”@} 2 ‘ऋध्नोतीति भवेद् वृद्धावृध्यतीत्यत्र तु श्यनि।’ 3 इति देवः।" इत्युक्तचरम्। आख्यातचन्द्रिकायाम् अपि तद् रूपं दृश्यते।

**Comment by drdhaval2785** [comment]
This verb is enumerated in both svAdi and divAdi gana. Both are enlisted in the system. If you select svAdi, you get fDnoti. If you select divAdi, you get fDyati

**Comment by vvasuki** [comment]
Oh! https://github.com/sanskrit-coders/stardict-sanskrit/issues/93 इति सूत्रान्तरम् प्रारब्धम्।
