### ISSUE TITLE
लिख णिच् लोट् कर्मणि, लेख्यताम्  

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1075]
ण्यल्लोपावियङ्यण्गुणवृद्धिदीर्घेभ्यः पूर्वविप्रतिषेधेनेति वार्तिकम् 
अतः अकृत्सार्वधातुकयोः इति सूत्रं बाधित्वा पूर्वविप्रतिषेधेन णेरनिटि प्रवर्तते।

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=06.0092 handles this well.
