### ISSUE TITLE
ह्वेञ्, यङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1076]
जोहूयते भवेत्, अभ्यस्तस्य च इति सम्प्रसारणम्

**Comment by drdhaval2785** [comment]
Noted.

**Comment by drdhaval2785** [comment]
@akprasad, pending to be handled at vidyut-prakriya also.
It gives wrong forms like [जोहुय्यते](https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1163#)

**Comment by akprasad** [comment]
@drdhaval2785 This is [fixed](https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=01.1163&sanadi=4&activePada=%7B%22text%22%3A%22johUyate%22%2C%22type%22%3A%22tinanta%22%2C%22args%22%3A%7B%22dhatu%22%3A%7B%22code%22%3A%2201.1163%22%2C%22upadesha%22%3A%22hve%5C%5CY%22%2C%22upadeshaQuery%22%3A%22hveY%22%2C%22artha%22%3A%22sparDAyAM+Sabde+ca%22%7D%2C%22lakara%22%3A%220%22%2C%22prayoga%22%3A0%2C%22purusha%22%3A%220%22%2C%22vacana%22%3A%220%22%2C%22pada%22%3A%220%22%2C%22sanadi%22%3A%224%22%2C%22upasarga%22%3Anull%7D%7D#) in the latest build.
