### ISSUE TITLE
अधुना+इयम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#1077]
ङमुडागमं दर्शयति, पदान्ते ङमुटः अभावात् न स्यात् तदागमः
By AdguNaH (6.1.87) :
आद्गुणः (६.१.८७) :
1 - अधुन्+एयम्
pada
By Gamo hrasvAdaci GamuNnityam (8.3.32) :
ङमो ह्रस्वादचि ङमुण्नित्यम्‌ (८.३.३२) :
1 - अधुन्न्+एयम्
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अधुन्नेयम्
2 - अधुन्न्नेयम्
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अधुन्नेयम्
2 - अधुन्न्नेयम्
3 - अधुन्नेयम्म्
4 - अधुन्न्नेयम्म्
N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.
त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।
By halo yamAM yami lopaH (8.4.64) :
हलो यमां यमि लोपः (८.४.६४) :
1 - अधुन्नेयम्
2 - अधुन्न्नेयम्
3 - अधुन्नेयम्म्
4 - अधुन्न्नेयम्म्
Final forms are :
आखिरी रूप हैं :
1 - अधुन्नेयम्
2 - अधुन्न्नेयम्
3 - अधुन्नेयम्म्
4 - अधुन्न्नेयम्म्

**Comment by drdhaval2785** [comment]
Not providing support to sandhi / subanta now.
