### ISSUE TITLE
Potential error in prakriya for गडिँ

### ISSUE THREAD

**Issue by aniruddha753** [drdhaval2785/SanskritVerb#1078]
I tried getting karmaNi lat forms for गडिँ using [this](https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=%E0%A4%97%E0%A4%A1%E0%A4%BF%E0%A4%81&upasarga=&lakAra=law&sanAdi=&tran=Devanagari&vAcya=karma&frontend=1&jsonmode=0&number=01.0068&removed_sutras=&step=12&type=tiGanta) link.

It looks like after a numaagama due to the ikaara it (sutra 7.1.58), we get 'gand', but then while adding 'yak', the nakaara goes away due to sutra 6.4.24. After a few steps, sutra 7.1.58 is again used and the nakaara comes back. I'm not sure if this is right. Can anyone please confirm?

**Comment by mrudani** [comment]
सत्यम्! सः दोषः एव, वस्तुतः तत्र नलोपः न भवेत् तयोः इदित्त्वात्, अनिदितः
नस्यैव लोपः तेन उक्तत्वाच्च।

**Comment by mrudani** [comment]
एवम्

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0068 handles this well.
