### ISSUE TITLE
टुयाचृँ - णिजन्त - लुङ्‌ लकार

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#108]
Wrong declention because of akRtsArvadhAtukayordIrghaH.
Can this rule apply here?

```
1 - य+याच्+इ+अत्
By NeraniTi (6.4.51) :
णेरनिटि (६.१.५१) :
1 - य+याच्+अत्
akRtsArvadhAtukayordIrghaH (7.4.25) :
अकृत्सार्वधातुकयोर्दीर्घः (७.४.२५) :
1 - या+याच्+अत्
```

**Comment by mrudani** [comment]
नैव तत्सूत्रस्य प्रवृत्तिः अजन्ताङ्गेषु भवति. य इत्यत्र अजन्तत्वेऽपि अङ्गसंज्ञाभावाननास्य प्रवृत्तिः.

**Comment by mrudani** [comment]
क्ङिति परकत्वाभावाच्च नात्र दीर्घप्राप्तिः.
