### ISSUE TITLE
Error in churaadi-bhaave prakriyaa for वृतुँ

### ISSUE THREAD

**Issue by sowmyakrishnapur** [drdhaval2785/SanskritVerb#1081]
I was trying the tool for getting bhaave prakriyaa for वृतुँ भाषायाम् (चुरादिः) । It gives the form वर्तीयिते । Looks like सत्यापपाश... is being applied twice. 

https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=%E0%A4%B5%E0%A5%83%E0%A4%A4%E0%A5%81%E0%A4%81&upasarga=&lakAra=law&sanAdi=&tran=Devanagari&vAcya=bhAva&frontend=1&jsonmode=0&number=10.0312&removed_sutras=&step=13&type=tiGanta

**Comment by drdhaval2785** [comment]
Thank you for the report. Bhave is yet on experimental basis. Will keep this in mind when I try to correct Bhave prayoga fully.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=10.0312 handles this.
