### ISSUE TITLE
शक्नवानि इत्यत्र धातुसञ्ज्ञासूत्रे दोषः

### ISSUE THREAD

**Issue by vidushibolla** [drdhaval2785/SanskritVerb#1083]
लोड्लकारस्य उत्तरमपुरुषस्य एकवचने शक्नवानि इत्यस्य प्रक्रियायां शक् [ सनाद्यन्ता धातवः३.१.३२ ] इति विलिख्य आगच्छति, किन्तु अत्र भूवादयो धातवः इत्यनेनैव धातुसञ्ज्ञा, सनादिप्रत्ययान्तत्वाभावत्। प्रायः दोषोऽयं अन्यलकाराणाम् उत्तमपुरुषस्य एकवचने दरीदृश्यते।

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=05.0017 handles this.
