### ISSUE TITLE
चुरँ स्तेये। कर्मणि लडादिषु लकारेषु रूपाणि।

### ISSUE THREAD

**Issue by vedarthananda** [drdhaval2785/SanskritVerb#1084]
चोर्यते इत्यादिरूपाणि न प्राप्यन्ते।
The forms shown are, when णिच् is selected: चोराय्यते etc.
When णिच् is not selected: चोरीयिते etc.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=10.0001 handles this well.
![Screenshot_2023-04-16_21-39-12](https://user-images.githubusercontent.com/5755132/232325707-a289d371-240c-4821-b71d-b85c40ecd7ee.png)
