### ISSUE TITLE
जिज्ञासा

### ISSUE THREAD

**Issue by KALIDASTHAKER** [drdhaval2785/SanskritVerb#1085]
![संसाधनी](https://user-images.githubusercontent.com/76493549/102922307-d9de6e80-44b3-11eb-8dd1-6500945246c8.jpg)
![संसाधनी_जिज्ञासा](https://user-images.githubusercontent.com/76493549/102922309-db0f9b80-44b3-11eb-8f1a-189cce72033d.jpg)
![संसाधनी_जिज्ञासा-१](https://user-images.githubusercontent.com/76493549/102922310-dba83200-44b3-11eb-8ec0-60cef30af532.jpg)

**Comment by drdhaval2785** [comment]
Any issue in the form? I think you do not need to provide adhi. As the verb is always preceded by adhi.
