### ISSUE TITLE
महान्तः

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#1086]
महत् + जस् should be महान्तः, but gives महत

**Comment by GssMahadevan** [comment]
same issue applies to विद्वस् . Here also  विद्वस् + जस् -->  विद्वसः

**Comment by drdhaval2785** [comment]
Closing, as I am not developing subanta any longer.
In fact, tiGanta generator is also retiring in favour of https://ambuda-org.github.io/vidyullekha/
