### ISSUE TITLE
daDati

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#1087]
Bug report by Mr. Nityānanda Miśra.

मित्रे 

इदं पृष्ठं चित्रं च पश्यतम्

[https://ashtadhyayi.com/dhatu/03.0011?type=ting&form=दधति](https://ashtadhyayi.com/dhatu/03.0011?type=ting&form=%E0%A4%A6%E0%A4%A7%E0%A4%A4%E0%A4%BF)

→ दधा+अन्ति [ झोऽन्तः७.१.३ ]
→ दधा+अन्ति [ उभे अभ्यस्तम्६.१.५ ]
→ दधा+अति [ अदभ्यस्तात्‌७.१.४ ] 

As 7.1.4 is an exception to 7.1.3, rule 7.1.3 will not be applicable in this prakriya. Instead of अन्ति being replaced by अति, झ् of झि will be directly substituted by अत्

**Comment by akprasad** [comment]
This is handled by vidyut-prakriya.
