### ISSUE TITLE
अतत लुङ्‌ लकार - अनुदात्तोपदेशवनतितनोत्यादीनामनुनासिकलोपो झलि क्ङिति

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#112]
sahajabodha and all other books say that 'n' of tanAdi is elided before त.
अतन्‌+स्त -> अतन्‌ + त -> अतत.

But the machine didnt apply this rule.
When I examined the issue was that the machine was checking for क / ङ as इत्‌. As it couldn't find these as it markers, it didn't apply this rule.

Question - How is it that त has क्ङिति quality?

**Comment by mrudani** [comment]
सार्वधातुकमपित् इति निर्देशात् त इति प् इत्संज्ञारहितः सार्वधातुकप्रत्ययः ङित्-वत् भवति तेन अत्र ङित्कार्याणि भवन्ति.

**Comment by drdhaval2785** [comment]
Doesn't Sahajabodha count LuG lakAra as ArdhadhAtuka suffix?

**Comment by mrudani** [comment]
यत्र धातोः तिङः च मध्ये शिद्भिन्नः कश्चन प्रत्ययः भवति तर्हि सः आर्धधातुकः भवति। तस्मिन्नेव भावे सामान्यतया तत्र लुङः आर्धधातुकत्वेन परिगणितः। लुङ् लकारे सामान्यतया शिद्भिन्न च्लि इति प्रत्ययः धातोः तिङः च मध्ये भवति, अतः सः आर्धधातुक इति परगणितः।

**Comment by mrudani** [comment]
अत्र प्रश्नः समाहितः ननु।
