### ISSUE TITLE
उद्विजिष्ट / उदविजिष्ट - उत्‌+ओँविजीँ लुङ्‌ लकार तिप्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#113]
machine gives उदविजिष्ट i.e. उत्‌+अविजिष्ट
sahajabodha gives उद्विजिष्ट
What is correct?

**Comment by mrudani** [comment]
उदविजिष्ट इत्येव प्रयोगः
