### ISSUE TITLE
लुङ्‌ लकार

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#114]
@mrudani 

I am finding it exceedingly difficult to digest the लुङ्‌ लकार section of sahajabodha.
The 10-12 types pratyaya classification of sahajabodha doesn't seem workable to me in this lakAra.

What I would want you to do is - write an algorithm of this tense.

Step 1. Classify which verbs take these different pratyayas like सिच्‌, सिज्लुक्‌, चङ्‌, अङ्‌ etc.
Step 2. sahajabodha is not clear on why there is no iDAgama in sicluk, caG etc. Clarify that point.
Step 3 - Clarify the duplication process in caG. It is a bit confusing to me.
Step 4 - Describe how the pratyayas in sahajabodha (readymade) are derived from simple 'tiG' pratyayas.

**Comment by drdhaval2785** [comment]
```
Step 1. Classify which verbs take these different pratyayas like सिच्‌, सिज्लुक्‌, चङ्‌, अङ्‌ etc.
```

@mrudani 's reply is as below

१. सिच्लुक् गा, स्था, घुसंज्ञकधातवः, पा, भू एतेषां भवति
२. सक् आगमः आकारान्तधातूनां भवति गा, स्था, घुसंज्ञकधातवः, पा इति धातून् च विहाय भवति.
३. अङ्
असु, वच्, ख्या.
लिप्, सिच्, ह्वे एतेषां धातूनां परस्मैपदे नित्यम् अङ्, आत्मनेपदे विकल्पेन अङ् भवतीति.
पुषादिगणे विद्यमानानां धातूनां परस्मैपदे अङ्
द्युतादिगणे विद्यमानानां धातूनां परस्मैपदे अङ्
ऌदितां धातूनां परस्मैपदे अङ्
सृ, शास्, ऋ धातूनां परस्मैपदे अङ्
इरित् धातूनां विकल्पेन अङ् परस्मैपदे
जॄ, स्तम्भु, म्रुचु, म्लुचु, ग्रचु, ग्लुचु, ग्लुञ्चु, श्वि विकल्पेन अङ्
कृ, मृ, दृ, रुह् धातूनां छन्दसि अङ्
४. चङ्
णिजन्तधातूनां कर्तरि चङ
श्रि, द्रु, स्रु एतेषां कर्तरि चङ्
धेट्, श्वि विकल्पेन चङ्
गुप् धातोः विकल्पेन छन्दसि चङ्
ऊन, ध्वन, इल, अर्द एषां णिजन्तानां छन्दसि चङ्
५. क्स
शल्प्रत्याहारान्ताः, इगुपधः, अनिटश्च धातवः ये, तेषां क्स, दृश् धातोः न भवति.
श्लिष् धातोः क्स आलिङ्गनार्थे
६. अन्येषां धातूनां सिच् भवति.
७. सेट्धातूनां इट्+ सिच् भवति.
धातूनां परिगणनं कृत्वा प्रेषयिष्यामि.

**Comment by mrudani** [comment]
2. सिज्लुक् केवलं परस्मैपदेष्वेव भवति. अतः धातोः अनन्तरं विद्यमानस्य सिचः
लोपे सार्वधातुकपरत्वं भवति धातोः, अतः तत्र इडागम एव न भवति.
चङ्, अङ् इत्यत्र तु वलादित्वं न भवति अनपबन्धलोपेत्तरम्.
क्स इति आदेशस्तु अनिटामेव भवति. अतः तत्र इडागमस्य विचार एव न भवति.

**Comment by mrudani** [comment]
अस्मिन् धातूनां परिगणना कृता।

2015-02-12 16:03 GMT+05:30 Sivakumari Katuri <shivakumari.katuri@gmail.com>:

> 2. सिज्लुक् केवलं परस्मैपदेष्वेव भवति. अतः धातोः अनन्तरं विद्यमानस्य सिचः
> लोपे सार्वधातुकपरत्वं भवति धातोः, अतः तत्र इडागम एव न भवति.
> चङ्, अङ् इत्यत्र तु वलादित्वं न भवति अनपबन्धलोपेत्तरम्.
> क्स इति आदेशस्तु अनिटामेव भवति. अतः तत्र इडागमस्य विचार एव न भवति.
> On 12 Feb 2015 10:35, "Dr. Dhaval Patel" <notifications@github.com> wrote:
>
>> Step 1. Classify which verbs take these different pratyayas like सिच्‌, सिज्लुक्‌, चङ्‌, अङ्‌ etc.
>>
>> @mrudani <https://github.com/mrudani> 's reply is as below
>>
>> १. सिच्लुक् गा, स्था, घुसंज्ञकधातवः, पा, भू एतेषां भवति
>> २. सक् आगमः आकारान्तधातूनां भवति गा, स्था, घुसंज्ञकधातवः, पा इति धातून् च
>> विहाय भवति.
>> ३. अङ्
>> असु, वच्, ख्या.
>> लिप्, सिच्, ह्वे एतेषां धातूनां परस्मैपदे नित्यम् अङ्, आत्मनेपदे विकल्पेन
>> अङ् भवतीति.
>> पुषादिगणे विद्यमानानां धातूनां परस्मैपदे अङ्
>> द्युतादिगणे विद्यमानानां धातूनां परस्मैपदे अङ्
>> ऌदितां धातूनां परस्मैपदे अङ्
>> सृ, शास्, ऋ धातूनां परस्मैपदे अङ्
>> इरित् धातूनां विकल्पेन अङ् परस्मैपदे
>> जॄ, स्तम्भु, म्रुचु, म्लुचु, ग्रचु, ग्लुचु, ग्लुञ्चु, श्वि विकल्पेन अङ्
>> कृ, मृ, दृ, रुह् धातूनां छन्दसि अङ्
>> ४. चङ्
>> णिजन्तधातूनां कर्तरि चङ
>> श्रि, द्रु, स्रु एतेषां कर्तरि चङ्
>> धेट्, श्वि विकल्पेन चङ्
>> गुप् धातोः विकल्पेन छन्दसि चङ्
>> ऊन, ध्वन, इल, अर्द एषां णिजन्तानां छन्दसि चङ्
>> ५. क्स
>> शल्प्रत्याहारान्ताः, इगुपधः, अनिटश्च धातवः ये, तेषां क्स, दृश् धातोः न
>> भवति.
>> श्लिष् धातोः क्स आलिङ्गनार्थे
>> ६. अन्येषां धातूनां सिच् भवति.
>> ७. सेट्धातूनां इट्+ सिच् भवति.
>> धातूनां परिगणनं कृत्वा प्रेषयिष्यामि.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/drdhaval2785/SanskritVerb/issues/114#issuecomment-74018339>
>> .
>>
>


-- 
*सर्वे भद्राणि पश्यन्तु।*
