### ISSUE TITLE
vadavraja v/s pugantalaghUpadhasya ca

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#118]
भिदिँर्‌ लुङ्‌ लकार तिप्‌
Right now पुगन्तलघूपधस्य applies and then वदव्रज.. applies.
Actually there is no space for pugantalaghUpadhasya ca to apply.

I am thinking of shifting the pugantalaghUpadhasya ca statements and sArvadhAtukArdhadhAtukayoH statements after iDAgama.

It is too drastic a step from coding point of view.
Therefore, not doing it right now.
Will do at a later step once the code is stable.
Otherwise for display purpose, I can create a patch right now.

```
1 - भिद्+सीत्

pugantalaghUpadhasya ca (7.3.86) :

पुगन्तलघूपधस्य च (७.३.८६) 2:

1 - भेद्+सीत्

By luGlaGlRGkSvaDudAttaH (6.4.71) :

लुङ्लङ्लृङ्क्ष्वडुदात्तः (६.४.७१) :

1 - अभेद्+सीत्

By vadavrajahalantasya acaH (7.2.3) :

वदव्रजहलन्ताच्च अचः (७.२.३) 2:

1 - अभैद्+सीत्
```

**Comment by mrudani** [comment]
लघूपधगुणस्यापवादः एषः वदव्जहलन्तस्याचः इति वृद्धिविधिः
