### ISSUE TITLE
तृप्‌ दिवादि - सेट्‌ / वेट्‌ ?

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#119]
sahajabodha part 2 page 267 says they are वेट्‌.
Whereas my database as well as http://sanskrit.uohyd.ernet.in/scl/dhaatupaatha/compare_with_svara.html says that it is अनिट्‍.

What is correct?

**Comment by mrudani** [comment]
रधादित्वादस्य रधादिभ्यश्चेति विकल्पेन इट्.

**Comment by drdhaval2785** [comment]
This issue is generic. Mihail's database has no 'veT' entry.
Will have to redo it.
