### ISSUE TITLE
अवात्ताम्‌ - वस्‌ निवासे अनिट्‌ लुङ्‌ तस्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#120]
@mrudani 

The word अवात्ताम्‌ is derived on page 271 of part 2 of sahajabodha as follows:

![capture](https://cloud.githubusercontent.com/assets/5755132/6184410/4587ff8a-b387-11e4-8f13-b842fc29857a.PNG)

The issue is that after झलो झलि, there is no सकार after सकार.
अवास्‌+स्ताम्‌ -> अवास्‌+ताम्‌. 
Therefore, there is no possibility of application of सः स्यार्धधातुके.
Also, सः स्यार्धधातुके is asiddha to झलो झलि. 
So, I think the derivation in sahajabodha is wrong.

Machine derivation is as follows -
```
1 - अवस्+स्ताम्
वदव्रजहलन्ताच्च अचः (७.२.३) 2:
1 - अवास्+स्ताम्
सः स्यार्धधातुके (७.४.४९) :
1 - अवात्+स्ताम्
झलो झलि (८.२.२६) :
1 - अवात्+ताम्
```

See that the rules are in order of saH syArdhadhAtuke and then jhalo jhali.

**Comment by mrudani** [comment]
सत्यमुक्तम्, अत्र आदौ सः स्यार्धधातुके इत्यस्यैव प्रवृत्तिः, सस्य तागेशः सपरे विधानात् सलोपे सति सपरकत्वाभावात् तस्य प्रवृत्तिरेव न स्यात्
