### ISSUE TITLE
Display suggestions as one types in the dhAtu.

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#122]
[कृ](http://www.lanover.com/lan/sanskrit/SanskritVerb/tiGanta.php?first=%E0%A4%95%E0%A5%83&upasarga=&lakAra=law&vAcya=kartR&tran=Devanagari&sanAdi=&cond11=2&step=11) shows bad forms such as करति  .

अतः धातवस् सूचनीया यन्त्रेणैव उट्टङ्कनसमये। यथा "डुकृञ्"।

**Comment by drdhaval2785** [comment]
Very vital suggestion.
1. If it matches some verb, let us show it.
2. If it doesn't match the pre-fed verb list e.g. nAmadhAtu / Nijanta etc, let the user continue with the verb he is entering.

For this purpose, I will need help from someone who is good at browser side languages. I am really bad at it. If you can help me with some javascript or jquery kind of thing for this purpose, I would be really grateful.

**Comment by vvasuki** [comment]
सरलमिदम् - परीक्षताम् - http://jqueryui.com/autocomplete/

**Comment by drdhaval2785** [comment]
Corrected via 5f3c7dc5e39a0357d0957ab1cba088637855a6ce
