### ISSUE TITLE
डुकृञ् करणे - लटि दोषाः

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#123]
[डुकृञ्](http://www.lanover.com/lan/sanskrit/SanskritVerb/tiGanta.php?first=%E0%A4%95%E0%A5%83&upasarga=&lakAra=law&vAcya=kartR&tran=Devanagari&sanAdi=&cond11=2&step=11) इति धातोर् अनिष्टरूपाणि जन्यन्ते। यथा - कृञोति इति। इतां निष्कासनं कार्यम्।

**Comment by drdhaval2785** [comment]
Corrected in localhost. Will upload to server soon.

**Comment by drdhaval2785** [comment]
By halantyam (1.3.3) :

हलन्त्यम्‌ (१.३.३) 1:

1 - कृञ्+उ+तिप्

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कृ+उ+ति

sArvadhAtukArdhadhAtukayoH (7.3.84) 4:

सार्वधातुकार्धधातुकयोः (७.३.८४) :

1 - कर्+उ+ति

sArvadhAtukArdhadhAtukayoH (7.3.84) 3:

सार्वधातुकार्धधातुकयोः (७.३.८४) :

1 - कर्+ओ+ति

Final forms are :

आखिरी रूप हैं :

1 - करोति

**Comment by drdhaval2785** [comment]
Corrected on live server
