### ISSUE TITLE
Separate the UI from the grammatical logic.

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#125]
The current setup mixes UI with the core grammar logic. This has the following disadvantages:
- We cannot use the code as it currently stands to generate conjugations outside the context of the current web-page.
  - (We would want to do this, for example, to generate conjugations for use in dictionaries or parsers or other applications.)
- It is cumbersome to refine the UI, and make it do cool things which don't rely on grammar logic.

Separation of concerns/ modularity is an important principle in writing easily-maintainable, reusable software. In this praticular case, at the minimum, a pattern such as http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter could be adapted.

A first step at doing this: Separate out the grammar logic to functions. More functions = more modularity, more reusability, easier understanding.

**Comment by vvasuki** [comment]
Your [slp-dev](https://github.com/drdhaval2785/SanskritVerb/blob/master/slp-dev.php) function is a good example of modularizing the code.

**Comment by vvasuki** [comment]
I can think of the following functions:
GetConjugations, determineParasmaiAtmaneUbhayaPada, getParasmaipadaConjugations, getAtmanepadaConjugations, addVikarana, addTip .....

**Comment by drdhaval2785** [comment]
I agree with the need to modularize the code.
And some of the things are easily doable.
You may have a look at the function.php file.
There I have modularized the code for Paninian processes.

It will take some time to modularize the thing, but yes it it doable and easily doable. Only issue is that it is cumbersome.

**Comment by vvasuki** [comment]
Conversely, the core pANiniya logic should not contain any UI business (such as [here](https://github.com/drdhaval2785/SanskritVerb/blob/master/function.php#L1430)). Functions such as anubandha() could return the modified text, with a sequence of sutra-references - the UI should take care of displaying (ie adding <p class = pa > etc.. )

**Comment by funderburkjim** [comment]
I am in infrequent participant in this project, and definitely do not understand the underlying grammatical principles as do the more active participants.

However, several months ago I did look at the code as it was then and *heartily agree with the comments made under this issue*.   A multi-thousand line program in php (or any programming language) is basically
impossible to understand, and, more importantly, impossible to modify or improve or make use of in
other contexts.

In addition to the principle of modularization by means of separating related functions in different .php files,
also modularization by means of object oriented programming tecniques (available in php) should 
be considered.  

@drdhaval2785  Let me know if you'd want me to work with you in some of this program refactoring work.

**Comment by drdhaval2785** [comment]
I would love if you can help me with refractoring the code

**Comment by drdhaval2785** [comment]
```
Conversely, the core pANiniya logic should not contain any UI business
```
I agree and get the point what you want to say.
I will think in that direction and weed out the UI business from such functions.

**Comment by drdhaval2785** [comment]
A baby step in this direction started with function gui($sutra_number) in function.php committed via 1bb39d6bdcc0aab5a5a67c5e24b4688a46f329a8.
This function can mimic the display which is right now shown inline.
It draws necessary information from $ASdata which has data in array form whose individual members are in AS_sutra_number:AS_sutra_devanagari:AS_sutra_type format. (The data is scraped from https://docs.google.com/spreadsheet/ccc?key=0Aocnp1cX4xG8dGh5Q0JaX21WYTZ0MktsRVQ3NzVON0E of Sai Susarla.

**Comment by gasyoun** [comment]
@vvasuki Dhaval will get there, I know this is one of the top priorities in this list. It's like when CSS was invented the fonts tag in HTML died. Same step has to be done here. The question is - as from a reuser perspective what kind of functions could come handy? I badly need impossible sandhi combinations generator :rabbit2:

**Comment by funderburkjim** [comment]
Peter Scharf  wrote a Pascal sandhi-combination program  many years ago, and 4 or 5 years ago I converted it to a Java program.  Several months ago he agreed that I could put this in a Github repository.   I have also 
written an 'inverse sandhi' program in Emacs Lisp about 10 years ago.   I don't know whether these have any
current use in this thread or elsewhere, but it seemed relevant to mention it in this thread.

**Comment by vvasuki** [comment]
2015-04-23 17:42 GMT-07:00 funderburkjim <notifications@github.com>:

> I could put this in a Github repository. I have also
> written an 'inverse sandhi' program in Emacs Lisp about 10 years ago.
>

​Are these on github? At the minimum, they ​would be useful references.



-- 
--
Vishvas /विश्वासः

**Comment by drdhaval2785** [comment]
The PHP function (named gui in function.php) to separate the UI from code
is ready. I am testing it whether i take care of storing all the parameters
to show it later with GUI function. After that i will apply it to whole of
the code.

**Comment by drdhaval2785** [comment]
Putting the codes of Jim on Github would be good starting point.

**Comment by funderburkjim** [comment]
Implementations of Scharf's Sandhi program are now in the [ScharfSandhi](https://github.com/funderburkjim/ScharfSandhi) repository.

**Comment by drdhaval2785** [comment]
[tiGanta.php](https://github.com/drdhaval2785/SanskritVerb/blob/master/tiGanta.php) has been refractored as of now.

Now the typical code line would look something like this
```
/* ato bhisa ais (7.1.9) */
if (arr($text,'/[a][+]/') && $so === "Bis" && $nedamadas===0 && $fo!=="adas" )
{
    $text = two(array("a"),array("Bis"),array("a"),array("Es"),0);
	storedata('7.1.9','sa',5);
    $atobhis = 1; // 0 - this sUtra has not applied. 1 - this sUtra has applied.
}
```

Explanation
The first line in between `/* */` is the sUtra / vArtika under consideration.
Second line `if (arr($text,'/[a][+]/') && $so === "Bis" && $nedamadas===0 && $fo!=="adas" )
` is the condition section, where we check that particular conditions are satisfied before triggerring the rule.
Third line `$text = two(array("a"),array("Bis"),array("a"),array("Es"),0);` is where we alter the string based on the rule.
Fourth line `storedata('7.1.9','sa',5);` is where we store the data needed for GUI at later stage i.e. sUtra number, sUtra type, any specific display message.
Fifth line `$atobhis = 1;` is some variable change we want to remember for future reference.

The GUI business is separated from code and stored as `display_from_storedata();`.
This will parse all the storedata variables and display on the frontend.

TODO:
1. Some GUI business from function.php still needs to be refractored.
2. There were some cases where more than one sUtras played a part to give final product. In the current scheme of things, only one sUtra is stored. Will need to think about handling multiple sUtras.
3. Special messages which are not sUtra / vArtika are not refractored as of yet. e.g. explanation / paribhASA / gaNasUtras / uNAdisUtras etc

**Comment by drdhaval2785** [comment]
```
TODO:
1. Some GUI business from function.php still needs to be refractored.
2. There were some cases where more than one sUtras played a part to give final product. In the current scheme of things, only one sUtra is stored. Will need to think about handling multiple sUtras.
3. Special messages which are not sUtra / vArtika are not refractored as of yet. e.g. explanation / paribhASA / gaNasUtras / uNAdisUtras etc
```
Done now.
