### ISSUE TITLE
sub function and efficiency

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/SanskritVerb#126]
I ran into efficiency issues in running tiGanta.

These runs use 'curl' so that the output can be captured for further examination.
First case, run via the 'lanover' server, took 1:35 (one minute, 35 seconds)  to run.
```
curl 'http://lanover.com/lan/sanskrit/SanskritVerb/tiGanta.php?first=BU&upasarga=&lakAra=law&vAcya=kartR&tran=SLP1&sanAdi=&cond11=2&number=01.0001&step=11' > lanover-ex1.html
```
Second case,  downloaded a zip of this repository, and ran on local server:
```
curl  'http://localhost:8000/tiGanta.php?first=BU&upasarga=&lakAra=law&vAcya=kartR&tran=SLP1&sanAdi=&cond11=2&number=01.0001&step=11' > localhost-ex1.html
```

In fact the full run never completed (I killed after 20+ minutes, when it was about half through).

Question 1:  Is the lanover version running the code from this repository?

Question 2: Any idea why so much slower (at least a factor of 10) on local server.

Question 3:  I put in various timing statements, and narrowed down the primary cause of slow 
execution to the 'sub' function when it is used with $allverbs.  This is in one spot, the 'if' condition after the
line `Nau prAtipadikasya iSThavatkAryaM bhavatIti vaktavyam (vA)` of tiGanta.php,
```
sub($allverbs,array("+Ric+Sap+","+RiN+Sap+"),$tiG,0);
and $tig = 18-length array tip,tas,Ji,sip,Tas,Ta,mip,vas,mas,ta,AtAm,Ja,TAs,ATAm,Dvam,iw,vahi,mahiN
and $text = BU+Sap+tip    (passed to sub as a global (Ugh!))
```
In this call to sub, the `$needles` array is > 300,000.   There likely is some way to greatly optimize
this usage of the 'sub' function, provided we could know something about the '$text' variable at this
point.  From this one example, it appears that $text will be an array, whose elements are of form `X+Y', 
where X  is the input root, which is in fact one  the elements of the $allverbs array. 
Is that statement about $text right?

Any other simplifying assumptions (such as structure of Y) that could be used to make this call
to sub more efficient?

**Comment by drdhaval2785** [comment]
Q1 yes
Q2 i have no idea why it is so slow in your localhost. But make sure to
check your browser bufferring. It may be preventing the dat from being
printed and storing in buffer. A single variable bufferring too much of
data may be the reason.
In my localhost it almost always gives lesser time than lanover server.
Q3 this is interesting catch. I guess i will restructure it to make it less
taxing. The vArtrika is also not that important. If it is very taxing in
time, it can always be commented out.

**Comment by funderburkjim** [comment]
Found that the slow speed has something to do with the server being used.
In the test mentioned above, I was using the built-in web server of php (php -S localhost:8000).
There is also another lamp stack (Server2go, with php version 5.3.2) on this computer, and the same
code was run with it.   In this case, it took 9:24 to run.  This is still much slower than the run on lanover,
but much faster than when using the built-in web php web-server.   So, the speed is sensitive to 
details about php.

Incidentally, this version of SanskritVerb was from Mar 29.   I also downloaded the version of today, Mar 30,
and noticed one material difference in the output compared to Mar 29 SanskritVerb version.
Namely, these lines from the Mar29  (referencing sutra 1.1.7) 
```
<p class = form>1 - भू+शप्+तस्</p>
<p class = sa >sArvadhAtukamapit (<a href="http://sanskritdocuments.org/learning_tools/ashtadhyayi/vyakhya/1/1.1.7.htm">1.1.7</a>) :</p>
<p class = sa >सार्वधातुकमपित्‌ (१.१.७) :</p>
```
and similar lines for the other endings in the other conjugations (27 instances in all of 1.1.7).
These 1.1.7 references are absent in the Mar30 version. 

This suggests to me that substantive details of the program are still being changed.
Should I wait a for a more stable version before diving into the refactoring?

**Comment by drdhaval2785** [comment]
Right now the program is in debugging mode. There are many issues which
crop up during testing. Testing fully with representative verbs may take
around 2 months. I will let you know when we are stable enough.

**Comment by funderburkjim** [comment]
OK.

**Comment by drdhaval2785** [comment]
Q3 resolved. Made it less taxing on time.
