### ISSUE TITLE
श्रुणोति wrong form

### ISSUE THREAD

**Issue by Krupalu** [drdhaval2785/SanskritVerb#127]
'Sru' - 'SravaNe' ; I tried this. This is supposed to be parasmaipadI. I expected 'SRuNoti' kind of ourput. It took it as AtmanepadI and gave 'Sravate'.

**Comment by drdhaval2785** [comment]
@Krupalu 
I verified. Your concern is genuine. The issue is not about taking it as 'AtmanepadI'. It takes it as 'parasmaipadi' but wrongly applies 'kartari zap' rule here.
Will correct and let you know soon

**Comment by drdhaval2785** [comment]
The znu pratyaya is not by svAdibhyaH znuH, but a separate sUtra 3.1.74.

This issue draws attention to the following important left out coding.
1. संयसश्च 3.1.72
2. श्रुवः शृ च । 3.1.74
3. स्तम्भुस्तुम्भुस्कम्भुस्कुम्भुस्कुञ्भ्यः श्नुश्च । - 3.1.82

**Comment by drdhaval2785** [comment]
Done
