### ISSUE TITLE
Optional forms of aja! not being formed

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#130]
See pages 74,75 of SK part 2.
Only vivayiTa is being formed. viveTa and AjiTa pending.

![4-11-2015 2-39-07 pm](https://cloud.githubusercontent.com/assets/5755132/7100888/b23d8fde-e058-11e4-9a29-168c109aa916.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/7100890/bfac778e-e058-11e4-9a60-870877fa6f78.png)

**Comment by drdhaval2785** [comment]
Because of inerent difficulty in telling vI as aniT and aja as seT, this is really difficult.
We treat the whole array.
One member is aniT and the other is seT.
Therefore, the regular forms also get disturbed.
So, keeping 'valAdAvArdhadhAtukasya vikalpa iSyate (vA)' commented out as of now.

**Comment by gasyoun** [comment]
How many are outcommented in total?
