### ISSUE TITLE
i dhAtu liT forms

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#131]
SK part 2 page 88

In our database, we have only iR and iN dhAtus.
Whereas this seems to be a separate dhAtu.

If this is iR, then how 'iNo yaN' will not apply?
If this is iN, then the parasmaipada forms are not possible.
Check it further.

![capture](https://cloud.githubusercontent.com/assets/5755132/7101572/b8d912a4-e07c-11e4-9ace-09fa8acc9716.png)

**Comment by mrudani** [comment]
इमौ न इण् अथवा इङ्, अपि तु इ, ई इति अनुबन्धरहितधातू।

**Comment by drdhaval2785** [comment]
Not in our database.
Closing it for now.
If someone needs to use these verbs, he will have to reopen the issue
