### ISSUE TITLE
व्यष्टोभिष्ट

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#132]
When deriving luG lakAra of zwuBu! stambhe,

1 - वि+अस्तोभ्+इस्त

At this stage, I am unable to understand how this gets converted to  व्यष्टोभिष्ट ?

The machine makes व्यस्तोभिष्ट.

**Comment by mrudani** [comment]
इण् कोः इति अधिकारे आदेश प्रत्ययोः इति सूत्रं वर्तते, अतः अत्र सस्य षः भवति। इण् प्रत्याहारे यकारोपि वर्तते।

**Comment by drdhaval2785** [comment]
But 'a' is not in 'iN' praryAhAra.  'vyas'.. what would be the effect of
intermediate akAra?

**Comment by mrudani** [comment]
उपसर्गात् सुनोतिसुवतिस्यतिस्तौतिस्तोभतिस्थासेनयसेधसिचसञ्जस्वञ्जाम् इति सीत्रेण
उपसर्गस्थान् निमित्तातुत्तरस्य सुनोति सुवति स्यति स्तौति स्तोभति स्था सेनय सेध सिच सञ्ज स्वञ्ज इत्येतेषां सकारस्य मूर्धन्यादेशो भवति।
अभ्यष्टोभत। पर्यष्टोभत इति उदाहरणानि। अत्र अकारे सत्वे अपि सकारस्य षकारः दृश्यते।

**Comment by drdhaval2785** [comment]
How? Because of aTkupvA. .. and upasargA. .. Both read together?

**Comment by mrudani** [comment]
प्राक्सितादड्व्यवायेपि इति सूत्रात् अड्व्यवायेपि इति अनुवर्तते। अतः अड्व्यवायेपि भवति।
