### ISSUE TITLE
Is project stable?

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/SanskritVerb#153]
@drdhaval2785  A couple of months ago, I mentioned an interest in working on helping refactor the code, and you indicated an interest in this.  But you mentioned that the code was perhaps not stable enough.  In the interim, I've seen your messages indicating much work on this project.

Is the code stable enough now for me to begin working with it? 

If so, I envision devoting considerable time initially to understanding what you are doing, and this will require me to ask you many questions  (this is a warning!).

Let me know if this collaboration still sounds like a good idea to you, and if now is a good time to begin.

**Comment by drdhaval2785** [comment]
Project is still not stable.
It is in rough development.

**Comment by drdhaval2785** [comment]
#135 is almost 85% over. I see a near future for code stability, maybe around a fortnight and code should be stable and speedy enough.
Then we will discuss the issues related to coding aspect of it and how we can make it more efficient.
I apologize for inordinately long delay in making this project stable.

**Comment by drdhaval2785** [comment]
@funderburkjim The code is stable now.
If you want to auto generate verb forms via commandline, use wrongformfinder.sh shell script.
It will create generatedforms.xml and a suspectforms/latest.txt (a store of suspect forms found in our declention but absent in Amba / Gerard) file.
The code may change fast.
So advise you to sync anytime you run the code.
