### ISSUE TITLE
गुहूँ संवरणे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#154]
गु॑हूँ॒॑ - संवरणे, भ्वादि ०१.१०४३
By svaritañitaḥ kartrabhiprāye kriyāphale (1.3.72) :
स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२)
एषः स्वरितेत्त्वात् उभयपदि, परन्तु इत्संज्ञकस्य अनुदात्तत्वं चिह्नितम्।

**Comment by drdhaval2785** [comment]
The database I use has used 'a line above' and 'a line below' to denote the svaritattva.
Therefore it shows like this.
