### ISSUE TITLE
गाङ् गतौ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#155]
गा॒ङ् - गतौ, भ्वादि ०१.११०१
अदादिधातुरेषः।

**Comment by mrudani** [comment]
लट् प्रत्यये अकारटकारयोः इत्संज्ञा करणीया, ततः लशक्वतद्धिते इति लस्य इत्यंज्ञायां प्राप्तायां लस्य इति लस्थाने आदेशानामुपदेशात् न त्य इत्संज्ञा, ततः आत्मनेपदत्वात् प्रथमपुरुषैकवचनविवक्षायां लस्य त आदेशः इति सोपानक्रमेण प्रक्रिया।
लट् लकार
गाङ् + त Go Back
By tiṅśitsārvadhātukam (3.4.113) :
तिङ्शित्सार्वधातुकम् (३.४.११३) :
1 - गाङ्+त

**Comment by drdhaval2785** [comment]
भ्वादिधातुरेषः
![capture](https://cloud.githubusercontent.com/assets/5755132/13734794/dbf52796-e9c7-11e5-9695-57fc20903721.png)

And the step by step application is now done.
