### ISSUE TITLE
श्रु श्रवणे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#156]
शृ नु ति इत्यवस्थायां नु इत्यस्य गुणः भवति। तद्वदेव शृ इत्यस्यापि भवेत् तदा क्ङिति च इति गुणनिषेधः वक्तव्यः।Final forms are :
आखिरी रूप हैं :
1 - शृणोति
अत्र णत्वं केन भवतीति वक्तव्यम्।

**Comment by drdhaval2785** [comment]
It is there. RvarVAnnasya NatvaM vAcyaH is taught. But I am unable to locate its vArtika number in the database. Therefore, it is not showing.
If you can locate the vArtika number, it wouldbe great

**Comment by drdhaval2785** [comment]
8.4.1-1 is the vArtika number.
taught it.
So, the Natva issue is over.

I would not be able to show niSedhaH easily. That would stay. It is difficult to show non application of rules.
