### ISSUE TITLE
श्रु झि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#158]
By huśnuvoḥ sārvadhātuke (6.4.87) :
हुश्नुवोः सार्वधातुके (६.४.८७) :
1 - शृ+न्व्+अन्ति
By gkṅiti ca (1.1.5) :
ग्क्ङिति च (१.१.५) :
1 - शृ+न्व्+अन्ति

आदौ गुणनिषेधः, ततः इको यणचि इति यण् प्राप्तिः, तदपवादतया अचि श्नुधातुभ्रुवाम् इत्यादि सूत्रेण उवङ् आदेशे प्राप्ते तं प्रबाध्य हुश्नुवोरिति यणादेशः। एवं प्रक्रिया दर्शनीया।

**Comment by drdhaval2785** [comment]
Not possible to show the niSedhaH as of now. It is more than what machine can handle.
