### ISSUE TITLE
श्रु सिप्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#159]
Final forms are :
आखिरी रूप हैं :
1 - शृणोसि
अत्र सस्य षादेशः करणीयः , शृणोषि इति भवेत्।

**Comment by drdhaval2785** [comment]
which sUtra?
It will take much time if I search on my own.

**Comment by mrudani** [comment]
Adesha pratyayayoh, si iti prtyayah atah tasya shadeSaH bhavati.
