### ISSUE TITLE
सम् श्रु

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#161]
अर्तिश्रुदृशिभ्यश्चेति वक्तव्यम् इति वार्तिकेन अत्र आत्मनेपदं भवेत्, संशृणुते इत्यादीनि आत्मनेपदरूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
@mrudani 
वार्तिक missing in our database.
Which vArtika number as per mahAbhASya ?
