### ISSUE TITLE
तक्षूँ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#164]
तक्ष्णोति णत्वविधायकसूत्रोल्लेखनम्। स्वरितेतः परिवर्तनञ्च।

**Comment by drdhaval2785** [comment]
Natva is handled now.

I didn't understand what you mean by svaritetaH parivartanam.
Explain a bit.

**Comment by drdhaval2785** [comment]
@mrudani Waiting for your feedback

**Comment by drdhaval2785** [comment]
There is no 'svaritet' here.
It is udAttet.
Closing this as of now.
