### ISSUE TITLE
तिजँ निशाने क्षमाभिन्ने अर्थे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#166]
Final forms are :
आखिरी रूप हैं :
1 - तेजते
क्षमाभिन्ने णिच् भवेत् तेजयति, तेजयते।

**Comment by mrudani** [comment]
तिज क्षमायाम् तितिक्षते इति भवेत्।

**Comment by drdhaval2785** [comment]
Nic happens.

san would have to wait till sanAdi is taught.

**Comment by drdhaval2785** [comment]
Now happens. #167 cured this too.
