### ISSUE TITLE
गुपूँ रक्षणे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#168]
लिट्यभ्यासस्योभयेषाम् (६.१.१७) :
1 - गोपाय्+अ+ति
अनेन सम्प्रासरणं खलु विधीयते, सम्प्रति सम्प्रसारणप्रसङ्गः क्व?

**Comment by drdhaval2785** [comment]
It was wrong data entry of 6.1.17 instead of 6.1.97 of ato guNe.
Therefore it was displayed wrong.
Now corrected.
