### ISSUE TITLE
धूपँ सन्तापे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#169]
अत्रापि लिट्यभ्यासस्योभयेषाम् इति सूत्रस्य प्रसक्तिरेव नास्ति। परन्तु तस्य प्रवृत्तः दर्श्यते।

**Comment by drdhaval2785** [comment]
It was wrong data entry of 6.1.17 instead of 6.1.97 of ato guNe.
Therefore it was displayed wrong.
Now corrected.
