### ISSUE TITLE
पणं व्यवहारे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#170]
व्यवहारार्थे अपि आयप्रत्ययः भवति। यत्र व्यवहारार्थे आयप्रत्ययः तत्रात्मनेपदं न भवति - पणायति इति।

**Comment by drdhaval2785** [comment]
The relavent commentary is as follows:

काशिका-वृत्तिः
गुपूधूपविच्छिपणिपनिभ्य आयः ३।१।२८

गुपू रक्षणे, धूप सन्तापे, विच्छ गतौ, पण व्यवहारे स्तुतौ च, पन च इत्येतेभ्यो धातुभ्यः आयप्रत्ययो भवति। तोपायति। धूपयति। विच्छायति। पणायति। पनायति। स्तुत्यर्थेन पनिना साहचर्यात् तदर्थः पणिः प्रत्ययम् उत्पादयति न व्यवहारार्थः। शतस्य पणते। सहस्रसय पणते। अनुबन्धश्च केवले चरितार्थः, तेन आयप्रत्ययान्तान्नात्मनेपदं भवति। 

The take home message is -
1. paRa stutyarTaka has Aya pratyaya and parasmaipada endings like paRAyati.
2. paRa vyavahArArtha doesn't have Aya pratyaya and has Atmanepada endings like paRate.
