### ISSUE TITLE
भृश् + आताम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#171]
By yo'ci (7.2.89) :
योऽचि (७.२.८९) :
1 - भ्राश्+य+इय्+ते
2 - भ्राश्+अ+इय्+ते
By īdyati (6.4.65) :
ईद्यति (६.४.६५) :
1 - भ्राश्+य+इ+ते
2 - भ्राश्+अ+इ+ते
अत्र आतो ङितः इति सूत्रेण आकारस्य इयादेशः भवेत्।
आकारस्य ङिदवयवस्य अकारान्तादङ्गादुत्तरस्य सार्वधातुकस्य इयित्ययम् आदेशो भवति।
योचि, ईद्यति इत्यनयोः प्रवृत्तिर्न।

**Comment by drdhaval2785** [comment]
They were issues of wrong numberings.
Corrected.
Ato GitaH and lopo vyorvali displayed.
