### ISSUE TITLE
भ्रमुँ भ्वादि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#172]
By śamāmaṣṭānāṃ dīrghaḥ śyani (7.3.74) :
शमामष्टानां दीर्घः श्यनि (७.३.७४) :
1 - भ्राम्+श्यन्+तिप्
2 - भ्रमुँ+शप्+तिप्

अनेन सूत्रेण दीर्घः  दिवादिगणे विद्यमानभ्रमुधातोः न तु भ्वादिगणधातोः, अतः भ्रमति, भ्रम्यति इत्येव भवतः।

**Comment by drdhaval2785** [comment]
क्षीरतरङ्गिणीमते तु भ्राम्यतीत्येव ।
भ्वादि  - http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-6-9-2014/kRi546.html 
दिवादि - http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-6-9-2014/kRi865.html
