### ISSUE TITLE
ल॑षँ॒॑ - कान्तौ, भ्वादि ०१.१०३३

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#174]
a॑ṣaṃ॒॑ - kāntau, bhvādi 01.1033
ल॑षँ॒॑ - कान्तौ, भ्वादि ०१.१०३३
By svaritañitaḥ kartrabhiprāye kriyāphale (1.3.72) :
स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२) :
लट् लकार
लषँ + तिप् Go Back

Final forms are :
आखिरी रूप हैं :
1 - लष्यति
2 - लषति

स्वरितेत्वात् उभयपदिरूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
It happens after all parasmaipadi forms are over.
