### ISSUE TITLE
यमँ उपरमे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#175]
एषः न स्वरितेत्।
By svaritañitaḥ kartrabhiprāye kriyāphale (1.3.72) :
स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२) :
इति न भवेत्।

**Comment by drdhaval2785** [comment]
As per http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/compare_with_svara.html, यम चुरादि is उभयपदी. यम भ्वादि - परस्मैपदी.

**Comment by drdhaval2785** [comment]
Corrected
