### ISSUE TITLE
ध्मा

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#179]
By pāghrādhmāsthāmnādāṇdṛśyarttisarttiśadasadāṃ pibajighradhamatiṣṭhamanayacchapaśyarcchadhauśīyasīdāḥ (7.3.78) :
पाघ्राध्मास्थाम्नादाण्दृश्यर्त्तिसर्त्तिशदसदां पिबजिघ्रधमतिष्ठमनयच्छपश्यर्च्छधौशीयसीदाः (७.३.७८) :
1 - धम्+शप्+तिप्

धम इति आदेशः स्यात् न तु हलन्तः।

**Comment by drdhaval2785** [comment]
Added 'a' at the end of all Adezas of the sUtra 7.3.78 (except 'DO')
