### ISSUE TITLE
ष्ठा

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#180]
ṣṭhā॒ - gatinivṛttau, bhvādi 01.1077
ष्ठा॒ - गतिनिवृत्तौ, भ्वादि ०१.१०७७
By parasmaipadī :
परस्मैपदी :
लट् लकार
ष्ठा + तिप् Go Back
By nimittApAye naimittikasyApyapAyaH (paribhASA) :
निमित्तापाये नैमित्तिकस्याप्यपायः (परिभाषा) :

अत्रादौ धात्वादेः षः सः इति सूत्रेण षस्य सः आदेशः भवेत्, ततः निमित्तापाये इति परिभाषा।

**Comment by mrudani** [comment]
Final forms are :
आखिरी रूप हैं :
1 - स्थाति
पाघ्राध्मा इत्यादिसूत्रेण अत्र तिष्ठ आदेशः स्यात्, तिष्ठति इति भवेत्।

**Comment by drdhaval2785** [comment]
तिष्ठति is done.
The display of nimittApAye naimittikasyApyapAyam is pending to correct.
It is noted as separate issue
