### ISSUE TITLE
दाण् भ्वादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#181]
By āhasthaḥ (8.2.35) :
आहस्थः (८.२.३५) :
1 - यच्छ्+अ+ति
By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - यच्छति

एतयोः सूत्रयोः किमत्र प्रयोजनम्।

**Comment by drdhaval2785** [comment]
This was wrong numbering for vrazcabhrasja... because 'yacC' had 'C' at the end.
Corrected vrazcabhrasja... code to check C+jhal.
