### ISSUE TITLE
दृशिर्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#182]
By tiṅśitsārvadhātukam (3.4.113) :
तिङ्शित्सार्वधातुकम् (३.४.११३) :
1 - दृशिँर्+तिप्
By vartamāne laṭ (3.2.123) :
वर्तमाने लट् (३.२.१२३) :
1 - दृशिँर्+तिप्
By bhūvādayo dhātavaḥ (1.3.1) :
भूवादयो धातवः (१.३.१) :
1 - दृशिँर्+तिप्
By laḥ karmaṇi ca bhāve cākarmakebhyaḥ. (3.4.69) :
लः कर्मणि च भावे चाकर्मकेभ्यः. (३.४.६९) :
1 - दृशिँर्+तिप्
By lasya (3.4.77) :
लस्य (३.४.७७) :
1 - दृशिँर्+तिप्
By tiptasjhisipthasthamibvasmas tātāṃjhathāsāthāṃdhvamiḍvahimahiṅ (3.4.78) :
तिप्तस्झिसिप्थस्थमिब्वस्मस् तातांझथासाथांध्वमिड्वहिमहिङ् (३.४.७८) :
1 - दृशिँर्+तिप्
By laḥ parasmaipadam (1.4.99) :
लः परस्मैपदम् (१.४.९९) :
1 - दृशिँर्+तिप्
By tiṅastrīṇi trīṇi prathamamadhyamottamāḥ (1.4.101) :
तिङस्त्रीणि त्रीणि प्रथममध्यमोत्तमाः (१.४.१०१) :
1 - दृशिँर्+तिप्
By tānyekavacanadvivacanabahuvacanānyekaśaḥ (1.4.102) :
तान्येकवचनद्विवचनबहुवचनान्येकशः (१.४.१०२) :
1 - दृशिँर्+तिप्
By śeṣe prathamaḥ (1.4.108) :
शेषे प्रथमः (१.४.१०८) :
1 - दृशिँर्+तिप्
By kartari śap (3.1.68) :
कर्तरि शप्‌ (३.१.६८) :
1 - दृशिँर्+शप्+तिप्
By iraḥ upasaṅkhyānam (vA 1.3.7-4) :
इरः उपसङ्ख्यानम् (वा १.३.७-४) :
1 - दृशिँर्+शप्+तिप्
By tiṅśitsārvadhātukam (3.4.113) :
तिङ्शित्सार्वधातुकम् (३.४.११३) :
1 - दृशिँर्+शप्+तिप्
By laśakvataddhite (1.3.8) :
लशक्वतद्धिते (१.३.८) :
1 - दृशिँर्+शप्+तिप्
By tasya lopaḥ (1.3.9) :
तस्य लोपः (१.३.९) :
1 - दृशिँर्+अप्+तिप्
By halantyam (1.3.3) :
हलन्त्यम् (१.३.३) :
1 - दृशिँर्+अप्+तिप्
By tasya lopaḥ (1.3.9) :
तस्य लोपः (१.३.९) :
1 - दृशिँ+अ+ति
By upadeśe'janunāsika it (1.3.2) :
उपदेशेऽजनुनासिक इत् (१.३.२) :
1 - दृशिँ+अ+ति
By tasya lopaḥ (1.3.9) :
तस्य लोपः (१.३.९) :
1 - दृश्+अ+ति
By pugantalaghūpadhasya ca (7.3.86) :
पुगन्तलघूपधस्य च (७.३.८६) :
1 - दर्श्+अ+ति
By āhasthaḥ (8.2.35) :
आहस्थः (८.२.३५) :
1 - दर्श्+अ+ति
Final forms are :
आखिरी रूप हैं :
1 - दर्शति

पश्यति इति भवेत्। पाघ्राध्मा इत्यादिसूत्रेण पश्य आदेशः भवति।

**Comment by drdhaval2785** [comment]
Data entry error. Earlier entered 'dfzi!r' instead of 'dfSi!r' in SLP1.
