### ISSUE TITLE
सृ गतौ भ्वादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#184]
By kartari śap (3.1.68) :
कर्तरि शप्‌ (३.१.६८) :
1 - सृ+शप्+तिप्
By juhotyādibhyaḥ śluḥ (2.4.75) :
जुहोत्यादिभ्यः श्लुः (२.४.७५) :
1 - सृ+तिप्
By ślau (6.1.10) :
श्लौ (६.१.१०) :
1 - सिऋ+तिप्
By artipipartyośca (7.4.77) :
अर्तिपिपर्त्योश्च (७.४.७७) :
1 - सिऋ+तिप्
By halantyam (1.3.3) :
हलन्त्यम् (१.३.३) :
1 - सिऋ+तिप्
By tasya lopaḥ (1.3.9) :
तस्य लोपः (१.३.९) :
1 - सिऋ+ति
By sārvadhātukārdhadhātukayoḥ (7.3.84) :
सार्वधातुकार्धधातुकयोः (७.३.८४) :
1 - सिअर्+ति
By ubhe abhyastam (6.1.5) :
उभे अभ्यस्तम् (६.१.५) :
1 - सिअर्ति
By iko yaṇaci (6.1.77) :
इको यणचि (६.१.७७) :
1 - स्यर्ति
Final forms are :
आखिरी रूप हैं :
1 - स्यर्ति

एष धातुः भ्वादिः कथं जुहोत्यादिभ्यः श्लुः इति प्रवर्तते। पाघ्राध्मा इत्यादिसूत्रेण धाव आदेशः स्यात्, धावति इति सिध्येत्।

**Comment by drdhaval2785** [comment]
'f' and 'sf' both have some Adezas. Therefore, 'f' Adeza happened first. Changed the order. Placed 'sf' before 'f' in list of changes.
