### ISSUE TITLE
र॒ञ्जँ॒॑ - रागे मित् १९४०, भ्वादि ०१.११५४

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#187]
स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२) :
Final forms are :
आखिरी रूप हैं :
1 - रजति

स्वरितेत्त्वात् उभयपदिधातुरेषः। अतः रजति, रजते इति रूपद्वयं भवेत्।

**Comment by drdhaval2785** [comment]
It gives all forms.

N.B. In ubhayapadI words, actually we give parasmaipadi (tip-mas) first and then Atmanepadi forms (ta-mahiG)
Therefore, rajate will be created by rajAmaH.
