### ISSUE TITLE
कृ॑पूँ॒ - सामर्थ्ये

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#188]
कृ॑पूँ॒ - सामर्थ्ये, भ्वादि 01.0875 कृ॑पूँ॒ - सामर्थ्ये, भ्वादि 01.0866
उभयोः कः भेदः।

**Comment by drdhaval2785** [comment]
There doesn't seem to be any difference. Removed कृ॑पूँ॒ - सामर्थ्ये, भ्वादि 01.0875
