### ISSUE TITLE
"Page not found" for link in Readme

### ISSUE THREAD

**Issue by ppasedach** [drdhaval2785/SanskritVerb#194]
http://www.lanover.com/lan/sanskrit/SanskritVerb/tiGanta.html should be http://www.sanskritworld.in/sanskrittool/SanskritVerb/tiGanta.html I guess.

**Comment by drdhaval2785** [comment]
Yes. The server changed recently. Thanks for drawing attention. Will relook for occurrence of lanover everywhere.

Thanks for sparing time for feedback.

Appreciate it.
