### ISSUE TITLE
Compare outcome with existing lists

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#196]
It would be highly beneficial if some tool can be created for comparing the output of SanskritVerb verb forms with other verb form lists like
1. http://sanskrit.inria.fr/DATA/XML/
2. http://sanskrit.uohyd.ac.in/scl/ - I am not sure where the data lies.
3. http://sanskrit.jnu.ac.in/tinanta/data-resources/dhaturoopa_Hindi_translations2.txt
etc

**Comment by funderburkjim** [comment]
I am interested in this.  In particular I had not been aware of the DATA/XML/ resource that Huet is now making available.

My first interest is in comparing to my conjugations/declensions in https://github.com/funderburkjim/elispsanskrit,

but, since I am interested in eventually understanding your derivations, I could also work in 
comparing your results.

My first, and most basic question  is,  how to get a conjugation table for a given:
   root, class, pada, tense, and voice
out of your system.

In downloading your system, and reading the readme, it appears that the entry point for computations is tiganta.html.   The speed up is quite pleasing.

Is there a command-line version, which generates only the final forms?

**Comment by drdhaval2785** [comment]
There was one tool in the offing when you asked the question.
Now the tool is ready.

Click [this shell file](https://github.com/drdhaval2785/SanskritVerb/blob/master/wrongformfinder.sh).

1. It will send all 2000 odd verbs one by one to tiGanta.php
2. It will fetch the verb forms generated for total of 10 tenses for each given verb. (law, liw, luw, lfw, low, laN, ASIrliN, viDiliN, luN, lfN). Currently sArvaDAtukalew and ArDaDAtukalew are not included (because Gerard's database doesn't have many of them. So most of them return false positives.
3. It checks whether the generated form belongs to the verb forms of [Gerard's database modified](https://github.com/drdhaval2785/SanskritVerb/blob/master/verbforms_gerard.txt) for our use.
4. If the verb form is not found in the database, it is stored in the suspectverbforms.txt file.
5. Typical line in suspectverbforms.txt file would be `$verbform-($root,$tense,$suffix,$verbset,$verbnumber)` format e.g. `buBUTa-(BU,liw,sip,BvAdi,01.0001)`
6. The person who is going to test the machine would go to the tiGanta.html and try on the machine, whether the form is getting proper or not, because some of the forms may be corrected if user feedback is there.

As a test case, I am copy pasting the errors found in around 10*9 = 90+ forms of 'BU' dhAtu.
```
buBUTa-(BU,liw,sip,BvAdi,01.0001)
BavatAd-(BU,low,tip,BvAdi,01.0001)
BavatAt-(BU,low,tip,BvAdi,01.0001)
BavatAd-(BU,low,sip,BvAdi,01.0001)
BavatAt-(BU,low,sip,BvAdi,01.0001)
```

As one can see, there are only 5 suspect forms which are not found in Gerard's database. So only 5 forms require further scrutiny. Thus we are saved from testing whole 90+ forms. At least their final products are correct, even if there are some rule mistakes in between.
This should be a good starting point.

N.B. This code takes around 20-30 seconds per verb i.e. around 1000 minutes for 2000 verbs. So be patient. The console would show the progress achieved. Best luck.

If this goes through well, we would be replicate the same method with other databses.

**Comment by drdhaval2785** [comment]
Sorry. I had forgotten that your interest and my interest are a bit different. So closed the issue inadvertantly.
```
I am interested in this. In particular I had not been aware of the DATA/XML/ resource that Huet is now making available.
```
Not many are. His link which leads to this data is not at all visible. I have often to find out from my browsing history, and not from his website.

```
My first interest is in comparing to my conjugations/declensions in https://github.com/funderburkjim/elispsanskrit,
```
I would be interested in how you derive the conjugation / declension tables by this code.

```
but, since I am interested in eventually understanding your derivations, I could also work in
comparing your results.
```
The comparision work has started. Right now I am storing the results which are not enumerated in Gerard's database as a file of potentially suspect verb forms which requires human scrutiny. Code executed for 200/2000 dhAtus. Maybe tonight we will get a raw data.

```
My first, and most basic question is, how to get a conjugation table for a given:
root, class, pada, tense, and voice
out of your system.
```
I earlier had created a commandline tool, but right now it has been modified to work for finding errors.
Once that exercise is over, I will once again switch it back to normal. (with a hope to keep both the options accessible. That depends on my coding skills.)

```
In downloading your system, and reading the readme, it appears that the entry point for computations is tiganta.html. The speed up is quite pleasing.
```
Right.

```
Is there a command-line version, which generates only the final forms?
```
Will take a couple of days. Was there, now gone.

**Comment by gasyoun** [comment]
1000 minutes for 2000 verbs not bad at all. Can we make a table similar to Bucknell?

![pages from bucknell_sanskritmanual-2004](https://cloud.githubusercontent.com/assets/80761/10601632/8a13467a-771b-11e5-813a-c6e042e26cea.jpg)

**Comment by drdhaval2785** [comment]
I guess I miscalculated the speed. It takes around 1 day for 2000+ verb forms analysis.
Will post the outcome in around 6-7 hours.

**Comment by drdhaval2785** [comment]
The list is [here](https://www.dropbox.com/s/ubde3vbjsujxmwn/suspectverbforms21102015.txt?dl=0).
Some 7 MB file. Download only if needed. :)

**Comment by drdhaval2785** [comment]
The tool to generate txt files of [verbforms](https://github.com/drdhaval2785/SanskritVerb/blob/master/verbforms_gerard.txt) and [verbs](https://github.com/drdhaval2785/SanskritVerb/blob/master/verblist_gerard.txt) from Gerard's database are functions verbformlist() and verblist() in [sanskritmark.py](https://github.com/drdhaval2785/inriaxmlwrapper/blob/master/sanskritmark.py)

**Comment by drdhaval2785** [comment]
Right now refactored the code - now the code will only send the verb forms whose base root is there in Gerard's database and the output isn't in Gerard's.
This way we will be able to reduce the bulk of the file - because many false positives (because of non dealing of the verb altogether by Gerard) would be eliminated.
Will post the result tomorrow.
