### ISSUE TITLE
Testing of suspect verb forms

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#201]
@mrudani 
This issue is an intermediate output of https://github.com/drdhaval2785/SanskritVerb/issues/196.

Please find attached two files which compare our outcome with Gerard's database.

## Gerad's database

1. suspect verb forms list in [SLP1](https://www.dropbox.com/s/ubde3vbjsujxmwn/suspectverbforms21102015.txt?dl=0) - 7 MB - ignore (too lengthy)
2. suspect verb forms list in [Devanagari](https://www.dropbox.com/s/c8dk99trk9sdq74/suspectverbforms_deva_21102015.txt?dl=0) - 20 MB - ignore (too lengthy).
3. [suspect verb forms in SLP1](https://www.dropbox.com/s/v0w8ih3kwm9u34s/suspectverbforms_abridged_21102015.txt?dl=0) - Use this
4. [suspect verb forms in Devanagari](https://www.dropbox.com/s/hfzs136lu38h5vo/suspectverbforms_abridged_deva_21102015.txt?dl=0) - Use this

## UoHyd database
1. [UoHyd](https://www.dropbox.com/s/141dw97w021d6hu/UoHyd_all_forms.txt?dl=0) database in WX encoding, received with thanks from Amba madam. 

## Expected work
What I would like you to do is to have a brief overview of commonly used verbs and note the bugs in separate threads.

I would also like you to wait for a day or so, so that I can still reduce the number of entries further. 
Please go ahead when I give you a go ahead.

## Note to self - 
Current output is only comparision against Gerard's database.
Further error list generation by comparing with other potential verb form databases are pending.
This tool is designed to help you easily find out potential errors.

**Comment by drdhaval2785** [comment]
@mrudani 

Please ignore the earlier lengthier files.

You should test the following file
1. [suspect verb forms in SLP1](https://www.dropbox.com/s/v0w8ih3kwm9u34s/suspectverbforms_abridged_21102015.txt?dl=0)
2. [suspect verb forms in Devanagari](https://www.dropbox.com/s/hfzs136lu38h5vo/suspectverbforms_abridged_deva_21102015.txt?dl=0)

**Comment by drdhaval2785** [comment]
I think you would be more comfortable with Devanagari list.
Whenever you find some error, start a separate issue with title `verbform lakAra suffix` e.g. `अक्ष्णोसि लट्‌ सिप्‌`.
If we stick to a uniform issue name pattern, we would be able to manipulate it later also.
I have created a sample issue.

**Comment by gasyoun** [comment]
54k entries? It's 50k more than one can handle. If I'm right @mrudani works with github on her phone, she does not even has a laptop, that means her conditions are hard. Such a list is unmanagable.

![list](https://cloud.githubusercontent.com/assets/80761/10676410/930c2220-790e-11e5-892a-c80dd9a6e4e5.PNG)

**Comment by drdhaval2785** [comment]
Marcis, I don't intend to correct 54000 entries. I intend to use these
forms to find out errors in rule triggerring. E.g. if अक्ष्णोसि is bad and
I correct the rule, potentially I correct that errror for 600 verbs. So one
correction would decrease 500 - 600 entries. Maybe i will regenerate the
list after correction for one verb is installed. Let us see the impact on
numbers.
I am sure it would decrease exponentially.

**Comment by gasyoun** [comment]
So be it.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/tree/master/suspectforms is the place where I keep the suspect files with DDMMYYYY suffix to identify the date when this was created.
There has been significant reduction in the list size.
After I correct some substantial issue, I regenerate the list to have a look at whether my intervention  was useful or it resulted in more wrong forms.

**Comment by drdhaval2785** [comment]
This happens now when I run wrongformfinder.sh script.
