### ISSUE TITLE
लट् लकार चिञ् + तिप् 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#222]
By karmaṇyākrośe kṛñaḥ khamuñ (3.4.25) :

कर्मण्याक्रोशे कृञः खमुञ् (३.४.२५) :

1 - चिञ्+णिच्+तिप्

By kartari śap (3.1.68) :

कर्तरि शप्‌ (३.१.६८) :

1 - चिञ्+णिच्+शप्+तिप्

By tiṅśitsārvadhātukam (3.4.113) :

तिङ्शित्सार्वधातुकम् (३.४.११३) :

1 - चिञ्+णिच्+शप्+तिप्

By laśakvataddhite (1.3.8) :

लशक्वतद्धिते (१.३.८) :

1 - चिञ्+णिच्+शप्+तिप्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - चिञ्+णिच्+अप्+तिप्

By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - चिञ्+णिच्+अप्+तिप्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - चि+णि+अ+ति

By apaguro ṇamuli (6.1.53) :

अपगुरो णमुलि (६.१.५३) :

1 - चि+णि+अ+ति

2 - चा+णि+अ+ति

By arttihrīblīrīknūyīkṣmāyyātāṃ puṅṇau (7.3.36) :

अर्त्तिह्रीब्लीरीक्नूयीक्ष्माय्यातां पुङ्णौ (७.३.३६) :

1 - चि+णि+अ+ति

2 - चाप्+णि+अ+ति

By sanādyantā dhātavaḥ (3.1.32) :

सनाद्यन्ता धातवः (३.१.३२) :

1 - चि+णि+अ+ति

2 - चाप्+णि+अ+ति

By aco ñṇiti (7.2.115) :

अचो ञ्णिति (७.२.११५) :

1 - चै+णि+अ+ति

2 - चाप्+णि+अ+ति

By mitāṃ hrasvaḥ (6.4.92) :

मितां ह्रस्वः (६.४.९२) :

1 - चै+णि+अ+ति

2 - चप्+णि+अ+ति

By cuṭū (1.3.7) :

चुटू (१.३.७) :

1 - चै+णि+अ+ति

2 - चप्+णि+अ+ति

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - चै+इ+अ+ति

2 - चप्+इ+अ+ति

By nābhyastācchatuḥ (7.1.78) :

नाभ्यस्ताच्छतुः (७.१.७८) :

1 - चाय्+इ+अ+ति

2 - चप्+इ+अ+ति

By mitāṃ hrasvaḥ (6.4.92) :

मितां ह्रस्वः (६.४.९२) :

1 - चय्+इ+अ+ति

2 - चप्+इ+अ+ति

By sārvadhātukārdhadhātukayoḥ (7.3.84) :

सार्वधातुकार्धधातुकयोः (७.३.८४) :

1 - चये+अ+ति

2 - चपे+अ+ति

By nābhyastācchatuḥ (7.1.78) :

नाभ्यस्ताच्छतुः (७.१.७८) :

1 - चयय+ति

2 - चपय+ति

Final forms are :

आखिरी रूप हैं :

1 - चययति

2 - चपयति
चाययति इति साधनीयम्।

**Comment by mrudani** [comment]
चि णिच् तिप्
णकारचकारयोः इत्संज्ञायां लोपे - चि इ तिप्
पकारस्यइकत्संज्ञायां तस्यलोपे - चि इ ति
अचो ञ्णिति इति वृद्धौ चै इ ति
आयादेशे - चायि ति
कर्तरि शप् इति शप् प्रत्यये - चायि शप् ति
शकारपकारयोः इत्संज्ञायां तस्य लोपे - चायि अ ति
सार्वधातुकार्धधातुकयोः इति गुणे - चाये अ ति
एचोयवायावः इति अयादेशे चायय् अ ति - चाययति इति भवति।

**Comment by drdhaval2785** [comment]
१. चिस्फुरोर्णौ gives two alternate forms. Can you derive the पुगागम form ?
२. चिञ्‌ धातु is in मित्‌ list in our database. So won't it get back to चययति ?

**Comment by mrudani** [comment]
मिति तु चययति भवेत्तर्हि, 
चिस्फुरोर्णौ -
चि णिच् तिप्
इत्संज्ञालोपोत्तरम् - चि इ ति
अचोञ्णिति वृद्धौ - चै इ ति
चिस्फुरोर्णौ इति एचः आत्वे - चा इ ति
अर्तिह्रीव्ली-- इत्यादिना पुगागमे - चा पुक् इ ति
इत्संज्ञालोपानन्तरं - चा प् इ ति
कर्तरि शप् इति शपि - चा प् इ शप् ति
शकारपकारयोः इत्संज्ञायां लोपे - चा प् इ अ ति
सार्वधातुकार्धधातुकयोः इति इकारस्य गुणे - चापे अ ति
अयादेशे - चापय् अ ति - चापयति।
