### ISSUE TITLE
अकारान्त (कत्थादि) धातु - लिट्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#223]
Please see
```
आ-(अङ्क,लिट्,तिप्,चुरादि,१०.०४७३)
उः-(अङ्क,लिट्,झि,चुरादि,१०.०४७३)
आथुः-(अङ्क,लिट्,थस्,चुरादि,१०.०४७३)
आ-(अङ्क,लिट्,थ,चुरादि,१०.०४७३)
आ-(अङ्क,लिट्,मिप्,चुरादि,१०.०४७३)
एव-(अङ्क,लिट्,वस्,चुरादि,१०.०४७३)
एम-(अङ्क,लिट्,मस्,चुरादि,१०.०४७३)
```
There is an error in the abhyAsa prakriyA.
![capture](https://cloud.githubusercontent.com/assets/5755132/10715035/cb68ae48-7b2c-11e5-887b-f1982236fcdd.PNG)

**Comment by drdhaval2785** [comment]
@mrudani 
Can you please write the derivation process for such akArAnta dhAtus ?

**Comment by mrudani** [comment]
रच णिच् लिट्
कास्प्रत्ययादाममन्त्रे लिटि इति आम्
रच णिच् आम् लिट्
अतो लोपः इति अकारलोपे रच् णिच् आम् लिट्
णकारचाकारयोः इत्संज्ञायां लोपे 
रच् इ आम् लिट् - रचि आम् लिट्
सार्वधातुकार्धधातुकयोः इति गुणे
रचे आम् लिट्
अयादेशे रचय् आम् लिट्
आमः इति सूत्रेण लिटः लोपे रचयाम्
कृञ्चानुप्रयुज्यते लिटि इति कृ, भू, अस् धातुषु एकस्य अनुप्रयोगः
रचयाम् कृ
आम्प्रत्ययवत्कृञोनुप्रयोगस्य इति सूत्रेण यस्मात् आम्प्रत्ययः तस्य धातोः यत्पदं (आत्मनेपदं,परस्मैपदं) तदेव अनुप्रयुक्तधातोरपि भवति
णिजन्तधातवः उभयपदिनः भवन्ति, तस्मात् आत्मनेपदि, परस्मैपदि च रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
![10-28-2015 9-20-15 pm](https://cloud.githubusercontent.com/assets/5755132/10794136/b9b612d2-7db9-11e5-865c-4c1b73b2e1ad.png)

This is the list of forms made. If corrections needed, raise a separate issue.
