### ISSUE TITLE
स्थाध्वोरिच्च - sUtra number not known

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#243]
I am unable to locate this vArtika anywhere. 
@mrudani may like to refer me to proper vArtika number / sUtra number etc.
I think I saw this rule somewhere in sahajabodha.

**Comment by mrudani** [comment]
स्थाघ्वोरिच्च इति सूत्रम्, अस्य अष्टाध्यायीसंख्या - 1-2-17
