### ISSUE TITLE
अ॑ङ्क॑ - पदे लक्षणे च, चुरादि १०.०४७३ , लङ् लकार

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#262]
अत्रापि अयादेशः नाभ्यस्ताच्छतुः इत्यनेनैव दर्शितः, एचोयवायावः इति भवेत्।

**Comment by drdhaval2785** [comment]
It was wrongly stored as 7.1.78 and giving wrong sUtra.
Corrected to 6.1.78 for eco'yavAyAvaH
