### ISSUE TITLE
अञ्चुँ लुट् तिप्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#279]
By ṭeḥ (6.4.143) :

टेः (६.४.१४३) :

1 - अञ्च्+ता

अत्र टेः इति सूत्रस्य न प्रवृत्तिः। भसंज्ञाभावात्। डित्त्वसामर्थ्यादभस्यापि टेर्लोपः इति सूत्रेण टेर्लोपः।

**Comment by drdhaval2785** [comment]
Words in vArtika are `डिति टेः लोपात् लोपः (वा २.४.८५-७)` in our database.
Kept them.
Means the same.
