### ISSUE TITLE
अगिँ भ्वादि लिट्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#285]
Gerard shows this 

![capture](https://cloud.githubusercontent.com/assets/5755132/10931192/7feb26fa-82eb-11e5-99c6-0b36b2a4e98b.png)

Our machine shows this 

![capture](https://cloud.githubusercontent.com/assets/5755132/10931206/9f79f2f8-82eb-11e5-9175-70d568af809b.png)

@mrudani may like to comment which are the correct forms.

**Comment by mrudani** [comment]
आनङ्ग इत्येव साधु, अत आदेः इत्यनेन अभ्यासस्य आदेः अकारस्य दीर्घः भवेत्.
