### ISSUE TITLE
अगिँ भ्वादि लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#286]
There is no comparision forthcoming from Gerard / Amba.

Our machine gives 
![11-4-2015 12-16-05 pm](https://cloud.githubusercontent.com/assets/5755132/10931516/f2481ee0-82ed-11e5-9940-b7fb78fb84f2.png)

Is this fine @mrudani ?

**Comment by mrudani** [comment]
साधु रूपाणि
