### ISSUE TITLE
अगिँ लुट् तस्, झि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#292]
1. By ḍiti ṭeḥ lopāt lopaḥ (vA 2.4.85-7) :

डिति टेः लोपात् लोपः (वा २.४.८५-७) :

1 - अन्ग्+तास्+रौ
...........................................................
2. By ḍiti ṭeḥ lopāt lopaḥ (vA 2.4.85-7) :

डिति टेः लोपात् लोपः (वा २.४.८५-७) :

1 - अन्ग्+तास्+रस्

अत्र एतदनावश्यकम्।

**Comment by drdhaval2785** [comment]
@mrudani 
Then which vArtika / sUtra causes elision of टि in case of डित्‌ pratyaya ?

**Comment by mrudani** [comment]
रि च इति सूत्रेण लोपः, तत् तत्र लिखितमेव अतः अन्यस्य नास्त्यावश्यकता।

**Comment by drdhaval2785** [comment]
OK.
