### ISSUE TITLE
अगिँ लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#294]
1 - अन्ग्+सिच्+ई+त्
इत्संज्ञालोपोत्तरं अन्ग् स् ई त्
आर्धधातुकस्य इड्वलादेः इति इडागमे
अन्ग् इ स् ई त्
इट ईटि इति सस्य लोपे
अन्ग् इ ई त्
सवर्णदीर्घे कृते आन्गीत्
अनुस्वारे, परसवर्णे च कृते आङ्गीत्।

**Comment by drdhaval2785** [comment]
It is too difficult to alter. 
Positioning may alter, because we are applying a different algorithm.

There doesn't seem any wrong rule application.

**Comment by drdhaval2785** [comment]
Happens now.
