### ISSUE TITLE
अञ्चुँ लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#296]
आ अञ्च्+सिच्+ई+त्
इकारचकारयोः इत्संज्ञायां लोपे
आ अञ्च् स् ई त्
आर्धधातुकस्येड्वलादेः इति इडागमे
आ अञ्च् इ स् ई त्
इट ईटि इति सलोपे 
आ अञ्च इ ई त्
आटश्च इति वृद्धौ आञ्च् इ ई त्
सवर्णदीर्घे कृते आञ्चीत् इति भवति।

**Comment by drdhaval2785** [comment]
Forms are correct.
Rules applied are correct.
Order would be somewhat different as we are generating via a different algorithm.
Not possible to handle this at this stage.
Postponing it.

**Comment by drdhaval2785** [comment]
Now the rule order is also the same.
