### ISSUE TITLE
अ॑ञ्चुँ॒॑ - गतौ याचने च, भ्वादि ०१.०२१५ 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#297]
By svaritañitaḥ kartrabhiprāye kriyāphale (1.3.72) :

स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२) : 
एतत् सूत्रं आत्मनेपदारम्भे भवेत् खलु।

**Comment by mrudani** [comment]
अन्ते आत्मनेपदरूपाणि न सन्ति।

**Comment by drdhaval2785** [comment]
http://www.sanskritworld.in/sanskrittool/SanskritVerb/tiGanta.php?first=aYcu!&upasarga=&lakAra=luN&vAcya=kartR&tran=SLP1&sanAdi=&frontend=1&cond11=2&number=01.0215&cond50=2&step=11

This gives the Atmanepada output.
