### ISSUE TITLE
अ॑जिँ॑ - भाषार्थः च, चुरादि १०.००२१ 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#298]
By idito num dhātoḥ (7.1.58) :

इदितो नुम् धातोः (७.१.५८) :

1 - अजे+अ+ति

By eco'yavāyāvaḥ (6.1.78) :

एचोऽयवायावः (६.१.७८) :

1 - अजय+ति

Final forms are :

आखिरी रूप हैं :

1 - अजयति

नुमागमविधायकसूत्रमस्ति परन्तु नुमागमः न दृश्यते।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/11303383/8f4dc88e-8fc8-11e5-8d35-eb88aac09a9c.png)

Corrected.
