### ISSUE TITLE
अजिँ चुरादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#300]
अजिँ धातोः नुमागमः सर्वेषु लकारेषु न दृश्यते। तथा च आत्मनेपदरूपाणि अपि योजनीयानि।

**Comment by drdhaval2785** [comment]
णिचश्च इत्यनेन उभयपदित्वं भवेत्‌ । अस्माकीने यन्त्रे तु णिचश्च इत्यनेन परस्मैपदित्वं दत्तं आदौ । अधुना उभयपदित्वं दत्तम्‌ ।
