### ISSUE TITLE
अञ्जूँ लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#301]
By aniditāṃ hala upadhāyāḥ kṅiti (6.4.24) :+1: 
अनिदितां हल उपधायाः क्ङिति (६.४.२४) :
1 - अज्+ति
By rudhādibhyaḥ śnam (3.1.78) :
रुधादिभ्यः श्नम् (३.१.७८) :
1 - अनज्+ति
आदौ श्नम्, श्नमः शित्त्वात् सार्वधातुकत्वं, अपित्त्वात् ङित्त्वातिदेशः, तस्मात् अनिदितामित्यस्य प्रवृत्तिः।

2. By gkṅiti ca (1.1.5) :
ग्क्ङिति च (१.१.५) :
1 - अनज्+ति

अस्य प्रवृत्तिरत्र नास्ति।

3. By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - अनक्ति
By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - अनक्ति

अत्र वारद्वयं सूत्रप्रवृत्तिर्दर्शिता।

**Comment by drdhaval2785** [comment]
श्नमः मित्त्वाद्मिदचोऽन्त्यात्पर इति परिभाषासूत्रेण श्नमः स्थितिः अन्त्यात्परः, न तु अन्ते । तथा स्थिते श्नमः ङित्त्वातिदेशः नास्ति । ङिति इति सप्तमीनिर्दिष्टपरत्वस्याभावात्‌ अनिदितामित्यस्य प्रवृत्तिरपि नास्ति इति मे मतिः ।

http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-6-9-2014/mA1059.html
अत्रापि श्नान्नलोपः -> श्नसोरल्लोपः इति स्थिते नकारलोपः कृतः ।
अनिदितां हल इत्यनेन नकारलोपो न ।

@mrudani may like to comment and examine.
