### ISSUE TITLE
अञ्जूँ लिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#303]
By rudhādibhyaḥ śnam (3.1.78) :

रुधादिभ्यः श्नम् (३.१.७८) :

1 - अनज्+यान+त्

यासुटः श्नम् कथं भवति।
अञ्ज्यात्, अञ्ज्याद् इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
'यासुट्‌ परस्मैपदेषूदात्तो ङिच्च', 'किदाशिषि' इत्याभ्यां सूत्राभ्यां ङिद्वत्त्वकिद्वत्त्वे च भवतः ।
अतः 'अनिदितां हल उपधायाः क्ङिति' इति सूत्रेण नकारलोपे - 'अज्यात्‌' इति रूपं भवेदिति मे मतिः ।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/11303224/c3d7f4f4-8fc7-11e5-8324-79735ef6d38e.png)
