### ISSUE TITLE
अञ्जूँ लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#304]
आञ्जीत्
आ अञ्ज् इ स् ई त्
इट ईटि इति सलोपे
आ अञ्ज् इ ई त्
सवर्णदीर्घे 
आ अञ्जीत्
आटश्च इति वृद्धौ आञ्जीत् इति भवेत्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/11303286/22c5aed4-8fc8-11e5-95bd-e4bb3d7267a0.png)
