### ISSUE TITLE
अटँ लुट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#307]
By ḍiti ṭeḥ lopāt lopaḥ (vA 2.4.85-7) :

डिति टेः लोपात् लोपः (वा २.४.८५-७) :

1 - अट्+तास्+रौ

By ri ca (7.4.51) :

रि च (७.४.५१) :

1 - अट्+तारौ

डितः टेः इत्यादि अत्र अनावश्यकम्।

**Comment by mrudani** [comment]
By ḍiti ṭeḥ lopāt lopaḥ (vA 2.4.85-7) :

डिति टेः लोपात् लोपः (वा २.४.८५-७) :

1 - अट्+तास्+रस्
एतदपि निष्कासनीयम्।

**Comment by drdhaval2785** [comment]
#292 is the same. Handled via 94de9726e87b5e40cbb7dbd0728fa0fd51ca9979 commit
