### ISSUE TITLE
अटँ लुट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#308]
आटीत्  आटिष्टाम्  आटिषुः
आटीत्
आ अट् इ सिच् त्
इकारचकारयोः इत्संज्ञायां लोपे
आ अट् इ स् त्
अस्तिसिचोपृक्ते
आ अट् इ स् ईट् त्
टस्य इत्संज्ञायां लोपे
आ अट् इ स् ई त्
आटश्च इति वृद्धौ
आट् इ स् ई त्
इट ईटि इति सलोपे
आट् इ ई त्
सवर्णदीर्घे
आटीत्।

**Comment by drdhaval2785** [comment]
What is not being shown by the present code ?
I understand that the order is not as desired by you.
But is there any wrong application of rule / non application of applicable rule / wrong form generation ?

We are following a different algorithm.
Therefore, it would not be like classical classroom derivation.
