### ISSUE TITLE
अदँ लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#313]
By liṭi dhātoranabhyāsasya (6.1.8) :

लिटि धातोरनभ्यासस्य (६.१.८) :

1 - अद्+ण

2 - घस्+घस्+ण

By ekāco dve prathamasya (6.1.1) :

एकाचो द्वे प्रथमस्य (६.१.१) :

1 - अद्+ण

2 - घस्+घस्+ण

By halādiḥ śeṣaḥ (7.4.60) :

हलादिः शेषः (७.४.६०) :

1 - अ+ण

2 - घ+घस्+ण

अद इत्यस्यापि द्वित्वं भवति अद् अद् ण
हलादिशेषे अन्तिमं रूपम् आद इति भवेत्।

**Comment by drdhaval2785** [comment]
Difficult one.

**Comment by drdhaval2785** [comment]
Right now kept 'Gasx!' as mandatory Adeza, instead of optional one.

**Comment by drdhaval2785** [comment]
Handled in vidyut-prakriya
