### ISSUE TITLE
अदँ लिट् तस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#314]
अद् अतुस् - आदतुः
घस् अतुस् - जक्षतुः
अद् अद् अतुस्
घस् घस् अतुस्
हलादिशेषे, 
अ अद् अतुस्
घ घस् अतुस्
अभ्यासकार्याणि कृत्वा
आद् अतुस् - आदतुः
ज घस् अतुस्
असंयोगाल्लिट् कित् 
गमहनजनखनघसां लोपः क्ङित्यनङि इति उपधालोपः 
ज घ् स् अतुस्
शासिवसिघसीनां च इति सूत्रेण सस्य षत्वे 
ज घ् ष् अतुस्
खरि च इति चर्त्वे 
ज क् ष् अतुस् - जक्षतुः

**Comment by drdhaval2785** [comment]
Happens now.
