### ISSUE TITLE
अन्ध चुरादिः, लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#320]
आमः इति सूत्रेण आमः उत्तरस्य लिटः लोपः।
आम्प्रत्ययवत् कृञोनुप्रयोगस्य इति सूत्रेण अनुप्रयुक्तस्य कृञः उपग्रहः  आम्प्रत्ययवत् भवति। अर्थात् यस्मात् आम् विहितः तस्य यः उपग्रहः सः अनुप्रयुक्तस्य कृञः अपि भवति।

**Comment by drdhaval2785** [comment]
I am not understanding it properly.
Can you explain it in a bit detail.

How should it be seen in derivation process step by step?

**Comment by mrudani** [comment]
अन्ध णिच् लिट्
अन्धि लिट्
कास्प्रत्ययादाममन्त्रे लिटि इति आम् प्रत्ययः - अन्धि आम् लिट्
गुणे अयादेशे च कृते अन्धय् आम् लिट्
आमः इति सूत्रेण लिटः लोपः - अन्धयाम् 
कृञ् चानुप्रयुज्यते लिटि इति सूत्रेण कृञः अनुप्रयोगः भवेत् - अन्धयाम् कृञ् लिट्.
आम्प्रत्ययवत्कृञोनुप्रयोगस्य इति उपग्रहः निर्णेयः, सम्प्रति णिजन्तस्य उभयपदित्वात् उभयधापि रूपाणि साधनीयानि।
कृञ्धातोः लिटि या प्रक्रिया सैवात्रापि।

**Comment by drdhaval2785** [comment]
Understood and coded properly.
