### ISSUE TITLE
अमँ चुरादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#324]
अमँ धातोः चुरादित्वात् णिचि
अत उपधायाः इति उपधायाः वृद्धिः भवेत्
आमयति इत्यादीनि रूपाणि भवन्ति.

**Comment by mrudani** [comment]
"अमँ चुरादिः" इति दूरवाण्यामसौकर्यात् दोष आगतः, क्षन्तव्या.

**Comment by mrudani** [comment]
तथा च णिच् प्रत्ययः तिप्करणात् पूर्वमेव भवेत्.

**Comment by drdhaval2785** [comment]
Applied ata upaDAyAH.
Application of Ric pratyaya before tip is not possible currently.
