### ISSUE TITLE
अर्थ चुरादिः लिट् 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#327]
कृञः रूपाण्येव सन्ति, असभ्वोः न सन्ति। अर्थयाम्बभूव इत्यादीनि न सन्ति।

**Comment by drdhaval2785** [comment]
It won't be possible soon.
Will try later.

**Comment by drdhaval2785** [comment]
See https://github.com/drdhaval2785/SanskritVerb/issues/266 issue.
It is noted there.
So closing this issue.
