### ISSUE TITLE
अर्द चुरादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#330]
आधृषाद्वा इति गणसूत्रेण णिच् विकल्पः। णिजभावे अर्दति-ते इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
Optional ones are difficult for now.
Keeping it in 'not now' category.
@mrudani 
Can you enumerate the gaNa आधृषात्‌ ?

**Comment by drdhaval2785** [comment]
Pending to handle @akprasad.

**Comment by akprasad** [comment]
@drdhaval2785 see: https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=10.0365

edit: not sure why अर्दते is not appearing -- investigating

**Comment by akprasad** [comment]
@mrudani कथम् "अर्दते"  इति लभ्येत? णिजभावे "शेषात् कर्तरि परस्मैपदम्" इति विधिना "अर्दति" एव लभ्यते, न तु "अर्दते" इति मे भाति।

**Comment by drdhaval2785** [comment]
https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/mA1345.html and https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/XA1399.html

mAdhavIya and dhAtuprakASa seems to agree that there is ardate form as well

**Comment by mrudani** [comment]
अर्द इति चुरादिधातु: स्वरितेत्, तस्मात् आत्मनेपदप्रत्यया: अपि भवन्ति।

**Comment by akprasad** [comment]
अधुना "अर्दते, अर्देते" इत्यादीनि रूपाणि विद्युति दृश्यन्ते 

https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=10.0365
