### ISSUE TITLE
अशँ लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#333]
By aśnoteśca (7.4.72) :

अश्नोतेश्च (७.४.७२) :

1 - आ+नश्+ण

By cuṭū (1.3.7) :

चुटू (१.३.७) :

1 - आ+नश्+ण

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - आ+नश्+अ

By ata upadhāyāḥ (7.2.116) :

अत उपधायाः (७.२.११६) :

1 - आ+नाश्+अ

Final forms are :

आखिरी रूप हैं :

1 - आनाश
------------------------------------
अश्नोतेश्च इति सूत्रम् अशू धातोः विषये न तु अशँ धातोः, तस्मात् तन्न भवेत् आश, आशतुः इति रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
Oh,
This was a new revelation for me.
http://sanskritdocuments.org/learning_tools/ashtadhyayi/vyakhya/7/7.4.72.htm

```
काशिका-वृत्तिः
अश्नोतेश् च ७।४।७२

अश्नोतेश्च दीर्घीभूतादभ्यासादुत्तरस्य नुडागमो भवति। व्यानशे, व्यानशाते, व्यानशिरे। अश्नोतेः इति विकरणनिर्देशः अश्नातेर् मा भूतिति। आश, आशतुः, आशुः। 
```
Therefore doesn't apply in aSnAti.
Only applies in aSnute.
