### ISSUE TITLE
असुँ दिवादिः विधिलिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#337]
By jusi ca (7.3.83) :

जुसि च (७.३.८३) :

1 - अस्+य+ए+उस्

By sārvadhātukamapit (1.2.4) :

सार्वधातुकमपित् (१.२.४) :

1 - अस्+य+ए+उस्

By ato guṇe (6.1.97) :

अतो गुणे (६.१.९७) :

1 - अस्+य्+ए+उस्

By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - अस्येउस्

By eco'yavāyāvaḥ (6.1.78) :

एचोऽयवायावः (६.१.७८) :

1 - अस्ययुस्

By sasajuṣo ruḥ (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - अस्ययुरुँ

By upadeśe'janunāsika it (1.3.2) :

उपदेशेऽजनुनासिक इत् (१.३.२) :

1 - अस्ययुरुँ

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - अस्ययुर्

By kharavasānayorvisarjanīyaḥ (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - अस्ययुः

Final forms are :

आखिरी रूप हैं :

1 - अस्ययुः
-------------------------------------------------
जुसि च इति सूत्रमत्र न प्रवर्तते, यतो हि अचि परे गुणः, यासुटः प्रत्ययावयवत्वात् हलादित्वाच्च नास्य प्रवृत्तिः। अस्येयुः इति स्यात्।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/c1f45d01c14b5de6a72294504cf1f81c94c9dcbb
