### ISSUE TITLE
असुँ लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#338]
By skoḥ saṃyogādyorante ca (8.2.29) :

स्कोः संयोगाद्योरन्ते च (८.२.२९) :

1 - आअथ्+अत्

By āṭaśca (6.1.90) :

आटश्च (६.१.९०) :

1 - आथ्+अत्

By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - आथत्

By jhalāṃ jaśo'nte (8.2.39) :

झलां जशोऽन्ते (८.२.३९) :

1 - आथद्

By vā'vasāne (8.4.56) :

वाऽवसाने (८.४.५६) :

1 - आथद्

2 - आथत्

Final forms are :

आखिरी रूप हैं :

1 - आथद्

2 - आथत्
-----------------------------------------------
स्कोः संयोगाद्योरन्ते च इति सूत्रस्य प्रवृत्तिरत्र न पदान्तत्वाभावात्, झल्परकत्वाभावाच्च। आस्थत्, आस्थताम् इत्यादीनि।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/efca2d678336f4baa41deffc95b018f5c6d538a7
