### ISSUE TITLE
असँ भ्वादिः लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#339]
By ata ādeḥ (7.4.70) :

अत आदेः (७.४.७०) :

1 - आ+अस्+ध्वे

By dhi ca (8.2.25) :

धि च (८.२.२५) :

1 - आ+अ+ध्वे

By ārdhadhātukasyeḍ valādeḥ (7.2.35) :

आर्धधातुकस्येड् वलादेः (७.२.३५) :

1 - आ+अ+इध्वे

By akaḥ savarṇe dīrghaḥ (6.1.101) :

अकः सवर्णे दीर्घः (६.१.१०१) :

1 - आइध्वे

By ādguṇaḥ (6.1.87) :

आद्गुणः (६.१.८७) :

1 - एध्वे

Final forms are :

आखिरी रूप हैं :

1 - एध्वे
---------------------------------------------------
धि च इति प्रवर्तनात् पूर्वम् पूर्वत्वात् इडागमः, कृते च इडागमे धपरत्वाभावात् सलोपो न आसिध्वे इति रूपम्।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/f7924127e0bc8dc1aaebb57697295ab7de042ade
