### ISSUE TITLE
असँ भ्वादिः लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#340]
Final forms are :

आखिरी रूप हैं :

1 - आसिध्वम्
आसिड्ढ्विम् इत्यपि धातुरत्नाकरे वर्तते। एतच्चिन्त्यम्।

**Comment by drdhaval2785** [comment]
Which sUtra would convert 'Dva' to 'Qva' ?

**Comment by drdhaval2785** [comment]
iNaH zIDvam.... seems to be the sUtra.
For the time being we have decided to keep it 'iDvam'. Because the aNga is not iRanta.
