### ISSUE TITLE
असँ अदादिः विधिलिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#343]
By yāsuṭ parasmaipadeṣūdātto ṅicca (3.4.103) :

यासुट् परस्मैपदेषूदात्तो ङिच्च (३.४.१०३) :

1 - अस्+यास्+ताम्

By suṭ tithoḥ (3.4.107) :

सुट् तिथोः (३.४.१०७) :

1 - अस्+यास्+स्ताम्

By liṅaḥ salopo'nantyasya (7.2.79) :

लिङः सलोपोऽनन्त्यस्य (७.२.७९) :

1 - अस्+या+ताम्

By sārvadhātukamapit (1.2.4) :

सार्वधातुकमपित् (१.२.४) :

1 - अस्+या+ताम्

By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - अस्याताम्

Final forms are :

आखिरी रूप हैं :

1 - अस्याताम्
------------------------------------------------
श्नसोरल्लोपः इति अलोपः भवेत्। स्यात्, स्याताम्, स्युः इत्यादीनि रूपाणि।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12256860/122af876-b927-11e5-801e-797189e9e0ef.png)

The code gives the abovementioned output.

श्नसोरल्लोपः can elide only क्ङिति सार्वधातुके.
तिप्सिब्मिपः पित्त्वात्‌ सार्वधातुकमपिदित्यस्यापि प्रवृत्तिर्नास्ति । कथं किति ङिति वा सिध्यते ? कित्त्वङित्त्वाभावे कथं श्नसोरल्लोपस्य प्रवृत्तिः ? अन्यथा तु अस्ति, असि, अस्मि इत्येतेष्वपि श्नसोरल्लोपस्य प्रवृत्तिर्भवितुमर्हति ।

सहजबोधेऽपि किमपि कारणं न दत्तम्‌ । केवलं श्नसोरल्लोपस्य प्रवृत्तिर्दर्शिता ।
पश्यतु ।
![capture](https://cloud.githubusercontent.com/assets/5755132/12256909/91191578-b927-11e5-9da1-cfdcf1941da4.png)

**Comment by mrudani** [comment]
यासुटः ङित्त्वात् श्नसोरल्लोपः इत्यस्य प्रवृत्तिः। यासुट् परस्मैपदेषूदात्तो ङिच्च इति ङित्त्वम् यासुटः।
