### ISSUE TITLE
असँ अदादिः लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#345]
By astisico'pṛkte (7.3.96) :

अस्तिसिचोऽपृक्ते (७.३.९६) :

1 - भू+सिच्+ई+त्

By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - भू+सिच्+ई+त्

By upadeśe'janunāsika it (1.3.2) :

उपदेशेऽजनुनासिक इत् (१.३.२) :

1 - भू+सिच्+ई+त्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - भू+सी+त्

By sici vṛddhiḥ parasmaipadeṣu (7.2.1) :

सिचि वृद्धिः परस्मैपदेषु (७.२.१) :

1 - भौ+सी+त्

By luṅlaṅlṛṅkṣvaḍudāttaḥ (6.4.71) :

लुङ्लङ्लृङ्क्ष्वडुदात्तः (६.४.७१) :

1 - अभौ+सीत्

By ārdhadhātukasyeḍ valādeḥ (7.2.35) :

आर्धधातुकस्येड् वलादेः (७.२.३५) :

1 - अभौ+इसीत्

By neṭi (7.2.4) :

नेटि (७.२.४) :

1 - अभौ+इसीत्

By iṭa īṭi (8.2.28) :

इट ईटि (८.२.२८) :

1 - अभौ+इईत्

By akaḥ savarṇe dīrghaḥ (6.1.101) :

अकः सवर्णे दीर्घः (६.१.१०१) :

1 - अभौ+ईत्

By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - अभौईत्

By eco'yavāyāvaḥ (6.1.78) :

एचोऽयवायावः (६.१.७८) :

1 - अभावीत्

By jhalāṃ jaśo'nte (8.2.39) :

झलां जशोऽन्ते (८.२.३९) :

1 - अभावीद्

By vā'vasāne (8.4.56) :

वाऽवसाने (८.४.५६) :

1 - अभावीद्

2 - अभावीत्

Final forms are :

आखिरी रूप हैं :

1 - अभावीद्

2 - अभावीत्
---------------------------------------------------
सिच् करणात्परं गातिस्थाघुपाभूभ्यः सिचः परस्मैपदेषु इति सिचः लोपः, भूसुवोस्तिङि इति गुणनिषेधः, अभुत्, अभूताम् इत्यादीनि रूपाणि।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12259509/4d7a6000-b93c-11e5-895a-4b69d5f97d7a.png)
