### ISSUE TITLE
आपॢँ चुरादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#346]
आपिपत्, आपिपताम् इत्यादीनि रूपाणि भवेयुः।
आप् णिच् - आपि
अस्मात् लुङि, चङ्, धातोः अजदित्वात् द्वितीयस्य द्वित्वे आपिपत् इत्यादीनि रूपाणि सिध्यन्ति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12260248/d02b0a0a-b940-11e5-8594-321c18905263.png)

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/7a99ec54d805a9d71abc6f0b4989fe5cbcb76b49
