### ISSUE TITLE
इगिँ भ्वादिः लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#348]
इजादेश्च गुरुमतोनृछः इति आम् प्रत्ययः, तेन इगाञ्चकार इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262453/0f361412-b94e-11e5-832f-f632b65b63bf.png)
