### ISSUE TITLE
इगिँ भ्वादिः लृट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#350]
इङ्गिष्यति, इङ्गिष्यतः इङ्गिष्यन्ति इत्यादीनि रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262580/c33eb45a-b94e-11e5-86a2-48beb3ca3586.png)
