### ISSUE TITLE
इगिँ भ्वदिः विधिलिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#352]
इङ्गेत्, इङ्गेताम्, इङ्गेयुः इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262615/f5b1e286-b94e-11e5-8ed3-fe5cdd6737af.png)
