### ISSUE TITLE
इगिँ भ्वादि आशीर्लिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#353]
By jhalāṃ jaśo'nte (8.2.39) :

झलां जशोऽन्ते (८.२.३९) :

1 - याद्

By vā'vasāne (8.4.56) :

वाऽवसाने (८.४.५६) :

1 - याद्

2 - यात्

Final forms are :

आखिरी रूप हैं :

1 - याद्

2 - यात्
------------------------------------------------
इङ्ग्यात्, इङ्ग्यास्ताम्, इङ्ग्यासुः इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262637/140feed0-b94f-11e5-956a-d63eccaa5a06.png)
