### ISSUE TITLE
इगिँ भ्वादिः लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#354]
By vā'vasāne (8.4.56) :

वाऽवसाने (८.४.५६) :

1 - आयीद्

2 - आयीत्

Final forms are :

आखिरी रूप हैं :

1 - आयीद्

2 - आयीत्
------------------------------------------
ऐङ्गीत्, ऐङ्गिष्टाम्, ऐङ्गिषुः इत्यादीनि रूपाणि.

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262657/2ddcfa56-b94f-11e5-9b78-c7e1f48cf1c5.png)
