### ISSUE TITLE
इन्दि भ्वादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#355]
By sārvadhātukārdhadhātukayoḥ (7.3.84) :

सार्वधातुकार्धधातुकयोः (७.३.८४) :

1 - ए+अ+ति

By eco'yavāyāvaḥ (6.1.78) :

एचोऽयवायावः (६.१.७८) :

1 - अय+ति

Final forms are :

आखिरी रूप हैं :

1 - अयति
------------------------------------------
इन्दति, इन्दतः, इन्दन्ति इत्यदीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262691/5efbed22-b94f-11e5-8941-b93e4b64efba.png)
