### ISSUE TITLE
इदिँ भ्वादिः लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#356]
By ekāco dve prathamasya (6.1.1) :

एकाचो द्वे प्रथमस्य (६.१.१) :

1 - इ+इ+ण

By halādiḥ śeṣaḥ (7.4.60) :

हलादिः शेषः (७.४.६०) :

1 - इ+इ+ण

By cuṭū (1.3.7) :

चुटू (१.३.७) :

1 - इ+इ+ण

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - इ+इ+अ

By ṇeraniṭi (6.4.51) :

णेरनिटि (६.४.५१) :

1 - अ

Final forms are :

आखिरी रूप हैं :

1 - अ
-----------------------------------------
इन्दिभवतिभ्यां च इति आम् प्रत्ययः तेन इन्दाञ्चकार, इन्दाञ्चक्रतुः, इन्दाञ्चक्रुः इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
Leave this testing of idi. I will correct them. Go to the next verb

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12262708/78a41254-b94f-11e5-9f00-8f635b4370ec.png)
