### ISSUE TITLE
ञिइन्धीँ रुधादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#357]
Final forms are :

आखिरी रूप हैं :

1 - इन्द्धे
-----------------------------------
झषस्तथोर्धोधः इति तस्य धत्वे 
झरो झरि सवर्णे इति धस्य लोपे च इन्धे इति रूपम्।

**Comment by drdhaval2785** [comment]
Why not झलां जश्‌ झशि (८.४.५३)?

It comes before झरो झरि सवर्णे (८.४.६५).
There seems to be some discrepencies in dhAtuvRttis.

`माधवीयधातुवृत्तिः`
उदात्तोऽनुदात्तेत् (__इन्धे__ इन्धाते इन्त्से इन्धे ) "श्नान्नलोपः" इति श्नात्परस्य प्रकृतेर्नकारस्य लोपः किङ्तोः "इन्धिभवतिभ्यां च" इति इन्धेः परस्य लिटः कित्त्वविधानसामर्थ्यादामो विकल्पमिच्छन्ति तदिन्धेश्छन्धो विषयत्वाद्भुवो वुको नित्यत्वादित्यादि भाष्यवार्तिकविरोधादुपेक्ष्यम् (इन्धिता इन्धिष्यते इन्धाम् इन्धाताम् इन्धताम् न इन्त्स्व इनधै ऐन्ध ऐन्धाताम् ऐन्धत ऐन्धाः ऐन्धि इन्धीत इन्धोयाताम् )

**Comment by mrudani** [comment]
कृतेपि जश्त्वे, लोपप्रवृत्तिः झरो झरि सवर्णे इति सूत्रेण। अत्र सवर्णो नाम स एव वर्णः भवेदिति नास्तिनियमः, सवर्णः भवेत्, तेन लोपः भवत्येव।

**Comment by drdhaval2785** [comment]
OK.
kAzikA says
`सवर्णग्रहणसामर्थ्यातिह सङ्ख्यातानुदेशो न भवति, सवर्णमात्रे लोपो विज्ञायते। तेन शिण्ढि, पिण्ढि इति ढकारे डकारस्य लोपो भवति`

Therefore, the logic of mrudani is fine.
I agree with it.

jharo jhari savarNe code is corrected now.
