### ISSUE TITLE
ञिइन्धीँ लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#358]
By ṇeraniṭi (6.4.51) :

णेरनिटि (६.४.५१) :

1 - निन्ध्+ए

By naścāpadāntasya jhali (8.3.24) :

नश्चापदान्तस्य झलि (८.३.२४) :

1 - निंधे

By anusvārasya yayi parasavarṇaḥ (8.4.58) :

अनुस्वारस्य ययि परसवर्णः (८.४.५८) :

1 - निन्धे

Final forms are :

आखिरी रूप हैं :

1 - निन्धे

----------------------------------------
इजादेश्च गुरुमतो अनृच्छः इति आम्प्रत्ययः भवेत्। इन्धाञ्चक्रे इत्यादीनि रूपाणि सिध्यन्ति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12265481/3fba54e4-b963-11e5-8bb8-3859a49cef04.png)
