### ISSUE TITLE
अक्षूँ व्याप्तौ - लिट्‌ 

### ISSUE THREAD

**Issue by raghubhaijoshi** [drdhaval2785/SanskritVerb#359]
आक्व, आकिव 	आक्म, आकिम इति रूपाणि भवन्ति ।
आनक्ष्व, आक्षिव, आनक्ष्म, आक्षिम इति भवेयुः ।

हलन्त्यमित्यस्य प्रवृत्तिर्नास्ति ।

**Comment by drdhaval2785** [comment]
Closed.
It is a duplicate.
