### ISSUE TITLE
इष् तुदादिः लुट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#362]
Final forms are :

आखिरी रूप हैं :

1 - एषिता
-------------------------------
तीषसहलुभरुषरिषः इति इटः विकल्पे एष्टा इति भवति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12357347/5d7458ba-bbcd-11e5-8160-bfe4a534d0c2.png)
