### ISSUE TITLE
इषँ तुदादिः विधिलिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#363]
By pugantalaghūpadhasya ca (7.3.86) :

पुगन्तलघूपधस्य च (७.३.८६) :

1 - इच्छ्+अ+एय्+अम्

By ato guṇe (6.1.97) :

अतो गुणे (६.१.९७) :

1 - इच्छ्+एय्+अम्
----------------------------------------------------
अत्र पुगन्तलघूपधस्य च इति सूत्रेण गुणः न अत्र। अकार-इकारयोः गुणः भवति।

**Comment by drdhaval2785** [comment]
#360 closed this also.
