### ISSUE TITLE
इषँ दिवादिः लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#364]
By iṣugamiyamāṃ chaḥ (7.3.77) :

इषुगमियमां छः (७.३.७७) :

1 - इछ्+श्यन्+तिप्

By tiṅśitsārvadhātukam (3.4.113) :

तिङ्शित्सार्वधातुकम् (३.४.११३) :

1 - इछ्+श्यन्+तिप्

By laśakvataddhite (1.3.8) :

लशक्वतद्धिते (१.३.८) :

1 - इछ्+श्यन्+तिप्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - इछ्+यन्+तिप्

By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - इछ्+यन्+तिप्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - इछ्+य+ति

By che ca (6.1.73) :

छे च (६.१.७३) :

1 - इत्छ्+य+ति

By stoḥ ścunā ścuḥ (8.4.40) :

स्तोः श्चुना श्चुः (८.४.४०) :

1 - इच्छ्+य+ति

By sārvadhātukamapit (1.2.4) :

सार्वधातुकमपित् (१.२.४) :

1 - इच्छ्+य+ति

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - इच्छ्यति

Final forms are :

आखिरी रूप हैं :

1 - इच्छ्यति
----------------------------------------------------
इषुगमियमां छः इति सूत्रेण विधीयमानः छादेशः उदित्सु एव इति काशिकाकारः। तेनात्र न भवति।

**Comment by mrudani** [comment]
लोट्लकारोपि द्रष्टव्यः अस्मिन् प्रसंगे।

**Comment by drdhaval2785** [comment]
लट्‌
![capture](https://cloud.githubusercontent.com/assets/5755132/12357577/97afb67c-bbce-11e5-872d-b76f0714bd81.png)
लोट्‌
![capture](https://cloud.githubusercontent.com/assets/5755132/12357598/b71522f4-bbce-11e5-9c7f-ef6e45d61ef1.png)
लङ्‌
![capture](https://cloud.githubusercontent.com/assets/5755132/12357609/dbd515cc-bbce-11e5-9a79-a73e091e93df.png)
विधिलिङ्‌
![capture](https://cloud.githubusercontent.com/assets/5755132/12357627/fff3b85a-bbce-11e5-9e1b-166454be9f47.png)
