### ISSUE TITLE
इषँ दिवादिः लुट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#366]
By tīṣasahalubharuṣariṣaḥ (7.2.48) :

तीषसहलुभरुषरिषः (७.२.४८) :

1 - एष्+ता

2 - एष्+इता

By ṣṭunā ṣṭuḥ (8.4.41) :

ष्टुना ष्टुः (८.४.४१) :

1 - एष्टा

2 - एषिता

By na padāntāṭṭoranām (8.4.42) :

न पदान्ताट्टोरनाम् (८.४.४२) :

1 - एष्टा

2 - एषिता

By toḥ ṣi (8.4.43) :

तोः षि (८.४.४३) :

1 - एष्टा

2 - एषिता

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - एष्टा

2 - एषिता

Final forms are :

आखिरी रूप हैं :

1 - एष्टा

2 - एषिता
--------------------------------------------------------------
इषु इच्छायाम् इत्यस्य अयं विकल्प इष्यते। यस् तु इष गतौ इति दैवादिकः, तस्य प्रेषिता, प्रेषितुम्, प्रेषितव्यम् इति  नित्यं भवति इति काशिका। तेन एषिता इत्येव स्यात्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12357682/5ba63c0e-bbcf-11e5-9802-5800201d53e4.png)

#362 closed this too.
