### ISSUE TITLE
इषँ क्र्यादिः लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#375]
Final forms are :

आखिरी रूप हैं :

1 - एष
------------------------------------------------
इयेष, ईषतुः इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12378320/f028f948-bd5f-11e5-8ba4-bcd2364fc240.png)

There are errors in the tas, Ji etc forms.
ईषतुः, ईषुः are expected.

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/12378323/1899c7cc-bd60-11e5-96bc-e7692db2f0f3.png)

Corrected now.
Check out for errors.
