### ISSUE TITLE
सम्+वि॑दँ॑ - ज्ञाने, अदादि 02.0067

### ISSUE THREAD

**Issue by sowmyakrishnapur** [drdhaval2785/SanskritVerb#377]
The forms should be aatmanepadin forms, as the vid dhaatu, when preceded by sam, gets aatamepada suffixes by the rule 1-3-29

Also, when this query is submitted, the page displays jā॑gṛ॑ - nidrākṣaye, adādi 02.0067. Maybe some problem with numbering the dhaatus?
![capture15](https://cloud.githubusercontent.com/assets/15191034/12373112/9fcdcc42-bc94-11e5-8e06-172fd31a43ab.PNG)

**Comment by drdhaval2785** [comment]
@sowmyakrishnapur 
Thank you very much for your precious feedback, ma'am.
Now it is corrected.
Please see below.

We look forward to hear more such issues from you and your students.

![capture](https://cloud.githubusercontent.com/assets/5755132/12378058/3e0d3a5a-bd58-11e5-9f9d-9c04acd25a99.png)
