### ISSUE TITLE
ऋ॑ - हिंसायाम् इत्येके, स्वादि 05.0038

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#388]
@mrudani 
There is an entry in our database having
![capture](https://cloud.githubusercontent.com/assets/5755132/12413830/950205c4-beb7-11e5-97c4-26229fd40585.png)

Is there such a dhAtu ?

If yes, what would be its forms like ?

**Comment by drdhaval2785** [comment]
Not in mAdhavIyadhAtuvRtti or any other vRtti.
But found in dhAtupATha with svara.
See
![capture](https://cloud.githubusercontent.com/assets/5755132/12535826/56bdea82-c2b6-11e5-830d-d80889efc91c.png)

**Comment by mrudani** [comment]
मयाप्यन्विष्टे सति न लब्धः। किं कुर्याव।

**Comment by drdhaval2785** [comment]
We close it as of now.
If any substantial issue arises, we will dig deeper.
