### ISSUE TITLE
कृपँ॑ - अवकल्कने मिश्रीकरण इत्येके चिन्तन इत्यन्ये, चुरादि, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#404]
Test whether the following forms are correct or not
![capture](https://cloud.githubusercontent.com/assets/5755132/12528459/47c2df38-c1bc-11e5-8a9f-f465fffa16a4.png)

**Comment by drdhaval2785** [comment]
अचीक्लृपत्‌ seems more plausible.
But the process still remains unclear to me.

**Comment by mrudani** [comment]
अ कृप् इ अ त्
अत्र पुगन्तलघूपधस्य च इति गुणे कर्तव्ये तं प्रबाध्य उर्ऋत् इति ऋकारे
अ कृप् इ अ त्
णिचः लोपे - अ कृप् अ त्
धातोः द्वित्वे - अ कृप् कृप् अ त्
हलादिशेषे - अ कृ कृप् अ त्
उरत् इति अभ्यास-ऋकारस्य अकारादेशे रपरत्वे च 
अ कर् कृप् अ त्
हलादिशेषे, चर्त्वे च - अ च कृप् अ त्
सन्वद्भावे, सन्यतः इति अभ्यासस्य इत्वे, दीर्घो लघोः इति दीर्घे च - अ ची कृप् अ त्
कृपो रो लः इति लृकारादेशे - अचीक्लृपत्
......................................................................................
उर्ऋत् इत्यस्य विकल्पत्वात् तदभावे 
कृपो रो लः इति लृत्वे गुणे च कृते - अ कल्प् इ अ त्
णिलोपे, द्वित्वे, चर्त्वे, हलादिशेषे च - अ च कल्प् अ त्
अचकल्पत् इति सिध्यति
-------------------------------------------------------
अचीक्लृपत् इत्यत्र अर्ऋत् इत्यनेन ऋत्वकरणात्प्रं ऋकारस्य लृत्वे कृते
अ क्लृप् इ अ त् इति भवति, तस्मादपि अचीक्लृपत् इति साधितुं शक्यते। 
टंकने स्वरवर्णस्याभावात् लृ इति टंक्यते, क्षन्तव्या।

**Comment by drdhaval2785** [comment]
Right now keeping only अचीक्लृपत्‌.
Not kept अचकल्पत्‌.
Alternate forms give some trouble in luG lakAra.
So leaving it as of now.
The question is majorly solved.
