### ISSUE TITLE
कृ॒षँ॒॑ - विलेखने, तुदादि, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#406]
Test whether the following forms are correct or not. I suspect some are not.

![capture](https://cloud.githubusercontent.com/assets/5755132/12528522/eb6f05ec-c1be-11e5-80e4-fe8509854c42.png)

**Comment by mrudani** [comment]
लुङ् लकारे कथमेवं भवेयुः रूपाणि। लृट् लकारस्य रूपाणि इमानि। अमागमः भवति, अनुदात्तस्य... इत्यादिना सूत्रेण
