### ISSUE TITLE
कॄ॑ - विक्षेपे निक्षेपे, तुदादि, लुट्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#407]
The machine applied ॠतो इद्धातोः and gives the following forms.
![capture](https://cloud.githubusercontent.com/assets/5755132/12528544/18c16a16-c1c0-11e5-84bb-f2d06a26c5e4.png)

Actually ऋच्छत्यृऋताम् ७।४।११ is परसूत्रः than ॠत इद्धातोः ७.१.१००, so it will apply and give करिता, करितारौ etc.

**Comment by drdhaval2785** [comment]
All forms of kF needs this examination.

**Comment by mrudani** [comment]
ऋच्छत्यृताम् इति सूत्रं तु लिट्लकारे खलु, न तु लुटि. 
अत्र सार्वधातुकार्धधातुकयोः इति सूत्रेण गुणः भवेत्।

**Comment by mrudani** [comment]
यन्त्रेणापि तथैव दीयते। परिष्कृतो वा।
