### ISSUE TITLE
ख्या॒ - प्रकथने, अदादि, लङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#420]
अख्योड्-(ख्या,लङ्,झि,अदादि,०२।००५५)
अख्योट्-(ख्या,लङ्,झि,अदादि,०२।००५५)

**Comment by raghubhaijoshi** [comment]
अखु : , अख्यान् भवति ‌। लङलङःशाटकायनस्यैव इत्यनेन झेर्ज़ुस्

**Comment by drdhaval2785** [comment]
@raghubhaijoshi I like that you are getting used to commenting on github.
One day I want to see your correction submission on github.
