### ISSUE TITLE
गा॒ - स्तुतौ, जुहोत्यादि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#423]
Non application of कुहोश्चुः
gives wrong forms like 
गिगाति etc.

**Comment by raghubhaijoshi** [comment]
Closed  mins problem  sol हो गया ?

**Comment by drdhaval2785** [comment]
Yes. It is solved. It may take some time before the corrected version is
uploaded on website. This is usually done once a week.
