### ISSUE TITLE
भू सत्तायाम्, भ्वादिः आशीर्लिङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#430]
By udupadhādbhāvādikarmaṇoranyatarasyām (1.2.21) :

उदुपधाद्भावादिकर्मणोरन्यतरस्याम् (१.२.२१) :

1 - भू+यास्+स्
----------------------------------------------
अस्य सूत्रस्य प्रसक्तिरेव नास्ति।

**Comment by drdhaval2785** [comment]
It was misspelling for 1.2.41 (apRkta ekAl hal)
