### ISSUE TITLE
भू सत्तायाम्, भ्वादिः आशीर्लिङ् सिप्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#431]
By halṅyābbhyo dīrghāt sutisyapṛktaṃ hal (6.1.68) :
 
हल्ङ्याब्भ्यो दीर्घात्‌ सुतिस्यपृक्तं हल् (६.१.६८) :

1 - भू+यास्
------------------------------------------------
अत्र हल्ङ्याभ्यो इति सूत्रं न प्रवर्तते। भू यास् स् इत्यवस्थायां 
स्कोः संयोगाद्योरन्ते च इति प्रथमसकारस्य लोपः
भू या स् 
सस्य रुत्वे विसर्गे च
भूयाः इति सिध्यति।
यासुडागमस्य प्रत्ययावयवत्वात्, अपृक्तात्वाभावाच्च नात्र हल्ङ्याभ्यप्रवृत्तिरिति।

**Comment by drdhaval2785** [comment]
संयोगान्तस्य लोपः इत्यनेन न भवति ?
पूर्वत्रासिद्धत्वात्‌ ?
हल्‌... इत्यस्य प्रवृत्तिर्नास्ति । परन्तु संयोगान्तस्य लोपः वा स्कोः संयोगाद्योरन्ते च इत्यनयोः मध्ये कस्य प्रवृत्तिरिति मे आशङ्का ।
@mrudani

**Comment by mrudani** [comment]
उक्तमेव खलु, स्कोः संयोगाद्योरन्ते च इति सूत्रेण लोपः इति।

**Comment by drdhaval2785** [comment]
कथं संयोगान्तलोपं बाधित्वा स्कोः संयोगाद्योरन्ते च इत्यस्य प्रवृत्तिरित्येव प्रश्नः भगिनि !

**Comment by mrudani** [comment]
विशेषविधानात्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/15279369/348cf17c-1b41-11e6-8fb4-b195c51fd9cc.png)
Already corrected.
