### ISSUE TITLE
भू सत्तायाम् लुङ् ताम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#432]
By bhūsuvostiṅi (7.3.88) :

भूसुवोस्तिङि (७.३.८८) :

1 - भू+ताम्
----------------------------------------------
अत्र तसः अपित्त्वात् सार्वधातुकमपित् इति सूत्रेण ङित्त्वातिदेशे क्ङिति च इति गुणनिषेधः स्यात्।

**Comment by mrudani** [comment]
By bhūsuvostiṅi (7.3.88) :

भूसुवोस्तिङि (७.३.८८) :

1 - भू+तम्
-------------------------------------------
By bhūsuvostiṅi (7.3.88) :

भूसुवोस्तिङि (७.३.८८) :

1 - भू+त
---------------------------------------------
By bhūsuvostiṅi (7.3.88) :

भूसुवोस्तिङि (७.३.८८) :

1 - भू+व
----------------------------------------------
By bhūsuvostiṅi (7.3.88) :

भूसुवोस्तिङि (७.३.८८) :

1 - भू+म

**Comment by drdhaval2785** [comment]
सार्वधातुकत्वं कथं सिद्धम्‌ ?
अत्र तु आर्धधातुकं शेष इत्यस्य प्रवृत्तिर्ननु ।

**Comment by mrudani** [comment]
भू धातोः तिङ्परकत्वात्, तिङ्शित् सार्वधातुकम् इति सूत्रेण सार्वधातुकसंज्ञा भवति।

**Comment by drdhaval2785** [comment]
Crux of a long discussion on whatsapp
So let us sum up the discussion so far
1. भूसुवोस्तिङि - पिति anuvRtti is there. In that case तस्‌ would not have pittva and it would not apply. Only क्ङिति च is applicable. There are at least two commentaries which have पिति anuvRtti i.e. prakAza and prathamAvRtti. Also prakriyAkaumudi has specifically used क्ङिति च for derivation of अभूताम्‌. Also the next six rules have anuvRtti of पिति. So, it is highly probable that there is an anuvRtti of पिति here.
2. Second case is no anuvRtti of पिति. kAzikA / SK, rather no grammar text says that there is such an anuvRtti other than two mentioned above. So we don't have very authentic proof of anuvRtti. Nevertheless, none gives examples which are अपित्‌. Maybe we can take this as ज्ञापकम्‌ ?

**Comment by drdhaval2785** [comment]
I personally lean towards acceptin पिति anuvRtti here. Still not many authentic pramANas come in.

**Comment by mrudani** [comment]
अत्र इदमपि वक्तुं शक्यते, अपित्सु स्वतः एव क्ङिति च इति गुणनिषेधे सिद्धे तदर्थमिदमिति न स्यात्।
