### ISSUE TITLE
भू सत्तायाम् लुङ् झि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#433]
By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - अभूवन्
---------------------------------------------
अत्र हलन्त्यमित्यस्य प्रवृत्तिरेव नास्ति, उपदेशे अन्त्यत्वाभावात् नकारस्य, तस्मात् तन्निषेधस्याप्यप्रवृत्तिरिति मे मतिः।

**Comment by drdhaval2785** [comment]
Good observation.
Let me see what can be done in this matter.

**Comment by drdhaval2785** [comment]
Issue is closed now.
