### ISSUE TITLE
अदँ भक्षणे, अदादिः, लट्, सिप्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#434]
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्सि

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्सि
--------------------------------------------------------
खरि च इति सूत्रस्य द्विरुपयोगः दृश्यते।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/e93daf852335165ff105f17982e45221e040179d
