### ISSUE TITLE
अदँ भक्षणे, अदादिः, लिट्, उस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#438]
By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - जघसुस्

By sasajuṣo ruḥ (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - जघसुरुँ

By upadeśe'janunāsika it (1.3.2) :

उपदेशेऽजनुनासिक इत् (१.३.२) :

1 - जघसुरुँ

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - जघसुर्

By kharavasānayorvisarjanīyaḥ (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - जघसुः

Final forms are :

आखिरी रूप हैं :

1 - जघसुः
------------------------------------------------
गमहनजन... इत्यादिना उपधायाः लोपे, सस्य षत्वादेशे, चर्त्वे च कृते
जक्षुः इति भवेत्।

**Comment by drdhaval2785** [comment]
Closed via the same commit as #437
