### ISSUE TITLE
अदँ भक्षणे, अदादिः, लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#439]
जक्षतुः, जक्षुः
जक्षिव, जक्षिम इत्येवं प्रकारेण रूपाणि भवेयुः।
## अत्र सर्वत्रापि उपधालोपः भवेत्।

लिट्यन्यतरस्याम् इति सूत्रेण अद्-धातोः विकल्पेन घस्लृ-आदेशात् तदभावे 
आद आदतुः, आदुः
आदिथ, आदथुः, आद
आद, आदिव, आदिम इति रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
I know that right now we are keeping only Gasx! AdeSa and not showing 'ad' forms.
Not possible right now. Will keep on hold.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0001 handles this.
