### ISSUE TITLE
अदँ भक्षणे, अदादिः, लृट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#441]
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यति

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यति
----------------------------------------------------------
खरि च इति द्विः वर्तते। अनपेक्षितम्। 
अत्रापि एकाच उपदेशेनुदात्तात् इति इन्निषेधः दर्शनीयः।

**Comment by mrudani** [comment]
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यतः

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यतः
---------------------------------------------------
अत्रापि तथैव द्विः वर्तते।

**Comment by mrudani** [comment]
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यसि

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यसि

**Comment by mrudani** [comment]
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यथः

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यथः

**Comment by mrudani** [comment]
By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - अद्+थ

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - अद्+थ
-----------------------------------------
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यथ

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्स्यथ
--------------------------------------------
हलन्त्यमिति अनावश्यकम्, खरि च इति द्विः प्रयुक्तम्।

**Comment by drdhaval2785** [comment]
Closed earlier.
