### ISSUE TITLE
अदँ भक्षणे लोट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#442]
By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - अद्+तिप्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - अद्+ति
----------------------------------------------------
By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्तु

2 - अत्ताद्

3 - अत्तात्

By khari ca (8.4.55) :

खरि च (८.४.५५) :

1 - अत्तु

2 - अत्ताद्

3 - अत्तात्
---------------------------------------------------
1. प्रथमे हलन्त्यस्य अनावश्यकमुपयोगः। 
2. द्वितीये खरि च इत्यस्य द्विः दर्शनम्।

**Comment by mrudani** [comment]
लोट्-लकाररूपेषु सर्वत्र हलन्त्यम्,तस्य लोपः,  खरि च इति सूत्राणामावृत्तिः दृश्यते, तद्वार्यम्।

**Comment by drdhaval2785** [comment]
तिपः पकारास्य लोपाय हलन्त्यम् च तस्य लोपस्य प्रवृत्तिरनिवार्यैव ।
अत्तु इति स्थितौ प्रथमतकारस्तकारस्य झलन्तर्भावाद्द्वितीयतकारस्य
खरन्तर्भावाच्च खरि च इत्यस्य प्रवृत्तिरप्यनिवार्या । प्रथमतकारस्य तकार एव
आदेशः । पर्जन्यवल्लक्षणप्रवृत्तिरिति परिभाषाबलेन रूपविकाराभावेऽपि
प्रवृत्तिरनिवार्या ।

**Comment by mrudani** [comment]
By na vibhaktau tusmāḥ (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - अद्+तस्

By halantyam (1.3.3) :

हलन्त्यम् (१.३.३) :

1 - अद्+तस्

By tasya lopaḥ (1.3.9) :

तस्य लोपः (१.३.९) :

1 - अद्+तस्
------------------------------------------------
सत्यम्, प्रथमे युज्येत परमत्र तु न शक्यते खलु, इदमुदाहरणीये तदुक्तम्मया, क्षन्तव्या।

**Comment by mrudani** [comment]
द्वितीये -
अद् तात्, ताम्
अत्र तु खर्-परकः एक एव झल्वर्णः वर्तते ननु कथं द्विः प्रयोगः।
तथा च प्रक्रियाप्रदर्शने खरि च सूत्रोपरि नोदनेन वावसाने इत्यस्य वृत्तिरायाति संख्याभेदात्, तदपि द्रष्टव्यम्।

**Comment by drdhaval2785** [comment]
द्विःप्रयोगः न भवितुमर्हति ।
सम्यक्कृता प्रक्रियाधुना ।
