### ISSUE TITLE
ई॑शँ॒ - ऐश्वर्ये, अदादि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#462]
The machine gives the following forms.
```
Izze-(ISa!,law,sip,02.0010)
Izzva-(ISa!,low,sip,02.0010)
```
Whereas the UoHyd machine gives इशिषे इशिष्व etc.
How to bring in the iDAgama ?

**Comment by mrudani** [comment]
ईशिषे इति लटि, ईशिष्व इति लोटि च।
अत्र ईशः से इति सूत्रेण इट् आगमः विधीयते। ईश् धातोः सावर्धातुके से परे इडागमो भवति।
