### ISSUE TITLE
ज्यु॑तिँ॑र् - भासने, भ्वादि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#507]
Is there such a verb ?
The dhAtupATha says जुतृँ at the same location.

**Comment by mrudani** [comment]
ज्युतिर् इति न लब्धं धातुपाठान्तरेषु।

**Comment by drdhaval2785** [comment]
There is no such dhAtu is what I am deciding.
If there is opposite proof, I will reopen it.
