### ISSUE TITLE
दि॑वुँ॑ - क्रीडाविजिगीषाव्यवहारद्युतिस्तुतिमोदमदस्वप्नकान्तिगतिषु, दिवादि ०४.०२४९ , लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#518]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+ति

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यति
-------------------------------------------------
हलि च सूत्रस्य आवृत्तिः वारणीया।

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+थ

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यथ

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+मि

By ato dīrgho yañi (7.3.101) :

अतो दीर्घो यञि (७.३.१०१) :

1 - दीव्+या+मि

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यामि

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+वस्
--------------------------------------
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यावर्

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+मस्
------------------------------------
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यामर्

**Comment by drdhaval2785** [comment]
Why it should be stopped?

माधवीयधातिवृत्तौ तु -

( अक्षैर्दीव्यति, अक्षान् दीव्यति, दीव्यतः दीव्यन्ति दीव्यामि)
"दिवादिभ्यश्श्यन्'' इति श्यन् शपो ऽपवादः "हलि च'' इतीको दीर्घः

**Comment by drdhaval2785** [comment]
Oh. Ok. You wanted to prevent repetition. I misunderstood.
