### ISSUE TITLE
दिवुँ, दिवादिः, लोट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#520]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+तु

2 - दीव्+य+तात्

By jhalāṃ jaśo'nte (8.2.39) :

झलां जशोऽन्ते (८.२.३९) :

1 - दीव्यतु

2 - दीव्यताद्

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यतु

2 - दीव्यताद्
---------------------------------------------
हलि च सूत्रस्यावृत्तिः।

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+अन्तु

By ato guṇe (6.1.97) :

अतो गुणे (६.१.९७) :

1 - दीव्+य्+अन्तु

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यन्तु

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+हि

2 - दीव्+य+तात्

By ato heḥ (6.4.105) :

अतो हेः (६.४.१०५) :

1 - दीव्+य

2 - दीव्+य+तात्

By jhalāṃ jaśo'nte (8.2.39) :

झलां जशोऽन्ते (८.२.३९) :

1 - दीव्य

2 - दीव्यताद्

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्य

2 - दीव्यताद्

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+तम्

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यतम्

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+आनि

By akaḥ savarṇe dīrghaḥ (6.1.101) :

अकः सवर्णे दीर्घः (६.१.१०१) :

1 - दीव्यानि

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्यानि

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+आव

By akaḥ savarṇe dīrghaḥ (6.1.101) :

अकः सवर्णे दीर्घः (६.१.१०१) :

1 - दीव्याव

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्याव

**Comment by mrudani** [comment]
By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्+य+आम

By akaḥ savarṇe dīrghaḥ (6.1.101) :

अकः सवर्णे दीर्घः (६.१.१०१) :

1 - दीव्याम

By hali ca (8.2.77) :

हलि च (८.२.७७) :

1 - दीव्याम

**Comment by drdhaval2785** [comment]
I got the issue of repetition of hali ca. You dont need to repeat it. I
will correct it.
