### ISSUE TITLE
हु, जुहोत्यादिः लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#525]
हु लिट्
अत्र भीह्रीभृहुवां श्लुवच्च इति सूत्रेण विकल्पेन आम् प्रत्यये  
हु आम् लिट्
हु लिट्
धातोः द्वित्वे, अभ्यासकार्ये च कृते
जुहु आम् लिट्
जुहु लिट्
कृञ्चानुप्रयुज्यते लिटि इति कृञः अनुप्रयोगे 
जुहु आम् कृ लिट्
जुहु लिट्
सम्प्रति लिटः स्थाने तिबादयः, तेषां स्थाने णलादीनामादेशे
जुहुवाञ्चकार
जुहाव इति भवतः।

**Comment by drdhaval2785** [comment]
I won't be able to treat optional forms at this time.
I have kept 'Am' as mandatory as of now.
Will do the optional forms later.
