### ISSUE TITLE
हु, जुहोत्यादिः, लृङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#536]
By dadātidadhātyorvibhāṣā (3.1.139) :

ददातिदधात्योर्विभाषा (३.१.१३९) :

1 - हु+लृङ्
---------------------------------------
इदं सूत्रमत्र किमर्थम्।

**Comment by drdhaval2785** [comment]
It was a missplelling for 3.3.139
Corrected now.
