### ISSUE TITLE
डुक्रीञ् , क्र्यादिः लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#539]
By svaritañitaḥ kartrabhiprāye kriyāphale (1.3.72) :

स्वरितञितः कर्त्रभिप्राये क्रियाफले (१.३.७२) :

लट् लकार
## डुक्रीञ् + तिप् Go Back

अदं सूत्रमात्मनेपदविधायकं खलु, तस्मात् आत्मनेपरूपानामारम्भे स्यात्।

**Comment by akprasad** [comment]
[विद्युति विद्यते](https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=09.0001) @drdhaval2785
