### ISSUE TITLE
रुधिर्. रुधादिः, लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#540]
By upadeśe'janunāsika it (1.3.2) :

उपदेशेऽजनुनासिक इत् (१.३.२) :

1 - रुध्+तिप्
-----------------------------------------
अत्र कथं उपदेशेजनुनासिक इति सूत्रस्य प्रवृत्तिः।

**Comment by drdhaval2785** [comment]
रुधिँर्‌ इत्यवस्थायां हलन्त्यमित्यनेन रेफस्य उपदेशेऽजनुनासिक इदित्यनेन इकारस्य इत्संज्ञा भवति । तस्मादस्य प्रवृत्तिरिति मे मतिः ।
अन्यथा इरः इत्करणे किञ्चित्करणीयम्‌ ।

**Comment by mrudani** [comment]
इर इत्संज्ञा वाच्या इति वार्तिकेन इरः इत्संज्ञा भवति, इरितां प्रयोजनं तु इरितो वा इति सूत्रेण लुङ् लकारे भवति। यदि इदित् भवति तर्हि नुमागमः कार्यः इति क्लेशः।

**Comment by drdhaval2785** [comment]
OK. Got it.
