### ISSUE TITLE
Make dhAtu commentaries available offline

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#578]
http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/compare_with_svara.html
This site has three major dhAtu commentaries online.
Try to incorporate and link these commentaries to dhAtus in our display, so that the user may access these resources offline.

**Comment by drdhaval2785** [comment]
Thanks to Amba madam's very quick response, I now have an archive of the said commentaries in tar.gz format (Which gets automatically decompressed while installation).
https://github.com/drdhaval2785/SanskritVerb/blob/master/Data/dhaatupatha.tgz is the file under question.
Now the issue which remains is about tagging the specific verb to the correct link.

**Comment by Shalu411** [comment]
Namaste
What to open the tgz extension file with in Windows? 
This fellow says- use "7zip". Is that the way?
https://www.youtube.com/watch?v=bewYEHjcSkM

**Comment by drdhaval2785** [comment]
I guess 7-zip would do.

**Comment by funderburkjim** [comment]
I have used 7-zip  for many years, and highly recommend it.

**Comment by drdhaval2785** [comment]
The best thing you can do is to download git. That would give you at least
half of linux tools in widows setup like tar, gzip etc. You can run shell
scripts too.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/releases/tag/v1.6.0 is the release which has incorporated this task.
Right now majority verbs are linked and random search says that the linkage is quite reasonable. 
The criteria used were `verb_with_anubandha` and `gaNa` should match, for the commentary to be linked. I found these to be decent enough criteria to reduce false positives.
