### ISSUE TITLE
रुधिर्, रुधादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#597]
अस्मिन् धातौ इकारस्य अनुनासिकत्वमनपेक्षितं, तस्य इत्सज्ञात्वाभावात्।

**Comment by drdhaval2785** [comment]
तत्र अनुनासिकत्वं लकारस्य प्रदर्शितं न तु धातोः । धातोः कृते इरः उपसङ्ख्यानमिति वार्तिकं दर्शितम्‌ ।
