### ISSUE TITLE
ग्लै॒ - हर्षक्षये मित् अनुपसर्गाद्वा, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#629]
Check the forms in our machine

![capture](https://cloud.githubusercontent.com/assets/5755132/13377980/6b5ea336-de19-11e5-8088-11cb146ad50d.png)

vs
HCU machine
![capture](https://cloud.githubusercontent.com/assets/5755132/13377983/86eadfb6-de19-11e5-8669-8f8ff091889a.png)

**Comment by mrudani** [comment]
ग्लै धातोः आर्धधातुके परे आत्वविधानात्, यमरमनमातां सक् च इति इडागमः सगागमश्च भवति तेन अग्लासीत्, अग्लासिष्टाम्, अग्लासिषुः इत्यादीनि रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
The issue was that I had kept it applicable to only verbs ending with 'A', but here the verb originally ended with 'E'. Now corrected.
