### ISSUE TITLE
मृ॒ङ् - प्राणत्यागे, तुदादि 

### ISSUE THREAD

**Issue by raghubhaijoshi** [drdhaval2785/SanskritVerb#664]
मृ॒ङ् - प्राणत्यागे, तुदादि अत्र ङित्त्वात् मन्ये आत्मनेपदिनः प्रत्ययाः भवन्ति । यन्त्रे  परस्मैपदं विद्यते ।

**Comment by drdhaval2785** [comment]
म्रियतेर्लुङ्‌लिङोश्च॥ १।३।६१
अनेन आत्मनेपदे प्राप्ते लुङि लिङि एव आत्मनेपदमिति नियमः क्रियते इति मे मतिः
।

**Comment by raghubhaijoshi** [comment]
म्रियतेर्लुङ्‌लिङोश्च॥ १।३।६१
अनेन लुङि, लिङि ,शिति च परे आत्मनेपदम्  भवति । अतः लटि म्रियते तद्वद् शिति परे सर्वत्र

**Comment by drdhaval2785** [comment]
आम्‌ । शिति परे अपि आत्मनेपदमिति नावगतवान्‌ तदा । तथा करिष्यामि ।
