### ISSUE TITLE
सामान्या णिच्प्रक्रिया

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#673]
भू णिच्
चुटू इति णस्य इत्संज्ञायाम्,
हलन्त्यम् इति चकारस्य इत्संज्ञायाम्, 
तस्य लोपः इति उभयोर्लोपे - भू इ 
अचो ञ्णिति इति वृद्धौ - भौ इ
एचोयवायावः इति अावादेशे - भाव् इ - भावि
सनाद्यन्ताः धातवः इति धातुसंज्ञायाम्
लडादयः प्रवर्तन्ते।

**Comment by mrudani** [comment]
णिचश्च इति आत्मनेपदविधाययकं शास्त्रम्। तस्मात् आत्मनेपदप्रक्रियायाः आरम्भे तद्भवेत्।

**Comment by drdhaval2785** [comment]
All lakAras except luN and liw are getting this now.
These two will require some time.

**Comment by drdhaval2785** [comment]
Now 'luN' and 'liw' are closed.
