### ISSUE TITLE
भू णिच् लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#674]
भू णिच् लुङ्
भू इ लुङ्
प्रथमपुरुषैकवचने -अ भू इ च्लि लुङ्
णिश्रिद्रुस्रुभ्यः कर्तरि चङ् इति च्लेः चङादेशे - अ भू इ चङ् लुङ्
लुङः तिबादेशे -अ भू इ चङ् तिप्
सम्प्रति धातोः द्वित्वं तथा ऊकारस्य वृद्धिश्च प्रप्नोति युगपत्, तयोर्द्वयोर्मध्ये आदौ द्वित्वमेव भवति - णिच्यजादेशो न द्वित्वे कर्तव्ये इति वचनमनुसृत्य  आदौ द्वित्वमेव
अ भू भू इ चङ् तिप्
इत्संज्ञकवर्णानां लोपात्परं -अ भू भू इ अ ति
अभ्यासकर्ये कृते - अबू भू इ अ ति
तिपः इकारलोपे - अबू भू इ अ त्
वृद्धौ कृतायां - अबू भाव् इ अ त्
णौ चङ्युपधायाः ह्रस्वः इति सूत्रेण - अ बू भव् इ अ त्
णेरनिटि इति णिचः लोपे - अबू भव् अत्
सन्वल्लघुनि चङ्परेनग्लोपे इति सन्वद्भावे - 
ओः पुयणज्यपरे इति सूत्रेण अभ्यास-उकारस्य इकारादेशे - अबीभवत् इति।

**Comment by drdhaval2785** [comment]
लुङि एव कथं भिन्ना प्रक्रिया ।
सर्वत्र तु णिचि
भावि + लडादयः इति उक्तं भवत्या ।
अत्र कथं भू स्थितावेव लकारोपस्थितिः ?

**Comment by drdhaval2785** [comment]
Now the output is corrected according to suggested prakriyA.

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/14270531/ba7af39c-fb0c-11e5-9218-d14b2b23324a.png)
