### ISSUE TITLE
भू णिच् लिट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#675]
भू णिच् लिट्
इत्संज्ञालोपानन्तरं - भू इ लिट्
वृद्धौ, अयादेशे - भावि लिट्
अनेकाच्त्वात् , कास्प्रत्ययादाममन्त्रे लिटि इति आम् प्रत्ययः - भावि आम् लिट्
णेरनिटि इति णिलोपे कर्तव्ये तं प्रबाध्य, अयामन्ताल्वाय्येत्न्विष्णुषु इति अयादेशे - भावयाम् लिट्
लिटः स्थाने कृञोनुप्रयुज्यते लिटि इति कृ, भू, अस् धातुषु प्रत्येकं पर्यायेणानुप्रयोगे - भावयाञ्चकार, भावयाम्बभूव, भावयामास इत्यादीनि रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/14270641/bab4c6f2-fb0d-11e5-95a5-ed25c8d4f81a.png)
