### ISSUE TITLE
डुदाञ्, जुहोत्यादिः लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#677]
By kartari śap (3.1.68) :

कर्तरि शप्‌ (३.१.६८) :

1 - डुदाञ्+शप्+तिप्

By juhotyādibhyaḥ śluḥ (2.4.75) :

जुहोत्यादिभ्यः श्लुः (२.४.७५) :

1 - डुदाञ्+तिप्

--------------------------------------------
अत्र कथं सानुबन्धकधातोरेव द्वित्वविधिः। डु-ञकारयोः इत्संज्ञा, लोपश्च भवेत्।

**Comment by drdhaval2785** [comment]
It was because of the shift mentioned in #673.
