### ISSUE TITLE
दैप् शोधने 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#679]
दापयति इति भवेत्।
Final forms are :

आखिरी रूप हैं :

1 - दैपयति
इति दर्शयति। पस्य इत्संज्ञायां, लोपानन्तरं दै इत्यस्य आदेच उपदेशे अशिति इति ऐकारस्य आत्वे दा इति भवति, आकारान्तत्वात् पुगागमे दापयति।

**Comment by drdhaval2785** [comment]
It was because of non application of Adeca upadeze'ziti because of #673
