### ISSUE TITLE
पै शोषणे 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#680]
पाययति।
अत्र पै धातोः आदेच उपदेशे अशिति इति सूत्रेण आत्वे कृते पा णिच्
अर्तिह्रीवेलीरीक्नूयीक्ष्माय्यातां पुग्णौ इति पुगागमे कर्तव्ये -
शाच्छासाह्वाव्यावेपां युक् इति युगागमे कृते पायि इति णिजन्तः धातुः।
तस्मात् लट् लकरे प्रथमपुरुषैकवचने - पाययति इति।

**Comment by drdhaval2785** [comment]
closed along with #679
