### ISSUE TITLE
गाङ् गतौ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#682]
गापयति इति भवेत्। 
Final forms are :

आखिरी रूप हैं :

1 - गाङयति
इति दर्शयति।

**Comment by mrudani** [comment]
अर्थात् इदमत्र स्पष्टम्। यत्र धातुषु इत्संज्ञकवर्णाः सन्ति, तेषामित्संज्ञा, लोपश्च नाभूत्, तेन रूपेषु भेदश्च।

**Comment by drdhaval2785** [comment]
Got it. Corrected.
