### ISSUE TITLE
ज्वरत्वरश्रिव्यविमवामुपधायाश्च॥ ६।४।२०

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#687]
In यङ्लुगन्तप्रक्रिया ज्वर लट्‌ वस्‌
सहजबोधे तु जाजूर्वः इति रूपं दत्तम्‌ ।
यन्त्रे तु जाज्वर्वः इति रूपं दत्तम्‌ ।

वकारस्य अनुनासिक्त्वं झल्त्वं वा नास्ति । कथं ज्वरत्वरश्रि... इत्यस्य प्रवृत्तिः स्यात्‌ ?

**Comment by mrudani** [comment]
ज्वरत्वरश्रि---- इत्यादिसूत्रस्य प्रवृत्तिरत्र नास्ति।

**Comment by drdhaval2785** [comment]
I also agree.
