### ISSUE TITLE
श्रै णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#692]
श्रा पाके इति पाकार्थे मित्। पाकभिन्नार्थे मित् न भवति। श्रापयति - स्वेदयति इत्यर्थः।

**Comment by drdhaval2785** [comment]
There is already one option in the frontend.
![capture](https://cloud.githubusercontent.com/assets/5755132/14402469/7125c71c-fe54-11e5-8738-12143274e573.png)
