### ISSUE TITLE
इण् गतौ, णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#699]
णौ गमिरबोधने इति सूत्रेण अबोधनार्थस्य इणः गमादोशो भवति। गमयति। बोधने न भवति - प्रत्याययति।

**Comment by drdhaval2785** [comment]
Option is there. Select appropriate one from frontend.
![capture](https://cloud.githubusercontent.com/assets/5755132/14409546/ecbc5bcc-ff33-11e5-9f0f-f0c11ebe52e1.png)
This will give
![capture](https://cloud.githubusercontent.com/assets/5755132/14409551/00a1a796-ff34-11e5-8cea-822563a49f97.png)

Whereas selecting 'abodhane' would give
![capture](https://cloud.githubusercontent.com/assets/5755132/14409555/1d977b32-ff34-11e5-97ef-9a3f9678a365.png)
