### ISSUE TITLE
ञिभी भये, णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#701]
भीस्म्योर्हेतुभये इति सूत्रेण हेतुभये एव आत्मनेपदं, तदभावे परस्मैपदमेव भवेत्।

**Comment by mrudani** [comment]
हेतुभयाभावे आत्वाभावः, षुगागमाभावः भाययति।

**Comment by drdhaval2785** [comment]
कर्त्रभिप्राये तु उभयपदित्वमस्त्येव णिचश्च इति सूत्रेण ।
हेतुभये आत्मनेपदित्वमिति मे मतिः ।

काशिकायान्तु `अकर्त्रभिप्रायार्थो ऽयमारम्भः।` इत्युक्तम्‌ ।

**Comment by drdhaval2785** [comment]
There is an option in the frontend.
![capture](https://cloud.githubusercontent.com/assets/5755132/14409657/51fc3b08-ff37-11e5-9c5f-cf29bc2bfb89.png)
