### ISSUE TITLE
ष्ठा, सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#710]
By sanyataḥ (7.4.79) :

सन्यतः (७.४.७९) :

1 - ति+स्था+स
---------------------------------------
आदेशप्रत्यययोः इति सस्य षत्वे - तिष्ठास इति भवेत्।

**Comment by drdhaval2785** [comment]
fa82bccaad95fd368299f0edc697ec590867dd51 closed this
