### ISSUE TITLE
णट नृत्तौ, णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#711]
By sanādyantā dhātavaḥ (3.1.32) :

सनाद्यन्ता धातवः (३.१.३२) :

1 - नटि
...........................................
घटादित्वात् घटादयो मितः इति गणसूत्रेण मित्तवमुक्त्वा, मितां ह्रस्वः इति ह्रस्वः वक्तव्यः।

**Comment by mrudani** [comment]
णट इति धातुद्वयं वर्तते, उभयोरपि वृत्तिरेवार्थः, तथापि एकः घटादिः, अपरः तद्भिन्नः, तस्मात् नाटयति इत्यपि रापं भवति।

**Comment by drdhaval2785** [comment]
I am not sure about the शास्त्रार्थः here.
Please clarify this stand.
It is easy to modify the code to give two alternate forms for 'Rawa' but I need clarity here.

**Comment by mrudani** [comment]
अस्य नृत्तम्, नृत्यमिति अर्थद्वयम्। गात्रविक्षेपमात्रं नृत्तम्। पदार्थाभिनयो नृत्यम्।

**Comment by drdhaval2785** [comment]
OK.
Got it.
These are the two verbs.
![capture](https://cloud.githubusercontent.com/assets/5755132/14974252/2b3103c4-1110-11e6-99e6-41fa46233ed2.png)

The first is not in घटादिः. The second is in घटादिः.
Now the machine is corrected. If you select the first, you get नाटयति, for second you get नटयति.
