### ISSUE TITLE
इण् गतौ, णिच् सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#715]
इण् धातोः णिच्-प्रत्यये णौ गमिरबोधने इति सूत्रेण गमादेशे मित्त्वात् गमयति इति बोधनार्थे भवेत्, तथैव सनि, सनि च इति सूत्रेण गमादेशः बोधनार्थे तथा जिगमिषति इति भवेत्।

**Comment by drdhaval2785** [comment]
Select proper input from the frontend.
This gives correct output.
![capture](https://cloud.githubusercontent.com/assets/5755132/14628323/648c5cbe-061a-11e6-8a78-e2ffbeed0a23.png)
