### ISSUE TITLE
रण्, णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#716]
दलिवलिस्खलिरणिध्वनित्रपिक्षपयश्चेति भोजः इति वचनेन मित्त्वं दर्शनीयम्। अन्यमते राणयति इत्येव भवेत्।

**Comment by drdhaval2785** [comment]
Happens.
What is missing ?
![capture](https://cloud.githubusercontent.com/assets/5755132/14628278/f0777552-0619-11e6-85ea-b7a7d38583bd.png)

**Comment by mrudani** [comment]
वचनेन मित्त्वं भवतीति स्पष्टता नास्तीति लिखितं स्यात्।

**Comment by drdhaval2785** [comment]
Now added it.
![capture](https://cloud.githubusercontent.com/assets/5755132/14973770/d096f28a-1109-11e6-9144-d96a574a4ea2.png)
