### ISSUE TITLE
ग॑दी॑ - देवशब्दे, चुरादि,आशीर्लिङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#734]
Whether gadI! is a mit curAdi dhAtu or not - requires to be investigated.
```
gAdyAstAm,gadI!,10.0399,ASIrliN,tas
```

**Comment by mrudani** [comment]
गद इति अदन्तः यथा - अर्थ, गर्व इत्यादयः। अत एव उपधायाः वृद्धिर्न। गदी इति ईदिन्नास्तीति, इका निर्देशः इति च व्याख्यातारः।
