### ISSUE TITLE
अर्थ, णिच्, चुरादिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#736]
आगर्वादात्मनेपदिनः इति गणसूत्रम्, तेन आत्मनेपदमेव भवेत्।

**Comment by drdhaval2785** [comment]
अत्र सनादिणिजः सत्त्वात्‌ णिचश्च इति उभयपदित्वं वा आगर्वीयत्वादात्मनेपदमेव इति निर्णेयम्‌ ।
