### ISSUE TITLE
ह्वेञ्, णिच्, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#742]
अजूहवत् इति भवेत्।

**Comment by drdhaval2785** [comment]
I am not able to understand the shastrartha in mAdhavIyadhAtuvRtti.
Please write step by step derivation.

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/15035554/a9a152c2-12a0-11e6-94e6-70abf2b1b58f.png)


This is the output by our code as of now.
If there are any errors, @mrudani may open a new issue.
