### ISSUE TITLE
ष्ठा, णिच्, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#744]
तिष्ठतेरित् इति सूत्रेण उपधायाः इकारादेशे अतिष्ठिपत् इत्यादीनि रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/f4c216f3b3778f229f7f224ca90de180688e8112 also closed this issue.
