### ISSUE TITLE
इक्, णिच्, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#747]
इण्वदिकः इति वार्तिकेन गमादेशः दर्शयेत्।

**Comment by mrudani** [comment]
अधिजिगमत् इति अन्तिमं रूपं भवेत्।

**Comment by drdhaval2785** [comment]
It already happens.
Select 'abodhane' from the options.
![capture](https://cloud.githubusercontent.com/assets/5755132/15048226/400002c6-1306-11e6-9696-2f82369f0871.png)

When I selected this, the output is fine. अध्यजीगमत्‌ happens.

See
![capture](https://cloud.githubusercontent.com/assets/5755132/15048276/7e146c3c-1306-11e6-93ef-507c9a19d4f0.png)
