### ISSUE TITLE
प्रीञ्, णिच्, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#751]
अपिप्रिणत् इति नुगागमकृतरूपमेव भवेत्। तदभावरूपं न भवेत् खलु।

**Comment by drdhaval2785** [comment]
माधवीयधातुवृत्तौ तु विभाषा लक्ष्यते ।

पश्यतु -
प्रीञ् तर्पणे
 अत्र केचन धातुवृत्तिकाराः [धूञ्प्रीञोर्नुग्वक्तव्यः] इति पठन्तः प्रीणयतोत्युदाहरन्ति हरदत्तस्तु धूञ्प्रीणोरिति श्नानुकरणाद्दैवादिकस्य नेत्याह दैवादिकग्रहणेनात्र चौरादिकोऽप्युपलक्षयितव्य इति पुरुषकारे तन्मते प्राययतीति भाव्यम् मैत्रेयोऽप्यनेनैवाभिप्रायेण प्राययतीत्युदाजहार 294

**Comment by mrudani** [comment]
लघुशब्देन्दुशेखरे, बालमनोरमायां च, हरदत्तमते नुगागमः विकल्पते इति दीक्षितेन उक्तत्वात्, नुगागमाभावरुपं भाष्यासम्मतमिति वर्तते।
