### ISSUE TITLE
लीङ्, णिच्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#753]
dṛ॒paṃ॑ - harṣamohanayoḥ, divādi 04.0036

दृ॒पँ॑ - हर्षमोहनयोः, दिवादि ०४.००३६, मा.धा., क्षी.त., धा.प्र.

By ṇicaśca (1.3.74) :

णिचश्च (१.३.७४) :

By seṭ dhātuḥ :

सेट् धातुः :

लुङ् लकार
लीङ् + णिच् + तिप् Go Back

**Comment by drdhaval2785** [comment]
This issue of wrong verb display is to be handled in #668, #669
