### ISSUE TITLE
ऋ, णिच्, लुङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#759]
By sarttiśāstyartibhyaśca (3.1.56) :

सर्त्तिशास्त्यर्तिभ्यश्च (३.१.५६) :

1 - ऋ+णिच्+अङ्+तिप्
-------------------------------------------
णिजन्तत्वात् चङ् भवेत्। आर्पिपत् इति भवेत्।

**Comment by drdhaval2785** [comment]
closed along with #757
