### ISSUE TITLE
च॑का॑सृँ॑ - दीप्तौ, अदादि, लट्‌, झि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#764]
Should it be चकासति / चकासन्ति ?

**Comment by drdhaval2785** [comment]
cakAsantu,cakAsf!,02.0069,low,Ji

This also needs to be evaluated

**Comment by mrudani** [comment]
चकासति, चकासतु इति भवेताम्। जक्षित्यादयः षट् इति अभ्यस्तसंज्ञायाः सत्त्वात् अदभ्यस्तात् इति अत् आदेशः।
