### ISSUE TITLE
जा॑गृ॑ - निद्राक्षये, अदादि, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#774]
Check the outcome

```
ajAgArIt,jAgf,02.0067,luN,tip
ajAgArizwAm,jAgf,02.0067,luN,tas
ajAgArizuH,jAgf,02.0067,luN,Ji
ajAgArIH,jAgf,02.0067,luN,sip
ajAgArizwam,jAgf,02.0067,luN,Tas
ajAgArizwa,jAgf,02.0067,luN,Ta
ajAgArizam,jAgf,02.0067,luN,mip
ajAgArizva,jAgf,02.0067,luN,vas
ajAgArizma,jAgf,02.0067,luN,mas
```

![capture](https://cloud.githubusercontent.com/assets/5755132/15095863/f3ea4566-14fb-11e6-8ef6-2be6051d662f.png)

**Comment by drdhaval2785** [comment]
अतो हलादेर्लघोः gives these alternative forms. Is it applicable?

**Comment by mrudani** [comment]
अचकासीदित्यत्र चकारादकारस्य वृद्धिवारणाय "येन नावयवधान"मिति न्यायेन यद्येकवर्णव्यवधानमेवाश्रीयते तदा त्वरक्षीदित्यत्रापि प्रसक्त्यभावाल्लघोरिति शक्यमकर्तुमित्याहुः।
परं जागृविषये न किंचिल्लब्धम्। क्वचिल्लघुशब्देन्दुशेखरे द्रष्टव्यम्। उपधायाः इत्येव भाति।

**Comment by drdhaval2785** [comment]
अत्र राकेशदासमहोदयाः शाब्दिकपरिषदि

अजागारीत् इति न भवति. अतो हलादेर्लघोः इत्यनेन प्राप्ता वैकल्पिकींं वृद्धिम् अतो ल्रान्तस्य इति नित्या वृद्धिः बाधते. ताम् अपि ह्म्यन्तक्षणश्वसजागृणिश्व्येदिताम् इति निषेधति.

**Comment by drdhaval2785** [comment]
Now only coding part remains.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0067 handles this.
