### ISSUE TITLE
pratyaya and vikaraNa sUtras for ArdhadhAtuka lakAras

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#79]
@mrudani 
आर्धधातुक लकारों के लिये सहजबोध में तैयार प्रत्यय दिये गये हैं ।
उन्हें सिद्ध करनेवाले सूत्रों को यहाँ लिस्ट कर दीजिए ।

**Comment by mrudani** [comment]
आदौ लिट्लकारस्य प्रत्यया अत्रोच्यन्ते
परस्मैपदानां प्रत्ययाः
परस्मैपदानां णलतुसुस्थलथुसणल्वमाः इति सूत्रेण णल् इत्यादयः आदेशाः भवन्ति.
आत्मनेपदानां
लिटस्तझयोरेशिरेच् - 
त - एश्
झ - इरेच्
टितआत्मनोपदानां टेरे,
थासस्से, एतानि सूत्राणि लिट्लकारस्य प्रत्ययनिर्माणे उपयुज्यमानानि.
लुट्लकारस्य प्रत्ययाः
लुट् लकारे विकरणप्रत्ययः वर्तते - तास्
स्यतासीरलृलुटोः इति सूत्रम्. परस्मैपदे आत्मनेपदे च तास् सामान्यतया भवतीति वेद्यम्.
लुटः प्रथमस्य डारौरसः इति सूत्रम्. एतदपि परस्मैपग़दात्मनेपदसामान्यम्.
आत्मनेपदानां विशेषसूत्राणि -
थासस्से, टित आत्मनेपदानां टेरे इति.
लृट्लकारस्य प्रत्ययाः
विकरणप्रत्ययः - स्य, स्यतासीलृलुटोः
परस्मैपदे - झोऽन्तः इति अन्तादेशः झस्य
आत्मनेपदे - टित आक्मनेपदानां टेरे, थासस्से
उभयत्र - अतो दीर्घो यञि इति सूत्रम्

**Comment by mrudani** [comment]
लृङ्लकारस्य प्रत्ययाः
विकरणप्रत्ययः - स्य
नित्यं ङितः वस्, मस् इत्यादिषु सलोपविधायकम्
इतश्च इति ति इत्यादिषु इकारलोपविधायकम्
झोऽन्तः इति झस्य अन्तादेशः, तत्र इकारस्य इतश्च इति इकारलोपः, अन्ते विद्यमानस्य तकारस्य संयोगान्तस्य लोपः इति लोपः
आतो ङितः इति स्येते, स्येताम् इत्यादिषु एकारः
अतो दीर्घो यञि इति स्यावहि इत्यादिषु दीर्घः

**Comment by mrudani** [comment]
लृङ् लकारे - तस्थस्थमिपां तान्तन्तामः इति सूत्रेण ताम्, तम्, त, आमः.
आशीर्लिङ्
परस्यामैपदे - यासुट् परस्मैपदेषूदात्तौ ङिच्च, लिङः सलोपोऽनन्त्यस्य
झेर्जुस्,
नित्यं ङितः,
इतश्च,
तस्थस्थमिपां तान्तन्तामः,
आत्मनेपदे - लिङः सीयुट्,
झस्य रन्
इटोऽत्,
सुट् तिथोः

**Comment by drdhaval2785** [comment]
I guess I have included them in coding.
If there are any deviations, a separate issue will be opened.
