### ISSUE TITLE
दॄ॑ - भये, भ्वादि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#790]
Why does 'RRta iddhAtoH' not apply here?
दरति is the form given in mAdhavIyadhAtuvRtti.

Our machine gives the following form.
![capture](https://cloud.githubusercontent.com/assets/5755132/15179877/e53cdbbc-179b-11e6-9d39-e70d82933b3b.png)

**Comment by mrudani** [comment]
"ॠत इद्धातो"रिति इत्त्वम्, "उदोष्ठ()पूर्वस्य" इति उत्त्वमन्तरङ्गमपि बाधित्वा गुणवृद्धी विप्रतिषेधसूत्रेण परत्वात्स्यातामिति भावः। इति बालमनोरमा। निष्कर्षः - गुणवृद्ध्योः यत्र अप्राप्तिः तत्रैवेदमिति। प्रकृते तु गुणप्रवृत्तिर्वर्तते, तस्मात् न ईत्वादेशः।
