### ISSUE TITLE
ष्टगे, णिच्, चङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#809]
अतिष्टगत् इत्यादीनि रूपाणि भवेयुः।
एकारस्य इत्संज्ञायां लोपे कृते, अतिष्टगत् इति भवति।

**Comment by drdhaval2785** [comment]
Do you mean ष्ठगे ?
अतिष्ठगत् happens.
![capture](https://cloud.githubusercontent.com/assets/5755132/15273210/3aa3ab88-1aaf-11e6-84d4-b4ef403b7d6d.png)
