### ISSUE TITLE
AdezapratyayayoH in upasargas ending with 'i'/'u'

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#827]
ष्व॒ञ्जँ॒ - परिष्वङ्गे, भ्वादि, लिट्‌ with परि
gave the following.

![capture](https://cloud.githubusercontent.com/assets/5755132/15280713/16a42cb0-1b51-11e6-8775-8fb524b82c31.png)

Correct one would read 'parizasvaje'
Note the 'z' after 'i'

**Comment by akprasad** [comment]
This is supported in vidyut:

https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=01.1131&upasarga=pari

Let me know if it is useful for me to comment on SanskritVerb bugs that vidyut fixes. I am doing so in the spirit of some of the issues you tagged me on earlier, but I also want to make sure my comments are useful.

**Comment by drdhaval2785** [comment]
It is absolutely useful when you tag the bugs of SanskritVerb that vidyut fixes. Please keep on doing so.
It helps me keep the plate declutterred.
