### ISSUE TITLE
र॒धँ॑ - हिंसासंराद्ध्योः, दिवादि, लिट्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#837]
mAdhavIyadhAtuvRtti mandates different forms in the following
```
reDva,raDa!,04.0090,liw,vas
reDma,raDa!,04.0090,liw,mas
```
mA.dhA. says it has to be रेन्ध्व / रेन्ध्म (But I am not convinced). 

ररन्धिव, ररन्धिम, रेन्ध्व, रेन्ध्म, ) "रधादिभ्यश्च'' इतीड्विकल्पो वलाद्यार्धधातुके तत्रानिटि थलि "झषस्तथोः'' इति थकारस्य धकारे पूर्वस्यजश्त्वे दकारः वस्मसोरेवाभ्यासलोपौ इडादौ लिट्यन्यस्मिंश्चाजादौ "रधिजभोरचि'' इति नुम् ( ररन्धिव, ररन्धिम ) इत्यत्र रन्ध्व रन्ध्म इति स्थिते "असंयोगाल्लिट्कित्'' इति कित्त्वात्पूर्वं परत्वादिट्, तत्रापि कित्त्वान्नित्यत्वान्नुमि सतीदानीं संयोगान्तत्वेन वस्मसोः कित्त्वाभावात् "अनिदिताम्'' इति नलोपाभावः हरदत्तस्तु इटः परत्वमाश्रित्य "नेट्यलिटि'' इत्यत्राह इटि सत्यजादित्वाद् नुमा भवितव्यम्, प्रागेव कित्त्वं प्राप्नोति न चालिटीत्यस्य वैयर्थ्यं, थल्यर्थवत्त्वात् एवं धातोरित्यनुवृत्तेरुपदेश एव नुम्भवति, अचीत्येषा विषयसप्तमीत्याह

**Comment by mrudani** [comment]
रेध्व, रेध्म इत्येव भवेताम्। माधवीयधतुवृत्तिरत्र नानुसरणीया।

**Comment by drdhaval2785** [comment]
अरे वाह ! माधवीयधातुवृत्ति में दोषोद्घाटन ? मशीन अच्छा कर रहा है
