### ISSUE TITLE
महिङ्‌ - ङित्‌ or not ?

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#84]
When trying to derive लृट्‌ लकार of षूञ्‌ धातु
```
1 - सू+स्यामहे
क्ङिति च (१.१.५) :
1 - सू+स्यामहे
इडागमे कृते :
1 - सू+स्यामहे
2 - सू+इस्यामहे
अचि श्नुधातुभ्रुवां य्वोरियङुवङौ (६.४.७७) 1:
1 - सू+स्यामहे
2 - सुव्+इस्यामहे
```

Note that the machine took महिङ्‌ to be ङित्‌  and prevented application of सार्वधातुकार्धधातुकयोः because of क्ङिति च.
Therefore there is no सो. Therefore, the application of अचि श्नुधातु...

in वहि it gives सविष्यामहे by सार्वधातुकार्धधातुकयोः

**Comment by drdhaval2785** [comment]
@mrudani 
Answer please

**Comment by mrudani** [comment]
वस्तुतः महिङः ङकारः प्रत्याहारार्थं कल्पितः, सु + इस्यामहे अत्र गुणः स्य इति आर्धदातुकं निमित्तीकृत्य आगतः.

**Comment by mrudani** [comment]
समाधानमुक्तमेव।
