### ISSUE TITLE
रि॑ - ऋऽ हिंसायाम्, स्वादि, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#840]
Check the forms.
```
arAyizwAm,ri,05.0032,luN,tas
arAyizuH,ri,05.0032,luN,Ji
arAyizwam,ri,05.0032,luN,Tas
arAyizwa,ri,05.0032,luN,Ta
arAyizam,ri,05.0032,luN,mip
arAyizva,ri,05.0032,luN,vas
arAyizma,ri,05.0032,luN,mas
```
Whereas UoHyd says
![capture](https://cloud.githubusercontent.com/assets/5755132/15317885/0bad5566-1c41-11e6-8371-eb2b4e30e9cc.png)

**Comment by mrudani** [comment]
By neṭi (7.2.4) :

नेटि (७.२.४) :

1 - अरै+इसीत्

By iṭa īṭi (8.2.28) :

इट ईटि (८.२.२८) :

1 - अरै+इईत्
-----------------------------------------------
अनिट्धातुरयम्। तस्मात् सिचः लोपो न। अ रि स् ईत्, वृद्धौ कृतायाम् अरैषीत्।
