### ISSUE TITLE
घृ॑ - प्रस्रवणे स्रावण इत्येके, चुरादि, आशीर्लिङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#841]
Check the forms.
I feel it should be 'GArayizIzwa'
```
GArIzIzwa,Gf,10.0152,ASIrliN,ta
GArIzIyAstAm,Gf,10.0152,ASIrliN,AtAm
GArIzIran,Gf,10.0152,ASIrliN,Ja
GArIzIzWAH,Gf,10.0152,ASIrliN,TAs
GArIzIyAsTAm,Gf,10.0152,ASIrliN,ATAm
GArIzIDvam,Gf,10.0152,ASIrliN,Dvam
GArIzIQvam,Gf,10.0152,ASIrliN,Dvam
GArIzIya,Gf,10.0152,ASIrliN,iw
GArIzIvahi,Gf,10.0152,ASIrliN,vahi
GArIzImahi,Gf,10.0152,ASIrliN,mahiN
```

**Comment by mrudani** [comment]
By uśca (1.2.12) :

उश्च (१.२.१२) :

1 - घार्+इ+सीस्त

By uśca (1.2.12) :

उश्च (१.२.१२) :

1 - घार्+इ+सीस्त
--------------------------------------------
अत्र उश्च इति सूत्रेण कित्त्वातिदेशः न, झलादिप्रत्ययस्याभावात्, तेन गुणनिषेधः न, तस्मात् घारयिषीष्ट इति भवेत्।

**Comment by mrudani** [comment]
लुङि तु आत्मनेपदे अजीघरत इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/16170377/4779789a-356e-11e6-885a-980d9a9b2253.png)

Closing now.
