### ISSUE TITLE
शु॑नँ॑ - गतौ, तुदादि

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#855]
Check the forms.
Our database says this verb is not in kuTAdi.
In that case it would  be शोनिता otherwise शुनिता
```
SonitAsi,Suna!,06.0062,luw,sip
SonitAsTaH,Suna!,06.0062,luw,Tas
SonitAsTa,Suna!,06.0062,luw,Ta
SonitAsmi,Suna!,06.0062,luw,mip
SonitAsvaH,Suna!,06.0062,luw,vas
SonitAsmaH,Suna!,06.0062,luw,mas
```

**Comment by mrudani** [comment]
शोनितासि इत्यादीन्येव भवेयुः। inria अत्र तु तथैव सन्ति। कुटादिष्वपि नास्ति एषः।
