### ISSUE TITLE
क्षि॑ - क्षीऽ हिंसायाम् क्षिर्भाषायामित्येके, स्वादि - सेट्‌ / अनिट्‌ 

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#886]
Check whether this verb is सेट्‌ / अनिट्‌
![capture](https://cloud.githubusercontent.com/assets/5755132/15453743/749d1416-203e-11e6-9bfe-7e7d485f0237.png)

Whereas the UoHyd gives अक्षैसीत्‌ etc.

**Comment by mrudani** [comment]
श्वि, श्रि इति धातुद्वयमेव इकारान्तेषु एकाक्षु सेट्।
