### ISSUE TITLE
उँ॑छृ॑दिँ॒॑र् - दीप्तिदेवनयोः, रुधादि, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#896]
Check लुङ्‌ all forms
```
acCfdizwAm-(u!Cfdi!r,luN,tas,ruDAdi,07.0352)
acCfdizuH-(u!Cfdi!r,luN,Ji,ruDAdi,07.0352)
acCfdizwam-(u!Cfdi!r,luN,Tas,ruDAdi,07.0352)
acCfdizwa-(u!Cfdi!r,luN,Ta,ruDAdi,07.0352)
acCfdizva-(u!Cfdi!r,luN,vas,ruDAdi,07.0352)
acCfdizma-(u!Cfdi!r,luN,mas,ruDAdi,07.0352)
```

**Comment by mrudani** [comment]
एतं धातुमेव न दर्शयति अत्र।

**Comment by drdhaval2785** [comment]
http://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=%E0%A4%89%E0%A4%81%E0%A4%9B%E0%A5%83%E0%A4%A6%E0%A4%BF%E0%A4%81%E0%A4%B0%E0%A5%8D&upasarga=&lakAra=luN&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&cond11=2&number=07.0352&cond50=2&removed_sutras=&step=11&type=tiGanta

**Comment by mrudani** [comment]
साधूनि रूपाणि।
