### ISSUE TITLE
जु॑डँ॑ - प्रेरणे, तुदादि 06.0051 जु॑डँ॑ - बन्धने, तुदादि 06.0106 (कुटादि / अकुटादि)

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#900]
This verb is seen in both 'kuTAdi' and non kuTAdi sets.
kuTadi one has ajuqIt and non kuTAdi one has ajoqIt.

@mrudani will have to list verbs in tudAdi gaNa which are seen in both kuTAdi and outside kuTAdi.

```
ajuqIt-(juqa!,luN,tip,tudAdi,06.0106)
ajuqizwAm-(juqa!,luN,tas,tudAdi,06.0106)
ajuqizuH-(juqa!,luN,Ji,tudAdi,06.0106)
ajuqIH-(juqa!,luN,sip,tudAdi,06.0106)
ajuqizwam-(juqa!,luN,Tas,tudAdi,06.0106)
ajuqizwa-(juqa!,luN,Ta,tudAdi,06.0106)
ajuqizam-(juqa!,luN,mip,tudAdi,06.0106)
ajuqizva-(juqa!,luN,vas,tudAdi,06.0106)
ajuqizma-(juqa!,luN,mas,tudAdi,06.0106)
```

**Comment by mrudani** [comment]
अयं बन्धने ङित्त्वार्थं कुटादौ पठिष्यते प्रेरणे चुरादौ इति माधवीयधातुवृत्तिः, अनेन बन्धनार्थकः कुटादिषु तद्भिन्नः चुरादिषु वर्तते इति।

**Comment by drdhaval2785** [comment]
There can be other such words too. We need a complete list of such verbs
where  one is in kuTAdi and other is not.

**Comment by drdhaval2785** [comment]
All verb forms have been examined againset UoHyd database. 
There were no such similar issues found as on 24 June 2016.
Closing.
