### ISSUE TITLE
णौ गमिरबोधने - अत उपधायाः

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#91]
1.	Nau gamirabodhane – 
when tried to code for this, the output was गम् + णि +… 
The computer applied ‘ato upadhAyAH’ to convert it to गाम्+णि.
How is it prevented from application ?

**Comment by drdhaval2785** [comment]
@mrudani 
Answer please

**Comment by mrudani** [comment]
गमः मित्त्वात् मितां ह्रस्वः भवतीति
