### ISSUE TITLE
kfza!, mfza!, spfSa! etc, लुङ्‌

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#929]
After extensive repeated testing,
These are the problem areas still pending.
All other issues are also noted down.

So suspectforms.txt is no longer having the earlier issues.

**Comment by mrudani** [comment]
अस्प्राक्षीत्, अस्पार्क्षीत्, अस्पृक्षति इति रूपत्रयं भवेत्।
अ स्पृश् च्लि तिप् स्पृश् धातोः स्पृशमृशकृष---- इत्यादिना विकल्पेन सिजादेशे कृते, अनुदात्तस्य चर्दुपधस्य इत्यादिना अमादेशे कृते, अस्प्राश् सीत्, शस्य षादेशे, अस्प्राक् सीत्, षत्वादेशे कृते अस्प्राक्षीत्, अमाभावे सिचिवृद्धिः परस्मैपदेषु इति वृद्धौ कृतायां - अस्पार्क्षीत्, सिजभावपक्षे शल इगुपधादनिटक्सः इति क्सादेशे - अस्पृक्षत् इति च। 
एवमेव मृश् - अम्राक्षीत्, अमार्क्षीत्, अमृक्षत्। कृश् - अक्राक्षीत्, अकार्क्षीत्, अकृक्षत्। तृप् - अत्राप्सीत्, अतर्प्सीत्, अतृपत्। दृप् - अद्राप्सीत्, अदारप्सीत्, अदृपत्।

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=06.0158 handles this.
