### ISSUE TITLE
आत्मनेपदेष्वनतः

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#930]
AtmanepadeSvanataH

It is pending to analyse its effect.
Right now it is not functioning well.

We are doing this replacement quite early in our code. We need to send it back or just ensure that all eligible verbs are covered beforehand.

**Comment by mrudani** [comment]
आत्मनेपदेषु यः अनकारान्तः अङ्गः, तस्मात् परस्य झस्य अत् इति आदेशः। यथा चिनु इति अनकारान्तमङ्गं, तस्मात् परस्य झ इत्यस्य स्थाने अत् इति आदेशः।

**Comment by drdhaval2785** [comment]
Now majority of these is covered. 
No erroneous forms found prima facie.
Closing this for now.
