### ISSUE TITLE
Publish generated forms in a more human-friendly manner

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/SanskritVerb#936]
www.sanskritworld.in/sanskrittool/SanskritVerb/generatedforms/verbforms.tar.gz is wonderful for machine processing. 

However, humans would find an alternate format (such as [this](https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-vyAkaraNa/jnu-tiNanta/jnu-tiNanta.babylon)), and devanAgarI rendering more useful. PS: It would be great if you could  automatically generate a babylon file like the one linked above.

**Comment by drdhaval2785** [comment]
Devanagari rendering done at www.sanskritworld.in/public/sanskrittool/SanskritVerb/generatedforms/verbformsdeva.tar.gz.

As regards the Babylon files, would you be kind enough to direct me to the proper documentation of the file system and its proposed uses, so that I can create the file automatically with necessary details @vvasuki ?

**Comment by vvasuki** [comment]
Wonderful, thanks for the devanAgarI rendering!

As to automatic generation of babylon files:
It's uses:
* We can pick it up and easily create stardict dictionaries for use by sanskrit speakers. (When they think "ugh - लोटि अंसतेः किं रूपं मध्यमपुरुषे बहुवचने?", or "अंसयताम् इति समीचीनं वा?", they can just look it up in their phone's colordict/ goldendict app.)

Regarding format: Just follow the example I quoted [here](https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-vyAkaraNa/jnu-tiNanta/jnu-tiNanta.babylon). Here is a simple alternative example from elsewhere:

> apple|apples
> the meaning of apple
> 
> 2dimensional|2dimensionale|2dimensionaler|2dimensionales|2dimensionalem|2dimensionalen
> two dimensional's meaning<br>the sencond line.
> 
> 
 Above two dictionary entries are seen. First line in each entry is the list of keywords for looking up that dictionary entry. Second line is the entry itself, which should be displayed to the user. Empty lines separate entries.

**Comment by drdhaval2785** [comment]
@vvasuki 
Babylon rendering at
www.sanskritworld.in/public/sanskrittool/SanskritVerb/generatedforms/verbforms.babylon.tar.gz
Warning - 2 MB compresses. 40 MB uncompressed.
May need some modification if to be used in smartphones. Otherwise it will kill the phones.

**Comment by vvasuki** [comment]
namaste dhavala,

I was hoping that you could produce entries like this:

	भू|भवन्ति|भवतः|भवामः|भवथः|भवति|भवामि|भवसि|भवथ|भवावः
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लट्) <br> भवति भवतः भवन्ति <br> भवसि भवथः भवथ <br> भवामि भवावः भवामः

	भू|भवाव|भवतु|भवतम्|भवानि|भवताम्|भवन्तु|भव|भवाम|भवत
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लोट्) <br> भवतु भवताम् भवन्तु <br> भव भवतम् भवत <br> भवानि भवाव भवाम

	भू|अभवताम्|अभवतम्|अभवाम|अभवत्|अभवन्|अभवाव|अभवम्|अभवत|अभवः
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लङ्) <br> अभवत् अभवताम् अभवन् <br> अभवः अभवतम् अभवत <br> अभवम् अभवाव अभवाम

	भू|भवेव|भवेत्|भवेयम्|भवेम|भवेताम्|भवेयुः|भवेतम्|भवेत|भवेः
	भू (सत्तायाम्, भ्वादिगण, परस्मै, विधिलिङ्) <br> भवेत् भवेताम् भवेयुः <br> भवेः भवेतम् भवेत <br> भवेयम् भवेव भवेम

	भू|बभूवतुः|बभूव|बभुविव|बभूवुः|बभूविथ|बभुवथुः|बभूविम
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लिट्) <br> बभूव बभूवतुः बभूवुः <br> बभूविथ बभुवथुः बभूव <br> बभूव बभुविव बभूविम

	भू|भवितास्थ|भवितास्वः|भवितारौ|भवितारः|भवितासि|भवितास्मः|भविता|भवितास्थः|भवितास्मि
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लुट्) <br> भविता भवितारौ भवितारः <br> भवितासि भवितास्थः भवितास्थ <br> भवितास्मि भवितास्वः भवितास्मः

	भू|भविष्यामि|भविष्यतः|भविष्यावः|भविष्यन्ति|भविष्यथ|भविष्यथः|भविष्यति|भविष्यसि|भविष्यामः
	भू (सत्तायाम्, भ्वादिगण, परस्मै, ऌट्) <br> भविष्यति भविष्यतः भविष्यन्ति <br> भविष्यसि भविष्यथः भविष्यथ <br> भविष्यामि भविष्यावः भविष्यामः

	भू|भूयास्त|भूयासुः|भूयास्ताम्|भूयास्म|भूयात्|भूयासम्|भूयास्तम्|भूयाः|भूयास्व
	भू (सत्तायाम्, भ्वादिगण, परस्मै, आशीर्लिङ्) <br> भूयात् भूयास्ताम् भूयासुः <br> भूयाः भूयास्तम् भूयास्त <br> भूयासम् भूयास्व भूयास्म

	भू|अभूम|अभूवन्|अभूत|अभूः|अभूताम्|अभूतम्|अभूव|अभूत्|अभूवम्
	भू (सत्तायाम्, भ्वादिगण, परस्मै, लुङ्) <br> अभूत् अभूताम् अभूवन् <br> अभूः अभूतम् अभूत <br> अभूवम् अभूव अभूम

	भू|अभविष्याव|अभविष्यताम्|अभविष्यम्|अभविष्यन्|अभविष्यतम्|अभविष्यत|अभविष्यत्|अभविष्याम|अभविष्यः
	भू (सत्तायाम्, भ्वादिगण, परस्मै, ॡङ्) <br> अभविष्यत् अभविष्यताम् अभविष्यन् <br> अभविष्यः अभविष्यतम् अभविष्यत <br> अभविष्यम् अभविष्याव अभविष्याम

Reason is that when people look up a certain verb declension, they want to see (in a familiar way) other forms in the same lakAra as well.

**Comment by vvasuki** [comment]
Example of what a user will see on looking up भवति -
![image](https://cloud.githubusercontent.com/assets/2664797/16363761/a6286f1a-3b89-11e6-9da3-6726d0892617.png)
****

**Comment by drdhaval2785** [comment]
Yes. I will try. I tried to club them together, but it was too tedious and
slow.

**Comment by drdhaval2785** [comment]
Now the file has been updated.
The first two entries are of verb(without anubandha) and verb(with anubandha).
For bhU, it doesn't make much difference, but for let us say अहिँ / अंह्‌, both should land to the entry. So I have just made this small change to the format suggested by you.
www.sanskritworld.in/public/sanskrittool/SanskritVerb/generatedforms/verbforms.babylon.tar.gz
1.6 MB compressed
18 MB uncompressed.

Remvoed the earlier file.

Now the entries are like this -
```
भू|भू|भवति|भवतः|भवन्ति|भवसि|भवथः|भवथ|भवामि|भवावः|भवामः
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लट्) <br/> भवति भवतः भवन्ति <br/> भवसि भवथः भवथ <br/> भवामि भवावः भवामः

भू|भू|बभूव|बभूवतुः|बभूवुः|बभूविथ|बभूवथुः|बभूव|बभूव|बभूविव|बभूविम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लिट्) <br/> बभूव बभूवतुः बभूवुः <br/> बभूविथ बभूवथुः बभूव <br/> बभूव बभूविव बभूविम

भू|भू|भविता|भवितारौ|भवितारः|भवितासि|भवितास्थः|भवितास्थ|भवितास्मि|भवितास्वः|भवितास्मः
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लुट्) <br/> भविता भवितारौ भवितारः <br/> भवितासि भवितास्थः भवितास्थ <br/> भवितास्मि भवितास्वः भवितास्मः

भू|भू|भविष्यति|भविष्यतः|भविष्यन्ति|भविष्यसि|भविष्यथः|भविष्यथ|भविष्यामि|भविष्यावः|भविष्यामः
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लृट्) <br/> भविष्यति भविष्यतः भविष्यन्ति <br/> भविष्यसि भविष्यथः भविष्यथ <br/> भविष्यामि भविष्यावः भविष्यामः

भू|भू|भवतु|भवतात्|भवताम्|भवन्तु|भव|भवतात्|भवतम्|भवत|भवानि|भवाव|भवाम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लोट्) <br/> भवतु भवतात् भवताम् भवन्तु <br/> भव <br/> भवतात् भवतम् भवत <br/> भवानि भवाव भवाम

भू|भू|अभवत्|अभवताम्|अभवन्|अभवः|अभवतम्|अभवत|अभवम्|अभवाव|अभवाम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लङ्) <br/> अभवत् अभवताम् अभवन् <br/> अभवः अभवतम् अभवत <br/> अभवम् अभवाव अभवाम

भू|भू|भवेत्|भवेताम्|भवेयुः|भवेः|भवेतम्|भवेत|भवेयम्|भवेव|भवेम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, विधिलिङ्) <br/> भवेत् भवेताम् भवेयुः <br/> भवेः भवेतम् भवेत <br/> भवेयम् भवेव भवेम

भू|भू|भूयात्|भूयास्ताम्|भूयासुः|भूयाः|भूयास्तम्|भूयास्त|भूयासम्|भूयास्व|भूयास्म
भू (सत्तायाम्, भ्वादिः, प०, सेट्, आशीर्लिङ्) <br/> भूयात् भूयास्ताम् भूयासुः <br/> भूयाः भूयास्तम् भूयास्त <br/> भूयासम् भूयास्व भूयास्म

भू|भू|अभूत्|अभूताम्|अभूवन्|अभूः|अभूतम्|अभूत|अभूवम्|अभूव|अभूम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लुङ्) <br/> अभूत् अभूताम् अभूवन् <br/> अभूः अभूतम् अभूत <br/> अभूवम् अभूव अभूम

भू|भू|अभविष्यत्|अभविष्यताम्|अभविष्यन्|अभविष्यः|अभविष्यतम्|अभविष्यत|अभविष्यम्|अभविष्याव|अभविष्याम
भू (सत्तायाम्, भ्वादिः, प०, सेट्, लृङ्) <br/> अभविष्यत् अभविष्यताम् अभविष्यन् <br/> अभविष्यः अभविष्यतम् अभविष्यत <br/> अभविष्यम् अभविष्याव अभविष्याम
```

**Comment by vvasuki** [comment]
Wonderful!

Stardict converter does not recognize the tag "br/" - "unknown tag: br/". I'm fixing this in my copy of the file. Can you please fix your program?

"The first two entries are of verb(without anubandha) and verb(with anubandha)." is a great great idea. But, while keeping that, can you apply a filter to ensure that duplicate headwords like भू|भू do not appear? These duplicates produce lots of warnings which will flood out genuine problems during the stardict-conversion process.

**Comment by vvasuki** [comment]
(PS: Even the second request above is not high priority - I am fixing that on my end, but something for the future since you will produce newer versions of this file.)

Example output in startdict programs - 
![image](https://cloud.githubusercontent.com/assets/2664797/16386418/8f3fe780-3c45-11e6-8579-2c5f69e2a345.png)

**Comment by drdhaval2785** [comment]
Both are decent proposals. I will correct the program on my end, so that
the issue doesnt crop up again.
