### ISSUE TITLE
श्रु, ज्ञा सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#940]
शुश्रूषते, जिज्ञासते इति आत्मनेपदप्रयोगाः भवन्ति खलु, तर्हि पूर्ववत्सनः इति सूत्रस्यावश्यकता नास्ति।

**Comment by drdhaval2785** [comment]
Ok. Got it. Dont write this problem again in other verbs. I will correct it
soon. Not a too difficult one.

**Comment by drdhaval2785** [comment]
Closed along with https://github.com/drdhaval2785/samasasplitter/commit/1f3bcb37bda4384f4e924d835d02535110e1e327

#938
