### ISSUE TITLE
ह्वेञ्, सन्, लट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#941]
जुहूशति-ते इति भवेत्।
अभ्यासश्च इति सूत्रेण द्वित्वात् पूर्वमेव सम्प्रसारणे कृते, अभ्यासकार्ये च कृते - जुहूषति-ते इत्यादीनि रूपाणि भवेयुः।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/df518e7f1b301cd138d8c3140648baa579811f5d
