### ISSUE TITLE
विद, सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#949]
वि॑दँ॒ - चेतनाख्याननिवासेषु, अदादि 02.0059,
वि॑दँ॑ - ज्ञाने, अदादि 02.0059
एतयोः रूपाणि न दर्शयति।

**Comment by drdhaval2785** [comment]
There are two verbs in the same gaNa with different padas in our database.
So earlier the machine used to stop without showing anything.
Right now, I am handling with a graceful error message, but derive as ubhayapadi.
If there are some errors, let me know. 
Closing for now.
