### ISSUE TITLE
कृड, सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#950]
By आदेशप्रत्यययोः (8.3.59) :

आदेशप्रत्यययोः (८.३.५९) :

1 - चि+कृड्+इष

By आदेशप्रत्यययोः (8.3.59) :

आदेशप्रत्यययोः (८.३.५९) :

1 - चि+कृड्+इष
------------------------------
एकस्यैव सूत्रस्यावृत्तिः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/17661492/260757b0-62fd-11e6-85f2-6546c88a8e8a.png)

Now there is no duplication.
