### ISSUE TITLE
प्रच्छ, सन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#951]
धातुः प्रछ इति किमर्थम्।

**Comment by drdhaval2785** [comment]
तत्र तुगागमस्तु छे च इत्यनेनैव । अतः मूलदशायां तु प्रछ एव धातुरिति मे मतिः ।

**Comment by drdhaval2785** [comment]
( पृच्छति ) "छे च'' इति तुकि "स्तोः श्चुना श्चुः'' इति श्चुत्वम्  - mAdhavIya. So there is a tugAgama. If the verb itself had tugAgama, why would there be any need for tugAgama?

**Comment by drdhaval2785** [comment]
Pending to handle.
