### ISSUE TITLE
ष्ठा, यङु

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#954]
Final form

अन्तिमं रूपम्‌

1 - तेस्थीयते
---------------------------
तेष्ठीयते इति भवेत्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/17661522/49b89318-62fd-11e6-86c7-da866a79cb8f.png)

Corrected now.
