### ISSUE TITLE
व्येञ्, यङ्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritVerb#956]
By nityaṃ karoteḥ (6.4.108) :

नित्यं करोतेः (६.४.१०८) :

1 - वि+य

---------------------
सम्प्रसारणाच्च इति पूर्वरूपं भवेत्।

**Comment by drdhaval2785** [comment]
Wrong numbering 6.4.108 instead of correct 6.1.108 of samprasAraNAcca.
Corrected now.
