### ISSUE TITLE
pysan comparision - corrections

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#963]
Here I will note the discussions going on in https://github.com/funderburkjim/elispsanskrit/issues/ where Jim is comparing the SanskritVerb and pysan generations.
This is a list where I will jot down the places which require modification in SanskritVerb.

**Comment by drdhaval2785** [comment]
1 https://github.com/funderburkjim/elispsanskrit/issues/43#issuecomment-247425460

**Comment by funderburkjim** [comment]
Regarding roots `sPiwa!` and `sPiwwa!` in verbdata:
```
sPiwa!:snehane ityeke:sPiw:10:0129:u:sew:स्फि॑टँ॑::1179:1267::
sPiwwa!:hiMsAyAm:sPiw:10:0056:u:sew:स्फि॑ट्टँ॑::1179:1267:sPitt1_sPittaz_curAxiH+hiMsAyAm:
```
Should the root without anubandha for `sPiwwa!` be `sPiwwa`  ?

**Comment by funderburkjim** [comment]
Why do these conjugations include the prefix 'aDi' ? Is that right?
```
ik:smaraRe ayamapyaDipUrvaH:i:02:0042:pa:aniw:इ॒क्:697:719:736:i3_ik_axAxiH+smaraNe:
ik pre 02.0042P:[aDyeti aDItaH aDiyanti aDyezi aDITaH aDITa aDyemi aDIvaH aDImaH]

iN pre 02.0041A:[aDIte aDIyAte aDIyate aDIze aDIyATe aDIDve aDIye aDIvahe aDImahe]
iN:aDyayane nityamaDipUrvaH:i:02:0041:A:aniw:इ॒ङ्:696:718:735:i2_if_axAxiH+aXyayane:
```

**Comment by funderburkjim** [comment]
Shouldn't gana for 'Sru' be 05 in verbdata?
```
Sru:SravaRe:Sru:01:1092:pa:aniw:श्रु॒:600:623:638:Sru1_Sru_BvAxiH+SravaNe:289
```

**Comment by funderburkjim** [comment]
Thanks for explanation of Sru.  Very confusing to the non-specialist like me.  I had noted that Kale, Wilson, and MadhavIya also all say class 1, in agreement with your explanation.

**Comment by drdhaval2785** [comment]
This is enough for one issue. Will start another issue for other corrections.
