### ISSUE TITLE
missing root name in generatedforms

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/SanskritVerb#973]
(This comment based on version with hash 8aabf1d5d6fde9d355a651a9943ee07c5b7bef26 of 1 day ago)

In the generateforms.xml reconstructed locally,  there are numerous cases of forms with no root,
e.g.
```
<f form="+tArO"><root name="" num="07.0316"/><luw/><tas/></f>
```

These are also odd because, at least in a couple I checked, the "num" value does not appear in verbdata.php.  For instance `07.0316` is not in verbdata.

When looking at wrongformfinder.sh, I DO see '07.0316'.   So, the problem is likely that
wrongformfinder.sh has not been updated to be in sync with verbdata.php.

The solution might be for wrongformfinder.sh to
*  first run a small php program to extract the gana-number list from verbdata.php and write that to a new file (lets call it gana-number.txt)
* modify wrongformfinder construction of LIST1 bash variable to get the value from gana-number.txt

Here's a little sample of how this might work, using 'temp.txt' in place of 'gana-number.txt' and
'temp.sh' in place of 'wrongformfinder.sh'.
* Make temp.txt to be in the form of a shell script initializing the LIST1 array:
```
LIST1=(10.0460 10.0328 01.0722 01.0901 01.0742 01.0902)

```

* Make temp.sh as
```
source temp.txt
number=1
for VALUE1 in "${LIST1[@]}"
do
	echo "$number - processing verb number $VALUE1 "
        ((number++))
done
```

Then, running 'sh temp.sh' under GitBash gives
```
$ sh temp.sh
1 - processing verb number 10.0460
2 - processing verb number 10.0328
3 - processing verb number 01.0722
4 - processing verb number 01.0901
5 - processing verb number 01.0742
6 - processing verb number 01.0902
```

The magic is in the 'source' command, which seems to in effect be like a php 'require';  that is,
'source temp.txt' executes the temp.txt file as a bash script, AND somehow, when run within the
parent temp.sh script, imports the LIST1 value as a variable in the temp.sh script.

There are probably other ways to have wrongformfinder.sh be automatically in sync with
verbdata.

**Comment by drdhaval2785** [comment]
Seems a wonderful way. Let me try do it and regenerate generatedforms.xml.
There are 1000+ entries in syspectforms.txt. That will also require correction. Let me do this stuff and rerun generatedforms.xml. Wait till then.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/857ecf6f2f3901d074fd37a0eadc24db3e36302c
This commit closed the issue.
Also changed some of the script encoding from 'utf-8 with BOM' to 'utf-8'.
Earlier that used to give some odd letters in terminal usage.
