### ISSUE TITLE
वॄतो वा

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritVerb#98]
When deriving jF dhAtu ASIrliN forms - I get the following. 
sahajabodha is silent on applicability of vRRto vA. It gives only 'i' form and not 'I' form.
@mrudani will have to confirm whether it is OK to apply vRRto vA in this case ?

By vRRto vA (7.2.38) :
वॄतो वा (७.२.३८) :
1 - जॄ+सीयास्ताम्
2 - जर्+इसीयास्ताम्
3 - जर्+ईसीयास्ताम्

**Comment by mrudani** [comment]
अत्र वॄतो वा उति सूत्रस्यप्रवृत्तिरवश्यं भवति. तेन इटः दीर्घः भवति.
